/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.mbusa.avro.dto;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class BtcServCmpgnDlrDtlDTO extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 6829749888744962697L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"BtcServCmpgnDlrDtlDTO\",\"namespace\":\"com.mbusa.avro.dto\",\"fields\":[{\"name\":\"CDE_CTRY\",\"type\":\"string\"},{\"name\":\"CDE_DLR\",\"type\":\"string\"},{\"name\":\"NUM_CMPGN\",\"type\":\"string\"},{\"name\":\"DTE_YR\",\"type\":\"string\"},{\"name\":\"DTE_MTH\",\"type\":\"string\"},{\"name\":\"DTE_WK\",\"type\":\"string\"},{\"name\":\"CNT_TOT_VEH\",\"type\":\"string\"},{\"name\":\"CNT_TOT_RPRD_VEH\",\"type\":\"string\"},{\"name\":\"CNT_TOT_TARG_VEH\",\"type\":\"string\"},{\"name\":\"PCT_TRGT_RATE\",\"type\":\"string\"},{\"name\":\"PCT_CML_RATE\",\"type\":\"string\"},{\"name\":\"DTS_CREA\",\"type\":\"string\"},{\"name\":\"ID_CREA_USER\",\"type\":\"string\"},{\"name\":\"DTS_LAST_UPDT\",\"type\":\"string\"},{\"name\":\"ID_LAST_UPDT_USER\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<BtcServCmpgnDlrDtlDTO> ENCODER =
      new BinaryMessageEncoder<BtcServCmpgnDlrDtlDTO>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<BtcServCmpgnDlrDtlDTO> DECODER =
      new BinaryMessageDecoder<BtcServCmpgnDlrDtlDTO>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<BtcServCmpgnDlrDtlDTO> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<BtcServCmpgnDlrDtlDTO> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<BtcServCmpgnDlrDtlDTO> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<BtcServCmpgnDlrDtlDTO>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this BtcServCmpgnDlrDtlDTO to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a BtcServCmpgnDlrDtlDTO from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a BtcServCmpgnDlrDtlDTO instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static BtcServCmpgnDlrDtlDTO fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private java.lang.CharSequence CDE_CTRY;
   private java.lang.CharSequence CDE_DLR;
   private java.lang.CharSequence NUM_CMPGN;
   private java.lang.CharSequence DTE_YR;
   private java.lang.CharSequence DTE_MTH;
   private java.lang.CharSequence DTE_WK;
   private java.lang.CharSequence CNT_TOT_VEH;
   private java.lang.CharSequence CNT_TOT_RPRD_VEH;
   private java.lang.CharSequence CNT_TOT_TARG_VEH;
   private java.lang.CharSequence PCT_TRGT_RATE;
   private java.lang.CharSequence PCT_CML_RATE;
   private java.lang.CharSequence DTS_CREA;
   private java.lang.CharSequence ID_CREA_USER;
   private java.lang.CharSequence DTS_LAST_UPDT;
   private java.lang.CharSequence ID_LAST_UPDT_USER;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public BtcServCmpgnDlrDtlDTO() {}

  /**
   * All-args constructor.
   * @param CDE_CTRY The new value for CDE_CTRY
   * @param CDE_DLR The new value for CDE_DLR
   * @param NUM_CMPGN The new value for NUM_CMPGN
   * @param DTE_YR The new value for DTE_YR
   * @param DTE_MTH The new value for DTE_MTH
   * @param DTE_WK The new value for DTE_WK
   * @param CNT_TOT_VEH The new value for CNT_TOT_VEH
   * @param CNT_TOT_RPRD_VEH The new value for CNT_TOT_RPRD_VEH
   * @param CNT_TOT_TARG_VEH The new value for CNT_TOT_TARG_VEH
   * @param PCT_TRGT_RATE The new value for PCT_TRGT_RATE
   * @param PCT_CML_RATE The new value for PCT_CML_RATE
   * @param DTS_CREA The new value for DTS_CREA
   * @param ID_CREA_USER The new value for ID_CREA_USER
   * @param DTS_LAST_UPDT The new value for DTS_LAST_UPDT
   * @param ID_LAST_UPDT_USER The new value for ID_LAST_UPDT_USER
   */
  public BtcServCmpgnDlrDtlDTO(java.lang.CharSequence CDE_CTRY, java.lang.CharSequence CDE_DLR, java.lang.CharSequence NUM_CMPGN, java.lang.CharSequence DTE_YR, java.lang.CharSequence DTE_MTH, java.lang.CharSequence DTE_WK, java.lang.CharSequence CNT_TOT_VEH, java.lang.CharSequence CNT_TOT_RPRD_VEH, java.lang.CharSequence CNT_TOT_TARG_VEH, java.lang.CharSequence PCT_TRGT_RATE, java.lang.CharSequence PCT_CML_RATE, java.lang.CharSequence DTS_CREA, java.lang.CharSequence ID_CREA_USER, java.lang.CharSequence DTS_LAST_UPDT, java.lang.CharSequence ID_LAST_UPDT_USER) {
    this.CDE_CTRY = CDE_CTRY;
    this.CDE_DLR = CDE_DLR;
    this.NUM_CMPGN = NUM_CMPGN;
    this.DTE_YR = DTE_YR;
    this.DTE_MTH = DTE_MTH;
    this.DTE_WK = DTE_WK;
    this.CNT_TOT_VEH = CNT_TOT_VEH;
    this.CNT_TOT_RPRD_VEH = CNT_TOT_RPRD_VEH;
    this.CNT_TOT_TARG_VEH = CNT_TOT_TARG_VEH;
    this.PCT_TRGT_RATE = PCT_TRGT_RATE;
    this.PCT_CML_RATE = PCT_CML_RATE;
    this.DTS_CREA = DTS_CREA;
    this.ID_CREA_USER = ID_CREA_USER;
    this.DTS_LAST_UPDT = DTS_LAST_UPDT;
    this.ID_LAST_UPDT_USER = ID_LAST_UPDT_USER;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return CDE_CTRY;
    case 1: return CDE_DLR;
    case 2: return NUM_CMPGN;
    case 3: return DTE_YR;
    case 4: return DTE_MTH;
    case 5: return DTE_WK;
    case 6: return CNT_TOT_VEH;
    case 7: return CNT_TOT_RPRD_VEH;
    case 8: return CNT_TOT_TARG_VEH;
    case 9: return PCT_TRGT_RATE;
    case 10: return PCT_CML_RATE;
    case 11: return DTS_CREA;
    case 12: return ID_CREA_USER;
    case 13: return DTS_LAST_UPDT;
    case 14: return ID_LAST_UPDT_USER;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: CDE_CTRY = (java.lang.CharSequence)value$; break;
    case 1: CDE_DLR = (java.lang.CharSequence)value$; break;
    case 2: NUM_CMPGN = (java.lang.CharSequence)value$; break;
    case 3: DTE_YR = (java.lang.CharSequence)value$; break;
    case 4: DTE_MTH = (java.lang.CharSequence)value$; break;
    case 5: DTE_WK = (java.lang.CharSequence)value$; break;
    case 6: CNT_TOT_VEH = (java.lang.CharSequence)value$; break;
    case 7: CNT_TOT_RPRD_VEH = (java.lang.CharSequence)value$; break;
    case 8: CNT_TOT_TARG_VEH = (java.lang.CharSequence)value$; break;
    case 9: PCT_TRGT_RATE = (java.lang.CharSequence)value$; break;
    case 10: PCT_CML_RATE = (java.lang.CharSequence)value$; break;
    case 11: DTS_CREA = (java.lang.CharSequence)value$; break;
    case 12: ID_CREA_USER = (java.lang.CharSequence)value$; break;
    case 13: DTS_LAST_UPDT = (java.lang.CharSequence)value$; break;
    case 14: ID_LAST_UPDT_USER = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'CDE_CTRY' field.
   * @return The value of the 'CDE_CTRY' field.
   */
  public java.lang.CharSequence getCDECTRY() {
    return CDE_CTRY;
  }


  /**
   * Sets the value of the 'CDE_CTRY' field.
   * @param value the value to set.
   */
  public void setCDECTRY(java.lang.CharSequence value) {
    this.CDE_CTRY = value;
  }

  /**
   * Gets the value of the 'CDE_DLR' field.
   * @return The value of the 'CDE_DLR' field.
   */
  public java.lang.CharSequence getCDEDLR() {
    return CDE_DLR;
  }


  /**
   * Sets the value of the 'CDE_DLR' field.
   * @param value the value to set.
   */
  public void setCDEDLR(java.lang.CharSequence value) {
    this.CDE_DLR = value;
  }

  /**
   * Gets the value of the 'NUM_CMPGN' field.
   * @return The value of the 'NUM_CMPGN' field.
   */
  public java.lang.CharSequence getNUMCMPGN() {
    return NUM_CMPGN;
  }


  /**
   * Sets the value of the 'NUM_CMPGN' field.
   * @param value the value to set.
   */
  public void setNUMCMPGN(java.lang.CharSequence value) {
    this.NUM_CMPGN = value;
  }

  /**
   * Gets the value of the 'DTE_YR' field.
   * @return The value of the 'DTE_YR' field.
   */
  public java.lang.CharSequence getDTEYR() {
    return DTE_YR;
  }


  /**
   * Sets the value of the 'DTE_YR' field.
   * @param value the value to set.
   */
  public void setDTEYR(java.lang.CharSequence value) {
    this.DTE_YR = value;
  }

  /**
   * Gets the value of the 'DTE_MTH' field.
   * @return The value of the 'DTE_MTH' field.
   */
  public java.lang.CharSequence getDTEMTH() {
    return DTE_MTH;
  }


  /**
   * Sets the value of the 'DTE_MTH' field.
   * @param value the value to set.
   */
  public void setDTEMTH(java.lang.CharSequence value) {
    this.DTE_MTH = value;
  }

  /**
   * Gets the value of the 'DTE_WK' field.
   * @return The value of the 'DTE_WK' field.
   */
  public java.lang.CharSequence getDTEWK() {
    return DTE_WK;
  }


  /**
   * Sets the value of the 'DTE_WK' field.
   * @param value the value to set.
   */
  public void setDTEWK(java.lang.CharSequence value) {
    this.DTE_WK = value;
  }

  /**
   * Gets the value of the 'CNT_TOT_VEH' field.
   * @return The value of the 'CNT_TOT_VEH' field.
   */
  public java.lang.CharSequence getCNTTOTVEH() {
    return CNT_TOT_VEH;
  }


  /**
   * Sets the value of the 'CNT_TOT_VEH' field.
   * @param value the value to set.
   */
  public void setCNTTOTVEH(java.lang.CharSequence value) {
    this.CNT_TOT_VEH = value;
  }

  /**
   * Gets the value of the 'CNT_TOT_RPRD_VEH' field.
   * @return The value of the 'CNT_TOT_RPRD_VEH' field.
   */
  public java.lang.CharSequence getCNTTOTRPRDVEH() {
    return CNT_TOT_RPRD_VEH;
  }


  /**
   * Sets the value of the 'CNT_TOT_RPRD_VEH' field.
   * @param value the value to set.
   */
  public void setCNTTOTRPRDVEH(java.lang.CharSequence value) {
    this.CNT_TOT_RPRD_VEH = value;
  }

  /**
   * Gets the value of the 'CNT_TOT_TARG_VEH' field.
   * @return The value of the 'CNT_TOT_TARG_VEH' field.
   */
  public java.lang.CharSequence getCNTTOTTARGVEH() {
    return CNT_TOT_TARG_VEH;
  }


  /**
   * Sets the value of the 'CNT_TOT_TARG_VEH' field.
   * @param value the value to set.
   */
  public void setCNTTOTTARGVEH(java.lang.CharSequence value) {
    this.CNT_TOT_TARG_VEH = value;
  }

  /**
   * Gets the value of the 'PCT_TRGT_RATE' field.
   * @return The value of the 'PCT_TRGT_RATE' field.
   */
  public java.lang.CharSequence getPCTTRGTRATE() {
    return PCT_TRGT_RATE;
  }


  /**
   * Sets the value of the 'PCT_TRGT_RATE' field.
   * @param value the value to set.
   */
  public void setPCTTRGTRATE(java.lang.CharSequence value) {
    this.PCT_TRGT_RATE = value;
  }

  /**
   * Gets the value of the 'PCT_CML_RATE' field.
   * @return The value of the 'PCT_CML_RATE' field.
   */
  public java.lang.CharSequence getPCTCMLRATE() {
    return PCT_CML_RATE;
  }


  /**
   * Sets the value of the 'PCT_CML_RATE' field.
   * @param value the value to set.
   */
  public void setPCTCMLRATE(java.lang.CharSequence value) {
    this.PCT_CML_RATE = value;
  }

  /**
   * Gets the value of the 'DTS_CREA' field.
   * @return The value of the 'DTS_CREA' field.
   */
  public java.lang.CharSequence getDTSCREA() {
    return DTS_CREA;
  }


  /**
   * Sets the value of the 'DTS_CREA' field.
   * @param value the value to set.
   */
  public void setDTSCREA(java.lang.CharSequence value) {
    this.DTS_CREA = value;
  }

  /**
   * Gets the value of the 'ID_CREA_USER' field.
   * @return The value of the 'ID_CREA_USER' field.
   */
  public java.lang.CharSequence getIDCREAUSER() {
    return ID_CREA_USER;
  }


  /**
   * Sets the value of the 'ID_CREA_USER' field.
   * @param value the value to set.
   */
  public void setIDCREAUSER(java.lang.CharSequence value) {
    this.ID_CREA_USER = value;
  }

  /**
   * Gets the value of the 'DTS_LAST_UPDT' field.
   * @return The value of the 'DTS_LAST_UPDT' field.
   */
  public java.lang.CharSequence getDTSLASTUPDT() {
    return DTS_LAST_UPDT;
  }


  /**
   * Sets the value of the 'DTS_LAST_UPDT' field.
   * @param value the value to set.
   */
  public void setDTSLASTUPDT(java.lang.CharSequence value) {
    this.DTS_LAST_UPDT = value;
  }

  /**
   * Gets the value of the 'ID_LAST_UPDT_USER' field.
   * @return The value of the 'ID_LAST_UPDT_USER' field.
   */
  public java.lang.CharSequence getIDLASTUPDTUSER() {
    return ID_LAST_UPDT_USER;
  }


  /**
   * Sets the value of the 'ID_LAST_UPDT_USER' field.
   * @param value the value to set.
   */
  public void setIDLASTUPDTUSER(java.lang.CharSequence value) {
    this.ID_LAST_UPDT_USER = value;
  }

  /**
   * Creates a new BtcServCmpgnDlrDtlDTO RecordBuilder.
   * @return A new BtcServCmpgnDlrDtlDTO RecordBuilder
   */
  public static com.mbusa.avro.dto.BtcServCmpgnDlrDtlDTO.Builder newBuilder() {
    return new com.mbusa.avro.dto.BtcServCmpgnDlrDtlDTO.Builder();
  }

  /**
   * Creates a new BtcServCmpgnDlrDtlDTO RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new BtcServCmpgnDlrDtlDTO RecordBuilder
   */
  public static com.mbusa.avro.dto.BtcServCmpgnDlrDtlDTO.Builder newBuilder(com.mbusa.avro.dto.BtcServCmpgnDlrDtlDTO.Builder other) {
    if (other == null) {
      return new com.mbusa.avro.dto.BtcServCmpgnDlrDtlDTO.Builder();
    } else {
      return new com.mbusa.avro.dto.BtcServCmpgnDlrDtlDTO.Builder(other);
    }
  }

  /**
   * Creates a new BtcServCmpgnDlrDtlDTO RecordBuilder by copying an existing BtcServCmpgnDlrDtlDTO instance.
   * @param other The existing instance to copy.
   * @return A new BtcServCmpgnDlrDtlDTO RecordBuilder
   */
  public static com.mbusa.avro.dto.BtcServCmpgnDlrDtlDTO.Builder newBuilder(com.mbusa.avro.dto.BtcServCmpgnDlrDtlDTO other) {
    if (other == null) {
      return new com.mbusa.avro.dto.BtcServCmpgnDlrDtlDTO.Builder();
    } else {
      return new com.mbusa.avro.dto.BtcServCmpgnDlrDtlDTO.Builder(other);
    }
  }

  /**
   * RecordBuilder for BtcServCmpgnDlrDtlDTO instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<BtcServCmpgnDlrDtlDTO>
    implements org.apache.avro.data.RecordBuilder<BtcServCmpgnDlrDtlDTO> {

    private java.lang.CharSequence CDE_CTRY;
    private java.lang.CharSequence CDE_DLR;
    private java.lang.CharSequence NUM_CMPGN;
    private java.lang.CharSequence DTE_YR;
    private java.lang.CharSequence DTE_MTH;
    private java.lang.CharSequence DTE_WK;
    private java.lang.CharSequence CNT_TOT_VEH;
    private java.lang.CharSequence CNT_TOT_RPRD_VEH;
    private java.lang.CharSequence CNT_TOT_TARG_VEH;
    private java.lang.CharSequence PCT_TRGT_RATE;
    private java.lang.CharSequence PCT_CML_RATE;
    private java.lang.CharSequence DTS_CREA;
    private java.lang.CharSequence ID_CREA_USER;
    private java.lang.CharSequence DTS_LAST_UPDT;
    private java.lang.CharSequence ID_LAST_UPDT_USER;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.mbusa.avro.dto.BtcServCmpgnDlrDtlDTO.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.CDE_CTRY)) {
        this.CDE_CTRY = data().deepCopy(fields()[0].schema(), other.CDE_CTRY);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.CDE_DLR)) {
        this.CDE_DLR = data().deepCopy(fields()[1].schema(), other.CDE_DLR);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.NUM_CMPGN)) {
        this.NUM_CMPGN = data().deepCopy(fields()[2].schema(), other.NUM_CMPGN);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.DTE_YR)) {
        this.DTE_YR = data().deepCopy(fields()[3].schema(), other.DTE_YR);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.DTE_MTH)) {
        this.DTE_MTH = data().deepCopy(fields()[4].schema(), other.DTE_MTH);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.DTE_WK)) {
        this.DTE_WK = data().deepCopy(fields()[5].schema(), other.DTE_WK);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.CNT_TOT_VEH)) {
        this.CNT_TOT_VEH = data().deepCopy(fields()[6].schema(), other.CNT_TOT_VEH);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
      if (isValidValue(fields()[7], other.CNT_TOT_RPRD_VEH)) {
        this.CNT_TOT_RPRD_VEH = data().deepCopy(fields()[7].schema(), other.CNT_TOT_RPRD_VEH);
        fieldSetFlags()[7] = other.fieldSetFlags()[7];
      }
      if (isValidValue(fields()[8], other.CNT_TOT_TARG_VEH)) {
        this.CNT_TOT_TARG_VEH = data().deepCopy(fields()[8].schema(), other.CNT_TOT_TARG_VEH);
        fieldSetFlags()[8] = other.fieldSetFlags()[8];
      }
      if (isValidValue(fields()[9], other.PCT_TRGT_RATE)) {
        this.PCT_TRGT_RATE = data().deepCopy(fields()[9].schema(), other.PCT_TRGT_RATE);
        fieldSetFlags()[9] = other.fieldSetFlags()[9];
      }
      if (isValidValue(fields()[10], other.PCT_CML_RATE)) {
        this.PCT_CML_RATE = data().deepCopy(fields()[10].schema(), other.PCT_CML_RATE);
        fieldSetFlags()[10] = other.fieldSetFlags()[10];
      }
      if (isValidValue(fields()[11], other.DTS_CREA)) {
        this.DTS_CREA = data().deepCopy(fields()[11].schema(), other.DTS_CREA);
        fieldSetFlags()[11] = other.fieldSetFlags()[11];
      }
      if (isValidValue(fields()[12], other.ID_CREA_USER)) {
        this.ID_CREA_USER = data().deepCopy(fields()[12].schema(), other.ID_CREA_USER);
        fieldSetFlags()[12] = other.fieldSetFlags()[12];
      }
      if (isValidValue(fields()[13], other.DTS_LAST_UPDT)) {
        this.DTS_LAST_UPDT = data().deepCopy(fields()[13].schema(), other.DTS_LAST_UPDT);
        fieldSetFlags()[13] = other.fieldSetFlags()[13];
      }
      if (isValidValue(fields()[14], other.ID_LAST_UPDT_USER)) {
        this.ID_LAST_UPDT_USER = data().deepCopy(fields()[14].schema(), other.ID_LAST_UPDT_USER);
        fieldSetFlags()[14] = other.fieldSetFlags()[14];
      }
    }

    /**
     * Creates a Builder by copying an existing BtcServCmpgnDlrDtlDTO instance
     * @param other The existing instance to copy.
     */
    private Builder(com.mbusa.avro.dto.BtcServCmpgnDlrDtlDTO other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.CDE_CTRY)) {
        this.CDE_CTRY = data().deepCopy(fields()[0].schema(), other.CDE_CTRY);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.CDE_DLR)) {
        this.CDE_DLR = data().deepCopy(fields()[1].schema(), other.CDE_DLR);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.NUM_CMPGN)) {
        this.NUM_CMPGN = data().deepCopy(fields()[2].schema(), other.NUM_CMPGN);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.DTE_YR)) {
        this.DTE_YR = data().deepCopy(fields()[3].schema(), other.DTE_YR);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.DTE_MTH)) {
        this.DTE_MTH = data().deepCopy(fields()[4].schema(), other.DTE_MTH);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.DTE_WK)) {
        this.DTE_WK = data().deepCopy(fields()[5].schema(), other.DTE_WK);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.CNT_TOT_VEH)) {
        this.CNT_TOT_VEH = data().deepCopy(fields()[6].schema(), other.CNT_TOT_VEH);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.CNT_TOT_RPRD_VEH)) {
        this.CNT_TOT_RPRD_VEH = data().deepCopy(fields()[7].schema(), other.CNT_TOT_RPRD_VEH);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.CNT_TOT_TARG_VEH)) {
        this.CNT_TOT_TARG_VEH = data().deepCopy(fields()[8].schema(), other.CNT_TOT_TARG_VEH);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.PCT_TRGT_RATE)) {
        this.PCT_TRGT_RATE = data().deepCopy(fields()[9].schema(), other.PCT_TRGT_RATE);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.PCT_CML_RATE)) {
        this.PCT_CML_RATE = data().deepCopy(fields()[10].schema(), other.PCT_CML_RATE);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.DTS_CREA)) {
        this.DTS_CREA = data().deepCopy(fields()[11].schema(), other.DTS_CREA);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.ID_CREA_USER)) {
        this.ID_CREA_USER = data().deepCopy(fields()[12].schema(), other.ID_CREA_USER);
        fieldSetFlags()[12] = true;
      }
      if (isValidValue(fields()[13], other.DTS_LAST_UPDT)) {
        this.DTS_LAST_UPDT = data().deepCopy(fields()[13].schema(), other.DTS_LAST_UPDT);
        fieldSetFlags()[13] = true;
      }
      if (isValidValue(fields()[14], other.ID_LAST_UPDT_USER)) {
        this.ID_LAST_UPDT_USER = data().deepCopy(fields()[14].schema(), other.ID_LAST_UPDT_USER);
        fieldSetFlags()[14] = true;
      }
    }

    /**
      * Gets the value of the 'CDE_CTRY' field.
      * @return The value.
      */
    public java.lang.CharSequence getCDECTRY() {
      return CDE_CTRY;
    }


    /**
      * Sets the value of the 'CDE_CTRY' field.
      * @param value The value of 'CDE_CTRY'.
      * @return This builder.
      */
    public com.mbusa.avro.dto.BtcServCmpgnDlrDtlDTO.Builder setCDECTRY(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.CDE_CTRY = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'CDE_CTRY' field has been set.
      * @return True if the 'CDE_CTRY' field has been set, false otherwise.
      */
    public boolean hasCDECTRY() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'CDE_CTRY' field.
      * @return This builder.
      */
    public com.mbusa.avro.dto.BtcServCmpgnDlrDtlDTO.Builder clearCDECTRY() {
      CDE_CTRY = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'CDE_DLR' field.
      * @return The value.
      */
    public java.lang.CharSequence getCDEDLR() {
      return CDE_DLR;
    }


    /**
      * Sets the value of the 'CDE_DLR' field.
      * @param value The value of 'CDE_DLR'.
      * @return This builder.
      */
    public com.mbusa.avro.dto.BtcServCmpgnDlrDtlDTO.Builder setCDEDLR(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.CDE_DLR = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'CDE_DLR' field has been set.
      * @return True if the 'CDE_DLR' field has been set, false otherwise.
      */
    public boolean hasCDEDLR() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'CDE_DLR' field.
      * @return This builder.
      */
    public com.mbusa.avro.dto.BtcServCmpgnDlrDtlDTO.Builder clearCDEDLR() {
      CDE_DLR = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'NUM_CMPGN' field.
      * @return The value.
      */
    public java.lang.CharSequence getNUMCMPGN() {
      return NUM_CMPGN;
    }


    /**
      * Sets the value of the 'NUM_CMPGN' field.
      * @param value The value of 'NUM_CMPGN'.
      * @return This builder.
      */
    public com.mbusa.avro.dto.BtcServCmpgnDlrDtlDTO.Builder setNUMCMPGN(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.NUM_CMPGN = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'NUM_CMPGN' field has been set.
      * @return True if the 'NUM_CMPGN' field has been set, false otherwise.
      */
    public boolean hasNUMCMPGN() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'NUM_CMPGN' field.
      * @return This builder.
      */
    public com.mbusa.avro.dto.BtcServCmpgnDlrDtlDTO.Builder clearNUMCMPGN() {
      NUM_CMPGN = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'DTE_YR' field.
      * @return The value.
      */
    public java.lang.CharSequence getDTEYR() {
      return DTE_YR;
    }


    /**
      * Sets the value of the 'DTE_YR' field.
      * @param value The value of 'DTE_YR'.
      * @return This builder.
      */
    public com.mbusa.avro.dto.BtcServCmpgnDlrDtlDTO.Builder setDTEYR(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.DTE_YR = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'DTE_YR' field has been set.
      * @return True if the 'DTE_YR' field has been set, false otherwise.
      */
    public boolean hasDTEYR() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'DTE_YR' field.
      * @return This builder.
      */
    public com.mbusa.avro.dto.BtcServCmpgnDlrDtlDTO.Builder clearDTEYR() {
      DTE_YR = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'DTE_MTH' field.
      * @return The value.
      */
    public java.lang.CharSequence getDTEMTH() {
      return DTE_MTH;
    }


    /**
      * Sets the value of the 'DTE_MTH' field.
      * @param value The value of 'DTE_MTH'.
      * @return This builder.
      */
    public com.mbusa.avro.dto.BtcServCmpgnDlrDtlDTO.Builder setDTEMTH(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.DTE_MTH = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'DTE_MTH' field has been set.
      * @return True if the 'DTE_MTH' field has been set, false otherwise.
      */
    public boolean hasDTEMTH() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'DTE_MTH' field.
      * @return This builder.
      */
    public com.mbusa.avro.dto.BtcServCmpgnDlrDtlDTO.Builder clearDTEMTH() {
      DTE_MTH = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'DTE_WK' field.
      * @return The value.
      */
    public java.lang.CharSequence getDTEWK() {
      return DTE_WK;
    }


    /**
      * Sets the value of the 'DTE_WK' field.
      * @param value The value of 'DTE_WK'.
      * @return This builder.
      */
    public com.mbusa.avro.dto.BtcServCmpgnDlrDtlDTO.Builder setDTEWK(java.lang.CharSequence value) {
      validate(fields()[5], value);
      this.DTE_WK = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'DTE_WK' field has been set.
      * @return True if the 'DTE_WK' field has been set, false otherwise.
      */
    public boolean hasDTEWK() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'DTE_WK' field.
      * @return This builder.
      */
    public com.mbusa.avro.dto.BtcServCmpgnDlrDtlDTO.Builder clearDTEWK() {
      DTE_WK = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'CNT_TOT_VEH' field.
      * @return The value.
      */
    public java.lang.CharSequence getCNTTOTVEH() {
      return CNT_TOT_VEH;
    }


    /**
      * Sets the value of the 'CNT_TOT_VEH' field.
      * @param value The value of 'CNT_TOT_VEH'.
      * @return This builder.
      */
    public com.mbusa.avro.dto.BtcServCmpgnDlrDtlDTO.Builder setCNTTOTVEH(java.lang.CharSequence value) {
      validate(fields()[6], value);
      this.CNT_TOT_VEH = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'CNT_TOT_VEH' field has been set.
      * @return True if the 'CNT_TOT_VEH' field has been set, false otherwise.
      */
    public boolean hasCNTTOTVEH() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'CNT_TOT_VEH' field.
      * @return This builder.
      */
    public com.mbusa.avro.dto.BtcServCmpgnDlrDtlDTO.Builder clearCNTTOTVEH() {
      CNT_TOT_VEH = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'CNT_TOT_RPRD_VEH' field.
      * @return The value.
      */
    public java.lang.CharSequence getCNTTOTRPRDVEH() {
      return CNT_TOT_RPRD_VEH;
    }


    /**
      * Sets the value of the 'CNT_TOT_RPRD_VEH' field.
      * @param value The value of 'CNT_TOT_RPRD_VEH'.
      * @return This builder.
      */
    public com.mbusa.avro.dto.BtcServCmpgnDlrDtlDTO.Builder setCNTTOTRPRDVEH(java.lang.CharSequence value) {
      validate(fields()[7], value);
      this.CNT_TOT_RPRD_VEH = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'CNT_TOT_RPRD_VEH' field has been set.
      * @return True if the 'CNT_TOT_RPRD_VEH' field has been set, false otherwise.
      */
    public boolean hasCNTTOTRPRDVEH() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'CNT_TOT_RPRD_VEH' field.
      * @return This builder.
      */
    public com.mbusa.avro.dto.BtcServCmpgnDlrDtlDTO.Builder clearCNTTOTRPRDVEH() {
      CNT_TOT_RPRD_VEH = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    /**
      * Gets the value of the 'CNT_TOT_TARG_VEH' field.
      * @return The value.
      */
    public java.lang.CharSequence getCNTTOTTARGVEH() {
      return CNT_TOT_TARG_VEH;
    }


    /**
      * Sets the value of the 'CNT_TOT_TARG_VEH' field.
      * @param value The value of 'CNT_TOT_TARG_VEH'.
      * @return This builder.
      */
    public com.mbusa.avro.dto.BtcServCmpgnDlrDtlDTO.Builder setCNTTOTTARGVEH(java.lang.CharSequence value) {
      validate(fields()[8], value);
      this.CNT_TOT_TARG_VEH = value;
      fieldSetFlags()[8] = true;
      return this;
    }

    /**
      * Checks whether the 'CNT_TOT_TARG_VEH' field has been set.
      * @return True if the 'CNT_TOT_TARG_VEH' field has been set, false otherwise.
      */
    public boolean hasCNTTOTTARGVEH() {
      return fieldSetFlags()[8];
    }


    /**
      * Clears the value of the 'CNT_TOT_TARG_VEH' field.
      * @return This builder.
      */
    public com.mbusa.avro.dto.BtcServCmpgnDlrDtlDTO.Builder clearCNTTOTTARGVEH() {
      CNT_TOT_TARG_VEH = null;
      fieldSetFlags()[8] = false;
      return this;
    }

    /**
      * Gets the value of the 'PCT_TRGT_RATE' field.
      * @return The value.
      */
    public java.lang.CharSequence getPCTTRGTRATE() {
      return PCT_TRGT_RATE;
    }


    /**
      * Sets the value of the 'PCT_TRGT_RATE' field.
      * @param value The value of 'PCT_TRGT_RATE'.
      * @return This builder.
      */
    public com.mbusa.avro.dto.BtcServCmpgnDlrDtlDTO.Builder setPCTTRGTRATE(java.lang.CharSequence value) {
      validate(fields()[9], value);
      this.PCT_TRGT_RATE = value;
      fieldSetFlags()[9] = true;
      return this;
    }

    /**
      * Checks whether the 'PCT_TRGT_RATE' field has been set.
      * @return True if the 'PCT_TRGT_RATE' field has been set, false otherwise.
      */
    public boolean hasPCTTRGTRATE() {
      return fieldSetFlags()[9];
    }


    /**
      * Clears the value of the 'PCT_TRGT_RATE' field.
      * @return This builder.
      */
    public com.mbusa.avro.dto.BtcServCmpgnDlrDtlDTO.Builder clearPCTTRGTRATE() {
      PCT_TRGT_RATE = null;
      fieldSetFlags()[9] = false;
      return this;
    }

    /**
      * Gets the value of the 'PCT_CML_RATE' field.
      * @return The value.
      */
    public java.lang.CharSequence getPCTCMLRATE() {
      return PCT_CML_RATE;
    }


    /**
      * Sets the value of the 'PCT_CML_RATE' field.
      * @param value The value of 'PCT_CML_RATE'.
      * @return This builder.
      */
    public com.mbusa.avro.dto.BtcServCmpgnDlrDtlDTO.Builder setPCTCMLRATE(java.lang.CharSequence value) {
      validate(fields()[10], value);
      this.PCT_CML_RATE = value;
      fieldSetFlags()[10] = true;
      return this;
    }

    /**
      * Checks whether the 'PCT_CML_RATE' field has been set.
      * @return True if the 'PCT_CML_RATE' field has been set, false otherwise.
      */
    public boolean hasPCTCMLRATE() {
      return fieldSetFlags()[10];
    }


    /**
      * Clears the value of the 'PCT_CML_RATE' field.
      * @return This builder.
      */
    public com.mbusa.avro.dto.BtcServCmpgnDlrDtlDTO.Builder clearPCTCMLRATE() {
      PCT_CML_RATE = null;
      fieldSetFlags()[10] = false;
      return this;
    }

    /**
      * Gets the value of the 'DTS_CREA' field.
      * @return The value.
      */
    public java.lang.CharSequence getDTSCREA() {
      return DTS_CREA;
    }


    /**
      * Sets the value of the 'DTS_CREA' field.
      * @param value The value of 'DTS_CREA'.
      * @return This builder.
      */
    public com.mbusa.avro.dto.BtcServCmpgnDlrDtlDTO.Builder setDTSCREA(java.lang.CharSequence value) {
      validate(fields()[11], value);
      this.DTS_CREA = value;
      fieldSetFlags()[11] = true;
      return this;
    }

    /**
      * Checks whether the 'DTS_CREA' field has been set.
      * @return True if the 'DTS_CREA' field has been set, false otherwise.
      */
    public boolean hasDTSCREA() {
      return fieldSetFlags()[11];
    }


    /**
      * Clears the value of the 'DTS_CREA' field.
      * @return This builder.
      */
    public com.mbusa.avro.dto.BtcServCmpgnDlrDtlDTO.Builder clearDTSCREA() {
      DTS_CREA = null;
      fieldSetFlags()[11] = false;
      return this;
    }

    /**
      * Gets the value of the 'ID_CREA_USER' field.
      * @return The value.
      */
    public java.lang.CharSequence getIDCREAUSER() {
      return ID_CREA_USER;
    }


    /**
      * Sets the value of the 'ID_CREA_USER' field.
      * @param value The value of 'ID_CREA_USER'.
      * @return This builder.
      */
    public com.mbusa.avro.dto.BtcServCmpgnDlrDtlDTO.Builder setIDCREAUSER(java.lang.CharSequence value) {
      validate(fields()[12], value);
      this.ID_CREA_USER = value;
      fieldSetFlags()[12] = true;
      return this;
    }

    /**
      * Checks whether the 'ID_CREA_USER' field has been set.
      * @return True if the 'ID_CREA_USER' field has been set, false otherwise.
      */
    public boolean hasIDCREAUSER() {
      return fieldSetFlags()[12];
    }


    /**
      * Clears the value of the 'ID_CREA_USER' field.
      * @return This builder.
      */
    public com.mbusa.avro.dto.BtcServCmpgnDlrDtlDTO.Builder clearIDCREAUSER() {
      ID_CREA_USER = null;
      fieldSetFlags()[12] = false;
      return this;
    }

    /**
      * Gets the value of the 'DTS_LAST_UPDT' field.
      * @return The value.
      */
    public java.lang.CharSequence getDTSLASTUPDT() {
      return DTS_LAST_UPDT;
    }


    /**
      * Sets the value of the 'DTS_LAST_UPDT' field.
      * @param value The value of 'DTS_LAST_UPDT'.
      * @return This builder.
      */
    public com.mbusa.avro.dto.BtcServCmpgnDlrDtlDTO.Builder setDTSLASTUPDT(java.lang.CharSequence value) {
      validate(fields()[13], value);
      this.DTS_LAST_UPDT = value;
      fieldSetFlags()[13] = true;
      return this;
    }

    /**
      * Checks whether the 'DTS_LAST_UPDT' field has been set.
      * @return True if the 'DTS_LAST_UPDT' field has been set, false otherwise.
      */
    public boolean hasDTSLASTUPDT() {
      return fieldSetFlags()[13];
    }


    /**
      * Clears the value of the 'DTS_LAST_UPDT' field.
      * @return This builder.
      */
    public com.mbusa.avro.dto.BtcServCmpgnDlrDtlDTO.Builder clearDTSLASTUPDT() {
      DTS_LAST_UPDT = null;
      fieldSetFlags()[13] = false;
      return this;
    }

    /**
      * Gets the value of the 'ID_LAST_UPDT_USER' field.
      * @return The value.
      */
    public java.lang.CharSequence getIDLASTUPDTUSER() {
      return ID_LAST_UPDT_USER;
    }


    /**
      * Sets the value of the 'ID_LAST_UPDT_USER' field.
      * @param value The value of 'ID_LAST_UPDT_USER'.
      * @return This builder.
      */
    public com.mbusa.avro.dto.BtcServCmpgnDlrDtlDTO.Builder setIDLASTUPDTUSER(java.lang.CharSequence value) {
      validate(fields()[14], value);
      this.ID_LAST_UPDT_USER = value;
      fieldSetFlags()[14] = true;
      return this;
    }

    /**
      * Checks whether the 'ID_LAST_UPDT_USER' field has been set.
      * @return True if the 'ID_LAST_UPDT_USER' field has been set, false otherwise.
      */
    public boolean hasIDLASTUPDTUSER() {
      return fieldSetFlags()[14];
    }


    /**
      * Clears the value of the 'ID_LAST_UPDT_USER' field.
      * @return This builder.
      */
    public com.mbusa.avro.dto.BtcServCmpgnDlrDtlDTO.Builder clearIDLASTUPDTUSER() {
      ID_LAST_UPDT_USER = null;
      fieldSetFlags()[14] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public BtcServCmpgnDlrDtlDTO build() {
      try {
        BtcServCmpgnDlrDtlDTO record = new BtcServCmpgnDlrDtlDTO();
        record.CDE_CTRY = fieldSetFlags()[0] ? this.CDE_CTRY : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.CDE_DLR = fieldSetFlags()[1] ? this.CDE_DLR : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.NUM_CMPGN = fieldSetFlags()[2] ? this.NUM_CMPGN : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.DTE_YR = fieldSetFlags()[3] ? this.DTE_YR : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.DTE_MTH = fieldSetFlags()[4] ? this.DTE_MTH : (java.lang.CharSequence) defaultValue(fields()[4]);
        record.DTE_WK = fieldSetFlags()[5] ? this.DTE_WK : (java.lang.CharSequence) defaultValue(fields()[5]);
        record.CNT_TOT_VEH = fieldSetFlags()[6] ? this.CNT_TOT_VEH : (java.lang.CharSequence) defaultValue(fields()[6]);
        record.CNT_TOT_RPRD_VEH = fieldSetFlags()[7] ? this.CNT_TOT_RPRD_VEH : (java.lang.CharSequence) defaultValue(fields()[7]);
        record.CNT_TOT_TARG_VEH = fieldSetFlags()[8] ? this.CNT_TOT_TARG_VEH : (java.lang.CharSequence) defaultValue(fields()[8]);
        record.PCT_TRGT_RATE = fieldSetFlags()[9] ? this.PCT_TRGT_RATE : (java.lang.CharSequence) defaultValue(fields()[9]);
        record.PCT_CML_RATE = fieldSetFlags()[10] ? this.PCT_CML_RATE : (java.lang.CharSequence) defaultValue(fields()[10]);
        record.DTS_CREA = fieldSetFlags()[11] ? this.DTS_CREA : (java.lang.CharSequence) defaultValue(fields()[11]);
        record.ID_CREA_USER = fieldSetFlags()[12] ? this.ID_CREA_USER : (java.lang.CharSequence) defaultValue(fields()[12]);
        record.DTS_LAST_UPDT = fieldSetFlags()[13] ? this.DTS_LAST_UPDT : (java.lang.CharSequence) defaultValue(fields()[13]);
        record.ID_LAST_UPDT_USER = fieldSetFlags()[14] ? this.ID_LAST_UPDT_USER : (java.lang.CharSequence) defaultValue(fields()[14]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<BtcServCmpgnDlrDtlDTO>
    WRITER$ = (org.apache.avro.io.DatumWriter<BtcServCmpgnDlrDtlDTO>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<BtcServCmpgnDlrDtlDTO>
    READER$ = (org.apache.avro.io.DatumReader<BtcServCmpgnDlrDtlDTO>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.CDE_CTRY);

    out.writeString(this.CDE_DLR);

    out.writeString(this.NUM_CMPGN);

    out.writeString(this.DTE_YR);

    out.writeString(this.DTE_MTH);

    out.writeString(this.DTE_WK);

    out.writeString(this.CNT_TOT_VEH);

    out.writeString(this.CNT_TOT_RPRD_VEH);

    out.writeString(this.CNT_TOT_TARG_VEH);

    out.writeString(this.PCT_TRGT_RATE);

    out.writeString(this.PCT_CML_RATE);

    out.writeString(this.DTS_CREA);

    out.writeString(this.ID_CREA_USER);

    out.writeString(this.DTS_LAST_UPDT);

    out.writeString(this.ID_LAST_UPDT_USER);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.CDE_CTRY = in.readString(this.CDE_CTRY instanceof Utf8 ? (Utf8)this.CDE_CTRY : null);

      this.CDE_DLR = in.readString(this.CDE_DLR instanceof Utf8 ? (Utf8)this.CDE_DLR : null);

      this.NUM_CMPGN = in.readString(this.NUM_CMPGN instanceof Utf8 ? (Utf8)this.NUM_CMPGN : null);

      this.DTE_YR = in.readString(this.DTE_YR instanceof Utf8 ? (Utf8)this.DTE_YR : null);

      this.DTE_MTH = in.readString(this.DTE_MTH instanceof Utf8 ? (Utf8)this.DTE_MTH : null);

      this.DTE_WK = in.readString(this.DTE_WK instanceof Utf8 ? (Utf8)this.DTE_WK : null);

      this.CNT_TOT_VEH = in.readString(this.CNT_TOT_VEH instanceof Utf8 ? (Utf8)this.CNT_TOT_VEH : null);

      this.CNT_TOT_RPRD_VEH = in.readString(this.CNT_TOT_RPRD_VEH instanceof Utf8 ? (Utf8)this.CNT_TOT_RPRD_VEH : null);

      this.CNT_TOT_TARG_VEH = in.readString(this.CNT_TOT_TARG_VEH instanceof Utf8 ? (Utf8)this.CNT_TOT_TARG_VEH : null);

      this.PCT_TRGT_RATE = in.readString(this.PCT_TRGT_RATE instanceof Utf8 ? (Utf8)this.PCT_TRGT_RATE : null);

      this.PCT_CML_RATE = in.readString(this.PCT_CML_RATE instanceof Utf8 ? (Utf8)this.PCT_CML_RATE : null);

      this.DTS_CREA = in.readString(this.DTS_CREA instanceof Utf8 ? (Utf8)this.DTS_CREA : null);

      this.ID_CREA_USER = in.readString(this.ID_CREA_USER instanceof Utf8 ? (Utf8)this.ID_CREA_USER : null);

      this.DTS_LAST_UPDT = in.readString(this.DTS_LAST_UPDT instanceof Utf8 ? (Utf8)this.DTS_LAST_UPDT : null);

      this.ID_LAST_UPDT_USER = in.readString(this.ID_LAST_UPDT_USER instanceof Utf8 ? (Utf8)this.ID_LAST_UPDT_USER : null);

    } else {
      for (int i = 0; i < 15; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.CDE_CTRY = in.readString(this.CDE_CTRY instanceof Utf8 ? (Utf8)this.CDE_CTRY : null);
          break;

        case 1:
          this.CDE_DLR = in.readString(this.CDE_DLR instanceof Utf8 ? (Utf8)this.CDE_DLR : null);
          break;

        case 2:
          this.NUM_CMPGN = in.readString(this.NUM_CMPGN instanceof Utf8 ? (Utf8)this.NUM_CMPGN : null);
          break;

        case 3:
          this.DTE_YR = in.readString(this.DTE_YR instanceof Utf8 ? (Utf8)this.DTE_YR : null);
          break;

        case 4:
          this.DTE_MTH = in.readString(this.DTE_MTH instanceof Utf8 ? (Utf8)this.DTE_MTH : null);
          break;

        case 5:
          this.DTE_WK = in.readString(this.DTE_WK instanceof Utf8 ? (Utf8)this.DTE_WK : null);
          break;

        case 6:
          this.CNT_TOT_VEH = in.readString(this.CNT_TOT_VEH instanceof Utf8 ? (Utf8)this.CNT_TOT_VEH : null);
          break;

        case 7:
          this.CNT_TOT_RPRD_VEH = in.readString(this.CNT_TOT_RPRD_VEH instanceof Utf8 ? (Utf8)this.CNT_TOT_RPRD_VEH : null);
          break;

        case 8:
          this.CNT_TOT_TARG_VEH = in.readString(this.CNT_TOT_TARG_VEH instanceof Utf8 ? (Utf8)this.CNT_TOT_TARG_VEH : null);
          break;

        case 9:
          this.PCT_TRGT_RATE = in.readString(this.PCT_TRGT_RATE instanceof Utf8 ? (Utf8)this.PCT_TRGT_RATE : null);
          break;

        case 10:
          this.PCT_CML_RATE = in.readString(this.PCT_CML_RATE instanceof Utf8 ? (Utf8)this.PCT_CML_RATE : null);
          break;

        case 11:
          this.DTS_CREA = in.readString(this.DTS_CREA instanceof Utf8 ? (Utf8)this.DTS_CREA : null);
          break;

        case 12:
          this.ID_CREA_USER = in.readString(this.ID_CREA_USER instanceof Utf8 ? (Utf8)this.ID_CREA_USER : null);
          break;

        case 13:
          this.DTS_LAST_UPDT = in.readString(this.DTS_LAST_UPDT instanceof Utf8 ? (Utf8)this.DTS_LAST_UPDT : null);
          break;

        case 14:
          this.ID_LAST_UPDT_USER = in.readString(this.ID_LAST_UPDT_USER instanceof Utf8 ? (Utf8)this.ID_LAST_UPDT_USER : null);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










