/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.mbusa.avro.dto;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class CmpgnCustDTO extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 9093065729290144019L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"CmpgnCustDTO\",\"namespace\":\"com.mbusa.avro.dto\",\"fields\":[{\"name\":\"ID_CUST\",\"type\":\"string\"},{\"name\":\"NAM_LAST\",\"type\":\"string\"},{\"name\":\"NAM_FIR\",\"type\":\"string\"},{\"name\":\"NAM_MID_INIT\",\"type\":\"string\"},{\"name\":\"NAM_PFX\",\"type\":\"string\"},{\"name\":\"NAM_SFX\",\"type\":\"string\"},{\"name\":\"ADR_LN_1\",\"type\":\"string\"},{\"name\":\"ADR_LN_2\",\"type\":\"string\"},{\"name\":\"ADR_LN_3\",\"type\":\"string\"},{\"name\":\"NAM_CITY\",\"type\":\"string\"},{\"name\":\"CDE_ST\",\"type\":\"string\"},{\"name\":\"CDE_ZIP\",\"type\":\"string\"},{\"name\":\"DTE_EFF\",\"type\":\"string\"},{\"name\":\"ADR_EML\",\"type\":\"string\"},{\"name\":\"NUM_TEL\",\"type\":\"string\"},{\"name\":\"CDE_CUST_CTRY\",\"type\":\"string\"},{\"name\":\"DTE_SRC_RCD_UPDT\",\"type\":\"string\"},{\"name\":\"TME_SRC_RCD_UPDT\",\"type\":\"string\"},{\"name\":\"ID_SRC_RCD_UPDT_USER\",\"type\":\"string\"},{\"name\":\"DTS_CREA\",\"type\":\"string\"},{\"name\":\"ID_CREA_USER\",\"type\":\"string\"},{\"name\":\"DTS_LAST_UPDT\",\"type\":\"string\"},{\"name\":\"ID_LAST_UPDT_USER\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<CmpgnCustDTO> ENCODER =
      new BinaryMessageEncoder<CmpgnCustDTO>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<CmpgnCustDTO> DECODER =
      new BinaryMessageDecoder<CmpgnCustDTO>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<CmpgnCustDTO> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<CmpgnCustDTO> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<CmpgnCustDTO> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<CmpgnCustDTO>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this CmpgnCustDTO to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a CmpgnCustDTO from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a CmpgnCustDTO instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static CmpgnCustDTO fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private java.lang.CharSequence ID_CUST;
   private java.lang.CharSequence NAM_LAST;
   private java.lang.CharSequence NAM_FIR;
   private java.lang.CharSequence NAM_MID_INIT;
   private java.lang.CharSequence NAM_PFX;
   private java.lang.CharSequence NAM_SFX;
   private java.lang.CharSequence ADR_LN_1;
   private java.lang.CharSequence ADR_LN_2;
   private java.lang.CharSequence ADR_LN_3;
   private java.lang.CharSequence NAM_CITY;
   private java.lang.CharSequence CDE_ST;
   private java.lang.CharSequence CDE_ZIP;
   private java.lang.CharSequence DTE_EFF;
   private java.lang.CharSequence ADR_EML;
   private java.lang.CharSequence NUM_TEL;
   private java.lang.CharSequence CDE_CUST_CTRY;
   private java.lang.CharSequence DTE_SRC_RCD_UPDT;
   private java.lang.CharSequence TME_SRC_RCD_UPDT;
   private java.lang.CharSequence ID_SRC_RCD_UPDT_USER;
   private java.lang.CharSequence DTS_CREA;
   private java.lang.CharSequence ID_CREA_USER;
   private java.lang.CharSequence DTS_LAST_UPDT;
   private java.lang.CharSequence ID_LAST_UPDT_USER;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public CmpgnCustDTO() {}

  /**
   * All-args constructor.
   * @param ID_CUST The new value for ID_CUST
   * @param NAM_LAST The new value for NAM_LAST
   * @param NAM_FIR The new value for NAM_FIR
   * @param NAM_MID_INIT The new value for NAM_MID_INIT
   * @param NAM_PFX The new value for NAM_PFX
   * @param NAM_SFX The new value for NAM_SFX
   * @param ADR_LN_1 The new value for ADR_LN_1
   * @param ADR_LN_2 The new value for ADR_LN_2
   * @param ADR_LN_3 The new value for ADR_LN_3
   * @param NAM_CITY The new value for NAM_CITY
   * @param CDE_ST The new value for CDE_ST
   * @param CDE_ZIP The new value for CDE_ZIP
   * @param DTE_EFF The new value for DTE_EFF
   * @param ADR_EML The new value for ADR_EML
   * @param NUM_TEL The new value for NUM_TEL
   * @param CDE_CUST_CTRY The new value for CDE_CUST_CTRY
   * @param DTE_SRC_RCD_UPDT The new value for DTE_SRC_RCD_UPDT
   * @param TME_SRC_RCD_UPDT The new value for TME_SRC_RCD_UPDT
   * @param ID_SRC_RCD_UPDT_USER The new value for ID_SRC_RCD_UPDT_USER
   * @param DTS_CREA The new value for DTS_CREA
   * @param ID_CREA_USER The new value for ID_CREA_USER
   * @param DTS_LAST_UPDT The new value for DTS_LAST_UPDT
   * @param ID_LAST_UPDT_USER The new value for ID_LAST_UPDT_USER
   */
  public CmpgnCustDTO(java.lang.CharSequence ID_CUST, java.lang.CharSequence NAM_LAST, java.lang.CharSequence NAM_FIR, java.lang.CharSequence NAM_MID_INIT, java.lang.CharSequence NAM_PFX, java.lang.CharSequence NAM_SFX, java.lang.CharSequence ADR_LN_1, java.lang.CharSequence ADR_LN_2, java.lang.CharSequence ADR_LN_3, java.lang.CharSequence NAM_CITY, java.lang.CharSequence CDE_ST, java.lang.CharSequence CDE_ZIP, java.lang.CharSequence DTE_EFF, java.lang.CharSequence ADR_EML, java.lang.CharSequence NUM_TEL, java.lang.CharSequence CDE_CUST_CTRY, java.lang.CharSequence DTE_SRC_RCD_UPDT, java.lang.CharSequence TME_SRC_RCD_UPDT, java.lang.CharSequence ID_SRC_RCD_UPDT_USER, java.lang.CharSequence DTS_CREA, java.lang.CharSequence ID_CREA_USER, java.lang.CharSequence DTS_LAST_UPDT, java.lang.CharSequence ID_LAST_UPDT_USER) {
    this.ID_CUST = ID_CUST;
    this.NAM_LAST = NAM_LAST;
    this.NAM_FIR = NAM_FIR;
    this.NAM_MID_INIT = NAM_MID_INIT;
    this.NAM_PFX = NAM_PFX;
    this.NAM_SFX = NAM_SFX;
    this.ADR_LN_1 = ADR_LN_1;
    this.ADR_LN_2 = ADR_LN_2;
    this.ADR_LN_3 = ADR_LN_3;
    this.NAM_CITY = NAM_CITY;
    this.CDE_ST = CDE_ST;
    this.CDE_ZIP = CDE_ZIP;
    this.DTE_EFF = DTE_EFF;
    this.ADR_EML = ADR_EML;
    this.NUM_TEL = NUM_TEL;
    this.CDE_CUST_CTRY = CDE_CUST_CTRY;
    this.DTE_SRC_RCD_UPDT = DTE_SRC_RCD_UPDT;
    this.TME_SRC_RCD_UPDT = TME_SRC_RCD_UPDT;
    this.ID_SRC_RCD_UPDT_USER = ID_SRC_RCD_UPDT_USER;
    this.DTS_CREA = DTS_CREA;
    this.ID_CREA_USER = ID_CREA_USER;
    this.DTS_LAST_UPDT = DTS_LAST_UPDT;
    this.ID_LAST_UPDT_USER = ID_LAST_UPDT_USER;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return ID_CUST;
    case 1: return NAM_LAST;
    case 2: return NAM_FIR;
    case 3: return NAM_MID_INIT;
    case 4: return NAM_PFX;
    case 5: return NAM_SFX;
    case 6: return ADR_LN_1;
    case 7: return ADR_LN_2;
    case 8: return ADR_LN_3;
    case 9: return NAM_CITY;
    case 10: return CDE_ST;
    case 11: return CDE_ZIP;
    case 12: return DTE_EFF;
    case 13: return ADR_EML;
    case 14: return NUM_TEL;
    case 15: return CDE_CUST_CTRY;
    case 16: return DTE_SRC_RCD_UPDT;
    case 17: return TME_SRC_RCD_UPDT;
    case 18: return ID_SRC_RCD_UPDT_USER;
    case 19: return DTS_CREA;
    case 20: return ID_CREA_USER;
    case 21: return DTS_LAST_UPDT;
    case 22: return ID_LAST_UPDT_USER;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: ID_CUST = (java.lang.CharSequence)value$; break;
    case 1: NAM_LAST = (java.lang.CharSequence)value$; break;
    case 2: NAM_FIR = (java.lang.CharSequence)value$; break;
    case 3: NAM_MID_INIT = (java.lang.CharSequence)value$; break;
    case 4: NAM_PFX = (java.lang.CharSequence)value$; break;
    case 5: NAM_SFX = (java.lang.CharSequence)value$; break;
    case 6: ADR_LN_1 = (java.lang.CharSequence)value$; break;
    case 7: ADR_LN_2 = (java.lang.CharSequence)value$; break;
    case 8: ADR_LN_3 = (java.lang.CharSequence)value$; break;
    case 9: NAM_CITY = (java.lang.CharSequence)value$; break;
    case 10: CDE_ST = (java.lang.CharSequence)value$; break;
    case 11: CDE_ZIP = (java.lang.CharSequence)value$; break;
    case 12: DTE_EFF = (java.lang.CharSequence)value$; break;
    case 13: ADR_EML = (java.lang.CharSequence)value$; break;
    case 14: NUM_TEL = (java.lang.CharSequence)value$; break;
    case 15: CDE_CUST_CTRY = (java.lang.CharSequence)value$; break;
    case 16: DTE_SRC_RCD_UPDT = (java.lang.CharSequence)value$; break;
    case 17: TME_SRC_RCD_UPDT = (java.lang.CharSequence)value$; break;
    case 18: ID_SRC_RCD_UPDT_USER = (java.lang.CharSequence)value$; break;
    case 19: DTS_CREA = (java.lang.CharSequence)value$; break;
    case 20: ID_CREA_USER = (java.lang.CharSequence)value$; break;
    case 21: DTS_LAST_UPDT = (java.lang.CharSequence)value$; break;
    case 22: ID_LAST_UPDT_USER = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'ID_CUST' field.
   * @return The value of the 'ID_CUST' field.
   */
  public java.lang.CharSequence getIDCUST() {
    return ID_CUST;
  }


  /**
   * Sets the value of the 'ID_CUST' field.
   * @param value the value to set.
   */
  public void setIDCUST(java.lang.CharSequence value) {
    this.ID_CUST = value;
  }

  /**
   * Gets the value of the 'NAM_LAST' field.
   * @return The value of the 'NAM_LAST' field.
   */
  public java.lang.CharSequence getNAMLAST() {
    return NAM_LAST;
  }


  /**
   * Sets the value of the 'NAM_LAST' field.
   * @param value the value to set.
   */
  public void setNAMLAST(java.lang.CharSequence value) {
    this.NAM_LAST = value;
  }

  /**
   * Gets the value of the 'NAM_FIR' field.
   * @return The value of the 'NAM_FIR' field.
   */
  public java.lang.CharSequence getNAMFIR() {
    return NAM_FIR;
  }


  /**
   * Sets the value of the 'NAM_FIR' field.
   * @param value the value to set.
   */
  public void setNAMFIR(java.lang.CharSequence value) {
    this.NAM_FIR = value;
  }

  /**
   * Gets the value of the 'NAM_MID_INIT' field.
   * @return The value of the 'NAM_MID_INIT' field.
   */
  public java.lang.CharSequence getNAMMIDINIT() {
    return NAM_MID_INIT;
  }


  /**
   * Sets the value of the 'NAM_MID_INIT' field.
   * @param value the value to set.
   */
  public void setNAMMIDINIT(java.lang.CharSequence value) {
    this.NAM_MID_INIT = value;
  }

  /**
   * Gets the value of the 'NAM_PFX' field.
   * @return The value of the 'NAM_PFX' field.
   */
  public java.lang.CharSequence getNAMPFX() {
    return NAM_PFX;
  }


  /**
   * Sets the value of the 'NAM_PFX' field.
   * @param value the value to set.
   */
  public void setNAMPFX(java.lang.CharSequence value) {
    this.NAM_PFX = value;
  }

  /**
   * Gets the value of the 'NAM_SFX' field.
   * @return The value of the 'NAM_SFX' field.
   */
  public java.lang.CharSequence getNAMSFX() {
    return NAM_SFX;
  }


  /**
   * Sets the value of the 'NAM_SFX' field.
   * @param value the value to set.
   */
  public void setNAMSFX(java.lang.CharSequence value) {
    this.NAM_SFX = value;
  }

  /**
   * Gets the value of the 'ADR_LN_1' field.
   * @return The value of the 'ADR_LN_1' field.
   */
  public java.lang.CharSequence getADRLN1() {
    return ADR_LN_1;
  }


  /**
   * Sets the value of the 'ADR_LN_1' field.
   * @param value the value to set.
   */
  public void setADRLN1(java.lang.CharSequence value) {
    this.ADR_LN_1 = value;
  }

  /**
   * Gets the value of the 'ADR_LN_2' field.
   * @return The value of the 'ADR_LN_2' field.
   */
  public java.lang.CharSequence getADRLN2() {
    return ADR_LN_2;
  }


  /**
   * Sets the value of the 'ADR_LN_2' field.
   * @param value the value to set.
   */
  public void setADRLN2(java.lang.CharSequence value) {
    this.ADR_LN_2 = value;
  }

  /**
   * Gets the value of the 'ADR_LN_3' field.
   * @return The value of the 'ADR_LN_3' field.
   */
  public java.lang.CharSequence getADRLN3() {
    return ADR_LN_3;
  }


  /**
   * Sets the value of the 'ADR_LN_3' field.
   * @param value the value to set.
   */
  public void setADRLN3(java.lang.CharSequence value) {
    this.ADR_LN_3 = value;
  }

  /**
   * Gets the value of the 'NAM_CITY' field.
   * @return The value of the 'NAM_CITY' field.
   */
  public java.lang.CharSequence getNAMCITY() {
    return NAM_CITY;
  }


  /**
   * Sets the value of the 'NAM_CITY' field.
   * @param value the value to set.
   */
  public void setNAMCITY(java.lang.CharSequence value) {
    this.NAM_CITY = value;
  }

  /**
   * Gets the value of the 'CDE_ST' field.
   * @return The value of the 'CDE_ST' field.
   */
  public java.lang.CharSequence getCDEST() {
    return CDE_ST;
  }


  /**
   * Sets the value of the 'CDE_ST' field.
   * @param value the value to set.
   */
  public void setCDEST(java.lang.CharSequence value) {
    this.CDE_ST = value;
  }

  /**
   * Gets the value of the 'CDE_ZIP' field.
   * @return The value of the 'CDE_ZIP' field.
   */
  public java.lang.CharSequence getCDEZIP() {
    return CDE_ZIP;
  }


  /**
   * Sets the value of the 'CDE_ZIP' field.
   * @param value the value to set.
   */
  public void setCDEZIP(java.lang.CharSequence value) {
    this.CDE_ZIP = value;
  }

  /**
   * Gets the value of the 'DTE_EFF' field.
   * @return The value of the 'DTE_EFF' field.
   */
  public java.lang.CharSequence getDTEEFF() {
    return DTE_EFF;
  }


  /**
   * Sets the value of the 'DTE_EFF' field.
   * @param value the value to set.
   */
  public void setDTEEFF(java.lang.CharSequence value) {
    this.DTE_EFF = value;
  }

  /**
   * Gets the value of the 'ADR_EML' field.
   * @return The value of the 'ADR_EML' field.
   */
  public java.lang.CharSequence getADREML() {
    return ADR_EML;
  }


  /**
   * Sets the value of the 'ADR_EML' field.
   * @param value the value to set.
   */
  public void setADREML(java.lang.CharSequence value) {
    this.ADR_EML = value;
  }

  /**
   * Gets the value of the 'NUM_TEL' field.
   * @return The value of the 'NUM_TEL' field.
   */
  public java.lang.CharSequence getNUMTEL() {
    return NUM_TEL;
  }


  /**
   * Sets the value of the 'NUM_TEL' field.
   * @param value the value to set.
   */
  public void setNUMTEL(java.lang.CharSequence value) {
    this.NUM_TEL = value;
  }

  /**
   * Gets the value of the 'CDE_CUST_CTRY' field.
   * @return The value of the 'CDE_CUST_CTRY' field.
   */
  public java.lang.CharSequence getCDECUSTCTRY() {
    return CDE_CUST_CTRY;
  }


  /**
   * Sets the value of the 'CDE_CUST_CTRY' field.
   * @param value the value to set.
   */
  public void setCDECUSTCTRY(java.lang.CharSequence value) {
    this.CDE_CUST_CTRY = value;
  }

  /**
   * Gets the value of the 'DTE_SRC_RCD_UPDT' field.
   * @return The value of the 'DTE_SRC_RCD_UPDT' field.
   */
  public java.lang.CharSequence getDTESRCRCDUPDT() {
    return DTE_SRC_RCD_UPDT;
  }


  /**
   * Sets the value of the 'DTE_SRC_RCD_UPDT' field.
   * @param value the value to set.
   */
  public void setDTESRCRCDUPDT(java.lang.CharSequence value) {
    this.DTE_SRC_RCD_UPDT = value;
  }

  /**
   * Gets the value of the 'TME_SRC_RCD_UPDT' field.
   * @return The value of the 'TME_SRC_RCD_UPDT' field.
   */
  public java.lang.CharSequence getTMESRCRCDUPDT() {
    return TME_SRC_RCD_UPDT;
  }


  /**
   * Sets the value of the 'TME_SRC_RCD_UPDT' field.
   * @param value the value to set.
   */
  public void setTMESRCRCDUPDT(java.lang.CharSequence value) {
    this.TME_SRC_RCD_UPDT = value;
  }

  /**
   * Gets the value of the 'ID_SRC_RCD_UPDT_USER' field.
   * @return The value of the 'ID_SRC_RCD_UPDT_USER' field.
   */
  public java.lang.CharSequence getIDSRCRCDUPDTUSER() {
    return ID_SRC_RCD_UPDT_USER;
  }


  /**
   * Sets the value of the 'ID_SRC_RCD_UPDT_USER' field.
   * @param value the value to set.
   */
  public void setIDSRCRCDUPDTUSER(java.lang.CharSequence value) {
    this.ID_SRC_RCD_UPDT_USER = value;
  }

  /**
   * Gets the value of the 'DTS_CREA' field.
   * @return The value of the 'DTS_CREA' field.
   */
  public java.lang.CharSequence getDTSCREA() {
    return DTS_CREA;
  }


  /**
   * Sets the value of the 'DTS_CREA' field.
   * @param value the value to set.
   */
  public void setDTSCREA(java.lang.CharSequence value) {
    this.DTS_CREA = value;
  }

  /**
   * Gets the value of the 'ID_CREA_USER' field.
   * @return The value of the 'ID_CREA_USER' field.
   */
  public java.lang.CharSequence getIDCREAUSER() {
    return ID_CREA_USER;
  }


  /**
   * Sets the value of the 'ID_CREA_USER' field.
   * @param value the value to set.
   */
  public void setIDCREAUSER(java.lang.CharSequence value) {
    this.ID_CREA_USER = value;
  }

  /**
   * Gets the value of the 'DTS_LAST_UPDT' field.
   * @return The value of the 'DTS_LAST_UPDT' field.
   */
  public java.lang.CharSequence getDTSLASTUPDT() {
    return DTS_LAST_UPDT;
  }


  /**
   * Sets the value of the 'DTS_LAST_UPDT' field.
   * @param value the value to set.
   */
  public void setDTSLASTUPDT(java.lang.CharSequence value) {
    this.DTS_LAST_UPDT = value;
  }

  /**
   * Gets the value of the 'ID_LAST_UPDT_USER' field.
   * @return The value of the 'ID_LAST_UPDT_USER' field.
   */
  public java.lang.CharSequence getIDLASTUPDTUSER() {
    return ID_LAST_UPDT_USER;
  }


  /**
   * Sets the value of the 'ID_LAST_UPDT_USER' field.
   * @param value the value to set.
   */
  public void setIDLASTUPDTUSER(java.lang.CharSequence value) {
    this.ID_LAST_UPDT_USER = value;
  }

  /**
   * Creates a new CmpgnCustDTO RecordBuilder.
   * @return A new CmpgnCustDTO RecordBuilder
   */
  public static com.mbusa.avro.dto.CmpgnCustDTO.Builder newBuilder() {
    return new com.mbusa.avro.dto.CmpgnCustDTO.Builder();
  }

  /**
   * Creates a new CmpgnCustDTO RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new CmpgnCustDTO RecordBuilder
   */
  public static com.mbusa.avro.dto.CmpgnCustDTO.Builder newBuilder(com.mbusa.avro.dto.CmpgnCustDTO.Builder other) {
    if (other == null) {
      return new com.mbusa.avro.dto.CmpgnCustDTO.Builder();
    } else {
      return new com.mbusa.avro.dto.CmpgnCustDTO.Builder(other);
    }
  }

  /**
   * Creates a new CmpgnCustDTO RecordBuilder by copying an existing CmpgnCustDTO instance.
   * @param other The existing instance to copy.
   * @return A new CmpgnCustDTO RecordBuilder
   */
  public static com.mbusa.avro.dto.CmpgnCustDTO.Builder newBuilder(com.mbusa.avro.dto.CmpgnCustDTO other) {
    if (other == null) {
      return new com.mbusa.avro.dto.CmpgnCustDTO.Builder();
    } else {
      return new com.mbusa.avro.dto.CmpgnCustDTO.Builder(other);
    }
  }

  /**
   * RecordBuilder for CmpgnCustDTO instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<CmpgnCustDTO>
    implements org.apache.avro.data.RecordBuilder<CmpgnCustDTO> {

    private java.lang.CharSequence ID_CUST;
    private java.lang.CharSequence NAM_LAST;
    private java.lang.CharSequence NAM_FIR;
    private java.lang.CharSequence NAM_MID_INIT;
    private java.lang.CharSequence NAM_PFX;
    private java.lang.CharSequence NAM_SFX;
    private java.lang.CharSequence ADR_LN_1;
    private java.lang.CharSequence ADR_LN_2;
    private java.lang.CharSequence ADR_LN_3;
    private java.lang.CharSequence NAM_CITY;
    private java.lang.CharSequence CDE_ST;
    private java.lang.CharSequence CDE_ZIP;
    private java.lang.CharSequence DTE_EFF;
    private java.lang.CharSequence ADR_EML;
    private java.lang.CharSequence NUM_TEL;
    private java.lang.CharSequence CDE_CUST_CTRY;
    private java.lang.CharSequence DTE_SRC_RCD_UPDT;
    private java.lang.CharSequence TME_SRC_RCD_UPDT;
    private java.lang.CharSequence ID_SRC_RCD_UPDT_USER;
    private java.lang.CharSequence DTS_CREA;
    private java.lang.CharSequence ID_CREA_USER;
    private java.lang.CharSequence DTS_LAST_UPDT;
    private java.lang.CharSequence ID_LAST_UPDT_USER;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.mbusa.avro.dto.CmpgnCustDTO.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.ID_CUST)) {
        this.ID_CUST = data().deepCopy(fields()[0].schema(), other.ID_CUST);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.NAM_LAST)) {
        this.NAM_LAST = data().deepCopy(fields()[1].schema(), other.NAM_LAST);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.NAM_FIR)) {
        this.NAM_FIR = data().deepCopy(fields()[2].schema(), other.NAM_FIR);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.NAM_MID_INIT)) {
        this.NAM_MID_INIT = data().deepCopy(fields()[3].schema(), other.NAM_MID_INIT);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.NAM_PFX)) {
        this.NAM_PFX = data().deepCopy(fields()[4].schema(), other.NAM_PFX);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.NAM_SFX)) {
        this.NAM_SFX = data().deepCopy(fields()[5].schema(), other.NAM_SFX);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.ADR_LN_1)) {
        this.ADR_LN_1 = data().deepCopy(fields()[6].schema(), other.ADR_LN_1);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
      if (isValidValue(fields()[7], other.ADR_LN_2)) {
        this.ADR_LN_2 = data().deepCopy(fields()[7].schema(), other.ADR_LN_2);
        fieldSetFlags()[7] = other.fieldSetFlags()[7];
      }
      if (isValidValue(fields()[8], other.ADR_LN_3)) {
        this.ADR_LN_3 = data().deepCopy(fields()[8].schema(), other.ADR_LN_3);
        fieldSetFlags()[8] = other.fieldSetFlags()[8];
      }
      if (isValidValue(fields()[9], other.NAM_CITY)) {
        this.NAM_CITY = data().deepCopy(fields()[9].schema(), other.NAM_CITY);
        fieldSetFlags()[9] = other.fieldSetFlags()[9];
      }
      if (isValidValue(fields()[10], other.CDE_ST)) {
        this.CDE_ST = data().deepCopy(fields()[10].schema(), other.CDE_ST);
        fieldSetFlags()[10] = other.fieldSetFlags()[10];
      }
      if (isValidValue(fields()[11], other.CDE_ZIP)) {
        this.CDE_ZIP = data().deepCopy(fields()[11].schema(), other.CDE_ZIP);
        fieldSetFlags()[11] = other.fieldSetFlags()[11];
      }
      if (isValidValue(fields()[12], other.DTE_EFF)) {
        this.DTE_EFF = data().deepCopy(fields()[12].schema(), other.DTE_EFF);
        fieldSetFlags()[12] = other.fieldSetFlags()[12];
      }
      if (isValidValue(fields()[13], other.ADR_EML)) {
        this.ADR_EML = data().deepCopy(fields()[13].schema(), other.ADR_EML);
        fieldSetFlags()[13] = other.fieldSetFlags()[13];
      }
      if (isValidValue(fields()[14], other.NUM_TEL)) {
        this.NUM_TEL = data().deepCopy(fields()[14].schema(), other.NUM_TEL);
        fieldSetFlags()[14] = other.fieldSetFlags()[14];
      }
      if (isValidValue(fields()[15], other.CDE_CUST_CTRY)) {
        this.CDE_CUST_CTRY = data().deepCopy(fields()[15].schema(), other.CDE_CUST_CTRY);
        fieldSetFlags()[15] = other.fieldSetFlags()[15];
      }
      if (isValidValue(fields()[16], other.DTE_SRC_RCD_UPDT)) {
        this.DTE_SRC_RCD_UPDT = data().deepCopy(fields()[16].schema(), other.DTE_SRC_RCD_UPDT);
        fieldSetFlags()[16] = other.fieldSetFlags()[16];
      }
      if (isValidValue(fields()[17], other.TME_SRC_RCD_UPDT)) {
        this.TME_SRC_RCD_UPDT = data().deepCopy(fields()[17].schema(), other.TME_SRC_RCD_UPDT);
        fieldSetFlags()[17] = other.fieldSetFlags()[17];
      }
      if (isValidValue(fields()[18], other.ID_SRC_RCD_UPDT_USER)) {
        this.ID_SRC_RCD_UPDT_USER = data().deepCopy(fields()[18].schema(), other.ID_SRC_RCD_UPDT_USER);
        fieldSetFlags()[18] = other.fieldSetFlags()[18];
      }
      if (isValidValue(fields()[19], other.DTS_CREA)) {
        this.DTS_CREA = data().deepCopy(fields()[19].schema(), other.DTS_CREA);
        fieldSetFlags()[19] = other.fieldSetFlags()[19];
      }
      if (isValidValue(fields()[20], other.ID_CREA_USER)) {
        this.ID_CREA_USER = data().deepCopy(fields()[20].schema(), other.ID_CREA_USER);
        fieldSetFlags()[20] = other.fieldSetFlags()[20];
      }
      if (isValidValue(fields()[21], other.DTS_LAST_UPDT)) {
        this.DTS_LAST_UPDT = data().deepCopy(fields()[21].schema(), other.DTS_LAST_UPDT);
        fieldSetFlags()[21] = other.fieldSetFlags()[21];
      }
      if (isValidValue(fields()[22], other.ID_LAST_UPDT_USER)) {
        this.ID_LAST_UPDT_USER = data().deepCopy(fields()[22].schema(), other.ID_LAST_UPDT_USER);
        fieldSetFlags()[22] = other.fieldSetFlags()[22];
      }
    }

    /**
     * Creates a Builder by copying an existing CmpgnCustDTO instance
     * @param other The existing instance to copy.
     */
    private Builder(com.mbusa.avro.dto.CmpgnCustDTO other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.ID_CUST)) {
        this.ID_CUST = data().deepCopy(fields()[0].schema(), other.ID_CUST);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.NAM_LAST)) {
        this.NAM_LAST = data().deepCopy(fields()[1].schema(), other.NAM_LAST);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.NAM_FIR)) {
        this.NAM_FIR = data().deepCopy(fields()[2].schema(), other.NAM_FIR);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.NAM_MID_INIT)) {
        this.NAM_MID_INIT = data().deepCopy(fields()[3].schema(), other.NAM_MID_INIT);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.NAM_PFX)) {
        this.NAM_PFX = data().deepCopy(fields()[4].schema(), other.NAM_PFX);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.NAM_SFX)) {
        this.NAM_SFX = data().deepCopy(fields()[5].schema(), other.NAM_SFX);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.ADR_LN_1)) {
        this.ADR_LN_1 = data().deepCopy(fields()[6].schema(), other.ADR_LN_1);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.ADR_LN_2)) {
        this.ADR_LN_2 = data().deepCopy(fields()[7].schema(), other.ADR_LN_2);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.ADR_LN_3)) {
        this.ADR_LN_3 = data().deepCopy(fields()[8].schema(), other.ADR_LN_3);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.NAM_CITY)) {
        this.NAM_CITY = data().deepCopy(fields()[9].schema(), other.NAM_CITY);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.CDE_ST)) {
        this.CDE_ST = data().deepCopy(fields()[10].schema(), other.CDE_ST);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.CDE_ZIP)) {
        this.CDE_ZIP = data().deepCopy(fields()[11].schema(), other.CDE_ZIP);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.DTE_EFF)) {
        this.DTE_EFF = data().deepCopy(fields()[12].schema(), other.DTE_EFF);
        fieldSetFlags()[12] = true;
      }
      if (isValidValue(fields()[13], other.ADR_EML)) {
        this.ADR_EML = data().deepCopy(fields()[13].schema(), other.ADR_EML);
        fieldSetFlags()[13] = true;
      }
      if (isValidValue(fields()[14], other.NUM_TEL)) {
        this.NUM_TEL = data().deepCopy(fields()[14].schema(), other.NUM_TEL);
        fieldSetFlags()[14] = true;
      }
      if (isValidValue(fields()[15], other.CDE_CUST_CTRY)) {
        this.CDE_CUST_CTRY = data().deepCopy(fields()[15].schema(), other.CDE_CUST_CTRY);
        fieldSetFlags()[15] = true;
      }
      if (isValidValue(fields()[16], other.DTE_SRC_RCD_UPDT)) {
        this.DTE_SRC_RCD_UPDT = data().deepCopy(fields()[16].schema(), other.DTE_SRC_RCD_UPDT);
        fieldSetFlags()[16] = true;
      }
      if (isValidValue(fields()[17], other.TME_SRC_RCD_UPDT)) {
        this.TME_SRC_RCD_UPDT = data().deepCopy(fields()[17].schema(), other.TME_SRC_RCD_UPDT);
        fieldSetFlags()[17] = true;
      }
      if (isValidValue(fields()[18], other.ID_SRC_RCD_UPDT_USER)) {
        this.ID_SRC_RCD_UPDT_USER = data().deepCopy(fields()[18].schema(), other.ID_SRC_RCD_UPDT_USER);
        fieldSetFlags()[18] = true;
      }
      if (isValidValue(fields()[19], other.DTS_CREA)) {
        this.DTS_CREA = data().deepCopy(fields()[19].schema(), other.DTS_CREA);
        fieldSetFlags()[19] = true;
      }
      if (isValidValue(fields()[20], other.ID_CREA_USER)) {
        this.ID_CREA_USER = data().deepCopy(fields()[20].schema(), other.ID_CREA_USER);
        fieldSetFlags()[20] = true;
      }
      if (isValidValue(fields()[21], other.DTS_LAST_UPDT)) {
        this.DTS_LAST_UPDT = data().deepCopy(fields()[21].schema(), other.DTS_LAST_UPDT);
        fieldSetFlags()[21] = true;
      }
      if (isValidValue(fields()[22], other.ID_LAST_UPDT_USER)) {
        this.ID_LAST_UPDT_USER = data().deepCopy(fields()[22].schema(), other.ID_LAST_UPDT_USER);
        fieldSetFlags()[22] = true;
      }
    }

    /**
      * Gets the value of the 'ID_CUST' field.
      * @return The value.
      */
    public java.lang.CharSequence getIDCUST() {
      return ID_CUST;
    }


    /**
      * Sets the value of the 'ID_CUST' field.
      * @param value The value of 'ID_CUST'.
      * @return This builder.
      */
    public com.mbusa.avro.dto.CmpgnCustDTO.Builder setIDCUST(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.ID_CUST = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'ID_CUST' field has been set.
      * @return True if the 'ID_CUST' field has been set, false otherwise.
      */
    public boolean hasIDCUST() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'ID_CUST' field.
      * @return This builder.
      */
    public com.mbusa.avro.dto.CmpgnCustDTO.Builder clearIDCUST() {
      ID_CUST = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'NAM_LAST' field.
      * @return The value.
      */
    public java.lang.CharSequence getNAMLAST() {
      return NAM_LAST;
    }


    /**
      * Sets the value of the 'NAM_LAST' field.
      * @param value The value of 'NAM_LAST'.
      * @return This builder.
      */
    public com.mbusa.avro.dto.CmpgnCustDTO.Builder setNAMLAST(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.NAM_LAST = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'NAM_LAST' field has been set.
      * @return True if the 'NAM_LAST' field has been set, false otherwise.
      */
    public boolean hasNAMLAST() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'NAM_LAST' field.
      * @return This builder.
      */
    public com.mbusa.avro.dto.CmpgnCustDTO.Builder clearNAMLAST() {
      NAM_LAST = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'NAM_FIR' field.
      * @return The value.
      */
    public java.lang.CharSequence getNAMFIR() {
      return NAM_FIR;
    }


    /**
      * Sets the value of the 'NAM_FIR' field.
      * @param value The value of 'NAM_FIR'.
      * @return This builder.
      */
    public com.mbusa.avro.dto.CmpgnCustDTO.Builder setNAMFIR(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.NAM_FIR = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'NAM_FIR' field has been set.
      * @return True if the 'NAM_FIR' field has been set, false otherwise.
      */
    public boolean hasNAMFIR() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'NAM_FIR' field.
      * @return This builder.
      */
    public com.mbusa.avro.dto.CmpgnCustDTO.Builder clearNAMFIR() {
      NAM_FIR = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'NAM_MID_INIT' field.
      * @return The value.
      */
    public java.lang.CharSequence getNAMMIDINIT() {
      return NAM_MID_INIT;
    }


    /**
      * Sets the value of the 'NAM_MID_INIT' field.
      * @param value The value of 'NAM_MID_INIT'.
      * @return This builder.
      */
    public com.mbusa.avro.dto.CmpgnCustDTO.Builder setNAMMIDINIT(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.NAM_MID_INIT = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'NAM_MID_INIT' field has been set.
      * @return True if the 'NAM_MID_INIT' field has been set, false otherwise.
      */
    public boolean hasNAMMIDINIT() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'NAM_MID_INIT' field.
      * @return This builder.
      */
    public com.mbusa.avro.dto.CmpgnCustDTO.Builder clearNAMMIDINIT() {
      NAM_MID_INIT = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'NAM_PFX' field.
      * @return The value.
      */
    public java.lang.CharSequence getNAMPFX() {
      return NAM_PFX;
    }


    /**
      * Sets the value of the 'NAM_PFX' field.
      * @param value The value of 'NAM_PFX'.
      * @return This builder.
      */
    public com.mbusa.avro.dto.CmpgnCustDTO.Builder setNAMPFX(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.NAM_PFX = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'NAM_PFX' field has been set.
      * @return True if the 'NAM_PFX' field has been set, false otherwise.
      */
    public boolean hasNAMPFX() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'NAM_PFX' field.
      * @return This builder.
      */
    public com.mbusa.avro.dto.CmpgnCustDTO.Builder clearNAMPFX() {
      NAM_PFX = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'NAM_SFX' field.
      * @return The value.
      */
    public java.lang.CharSequence getNAMSFX() {
      return NAM_SFX;
    }


    /**
      * Sets the value of the 'NAM_SFX' field.
      * @param value The value of 'NAM_SFX'.
      * @return This builder.
      */
    public com.mbusa.avro.dto.CmpgnCustDTO.Builder setNAMSFX(java.lang.CharSequence value) {
      validate(fields()[5], value);
      this.NAM_SFX = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'NAM_SFX' field has been set.
      * @return True if the 'NAM_SFX' field has been set, false otherwise.
      */
    public boolean hasNAMSFX() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'NAM_SFX' field.
      * @return This builder.
      */
    public com.mbusa.avro.dto.CmpgnCustDTO.Builder clearNAMSFX() {
      NAM_SFX = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'ADR_LN_1' field.
      * @return The value.
      */
    public java.lang.CharSequence getADRLN1() {
      return ADR_LN_1;
    }


    /**
      * Sets the value of the 'ADR_LN_1' field.
      * @param value The value of 'ADR_LN_1'.
      * @return This builder.
      */
    public com.mbusa.avro.dto.CmpgnCustDTO.Builder setADRLN1(java.lang.CharSequence value) {
      validate(fields()[6], value);
      this.ADR_LN_1 = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'ADR_LN_1' field has been set.
      * @return True if the 'ADR_LN_1' field has been set, false otherwise.
      */
    public boolean hasADRLN1() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'ADR_LN_1' field.
      * @return This builder.
      */
    public com.mbusa.avro.dto.CmpgnCustDTO.Builder clearADRLN1() {
      ADR_LN_1 = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'ADR_LN_2' field.
      * @return The value.
      */
    public java.lang.CharSequence getADRLN2() {
      return ADR_LN_2;
    }


    /**
      * Sets the value of the 'ADR_LN_2' field.
      * @param value The value of 'ADR_LN_2'.
      * @return This builder.
      */
    public com.mbusa.avro.dto.CmpgnCustDTO.Builder setADRLN2(java.lang.CharSequence value) {
      validate(fields()[7], value);
      this.ADR_LN_2 = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'ADR_LN_2' field has been set.
      * @return True if the 'ADR_LN_2' field has been set, false otherwise.
      */
    public boolean hasADRLN2() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'ADR_LN_2' field.
      * @return This builder.
      */
    public com.mbusa.avro.dto.CmpgnCustDTO.Builder clearADRLN2() {
      ADR_LN_2 = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    /**
      * Gets the value of the 'ADR_LN_3' field.
      * @return The value.
      */
    public java.lang.CharSequence getADRLN3() {
      return ADR_LN_3;
    }


    /**
      * Sets the value of the 'ADR_LN_3' field.
      * @param value The value of 'ADR_LN_3'.
      * @return This builder.
      */
    public com.mbusa.avro.dto.CmpgnCustDTO.Builder setADRLN3(java.lang.CharSequence value) {
      validate(fields()[8], value);
      this.ADR_LN_3 = value;
      fieldSetFlags()[8] = true;
      return this;
    }

    /**
      * Checks whether the 'ADR_LN_3' field has been set.
      * @return True if the 'ADR_LN_3' field has been set, false otherwise.
      */
    public boolean hasADRLN3() {
      return fieldSetFlags()[8];
    }


    /**
      * Clears the value of the 'ADR_LN_3' field.
      * @return This builder.
      */
    public com.mbusa.avro.dto.CmpgnCustDTO.Builder clearADRLN3() {
      ADR_LN_3 = null;
      fieldSetFlags()[8] = false;
      return this;
    }

    /**
      * Gets the value of the 'NAM_CITY' field.
      * @return The value.
      */
    public java.lang.CharSequence getNAMCITY() {
      return NAM_CITY;
    }


    /**
      * Sets the value of the 'NAM_CITY' field.
      * @param value The value of 'NAM_CITY'.
      * @return This builder.
      */
    public com.mbusa.avro.dto.CmpgnCustDTO.Builder setNAMCITY(java.lang.CharSequence value) {
      validate(fields()[9], value);
      this.NAM_CITY = value;
      fieldSetFlags()[9] = true;
      return this;
    }

    /**
      * Checks whether the 'NAM_CITY' field has been set.
      * @return True if the 'NAM_CITY' field has been set, false otherwise.
      */
    public boolean hasNAMCITY() {
      return fieldSetFlags()[9];
    }


    /**
      * Clears the value of the 'NAM_CITY' field.
      * @return This builder.
      */
    public com.mbusa.avro.dto.CmpgnCustDTO.Builder clearNAMCITY() {
      NAM_CITY = null;
      fieldSetFlags()[9] = false;
      return this;
    }

    /**
      * Gets the value of the 'CDE_ST' field.
      * @return The value.
      */
    public java.lang.CharSequence getCDEST() {
      return CDE_ST;
    }


    /**
      * Sets the value of the 'CDE_ST' field.
      * @param value The value of 'CDE_ST'.
      * @return This builder.
      */
    public com.mbusa.avro.dto.CmpgnCustDTO.Builder setCDEST(java.lang.CharSequence value) {
      validate(fields()[10], value);
      this.CDE_ST = value;
      fieldSetFlags()[10] = true;
      return this;
    }

    /**
      * Checks whether the 'CDE_ST' field has been set.
      * @return True if the 'CDE_ST' field has been set, false otherwise.
      */
    public boolean hasCDEST() {
      return fieldSetFlags()[10];
    }


    /**
      * Clears the value of the 'CDE_ST' field.
      * @return This builder.
      */
    public com.mbusa.avro.dto.CmpgnCustDTO.Builder clearCDEST() {
      CDE_ST = null;
      fieldSetFlags()[10] = false;
      return this;
    }

    /**
      * Gets the value of the 'CDE_ZIP' field.
      * @return The value.
      */
    public java.lang.CharSequence getCDEZIP() {
      return CDE_ZIP;
    }


    /**
      * Sets the value of the 'CDE_ZIP' field.
      * @param value The value of 'CDE_ZIP'.
      * @return This builder.
      */
    public com.mbusa.avro.dto.CmpgnCustDTO.Builder setCDEZIP(java.lang.CharSequence value) {
      validate(fields()[11], value);
      this.CDE_ZIP = value;
      fieldSetFlags()[11] = true;
      return this;
    }

    /**
      * Checks whether the 'CDE_ZIP' field has been set.
      * @return True if the 'CDE_ZIP' field has been set, false otherwise.
      */
    public boolean hasCDEZIP() {
      return fieldSetFlags()[11];
    }


    /**
      * Clears the value of the 'CDE_ZIP' field.
      * @return This builder.
      */
    public com.mbusa.avro.dto.CmpgnCustDTO.Builder clearCDEZIP() {
      CDE_ZIP = null;
      fieldSetFlags()[11] = false;
      return this;
    }

    /**
      * Gets the value of the 'DTE_EFF' field.
      * @return The value.
      */
    public java.lang.CharSequence getDTEEFF() {
      return DTE_EFF;
    }


    /**
      * Sets the value of the 'DTE_EFF' field.
      * @param value The value of 'DTE_EFF'.
      * @return This builder.
      */
    public com.mbusa.avro.dto.CmpgnCustDTO.Builder setDTEEFF(java.lang.CharSequence value) {
      validate(fields()[12], value);
      this.DTE_EFF = value;
      fieldSetFlags()[12] = true;
      return this;
    }

    /**
      * Checks whether the 'DTE_EFF' field has been set.
      * @return True if the 'DTE_EFF' field has been set, false otherwise.
      */
    public boolean hasDTEEFF() {
      return fieldSetFlags()[12];
    }


    /**
      * Clears the value of the 'DTE_EFF' field.
      * @return This builder.
      */
    public com.mbusa.avro.dto.CmpgnCustDTO.Builder clearDTEEFF() {
      DTE_EFF = null;
      fieldSetFlags()[12] = false;
      return this;
    }

    /**
      * Gets the value of the 'ADR_EML' field.
      * @return The value.
      */
    public java.lang.CharSequence getADREML() {
      return ADR_EML;
    }


    /**
      * Sets the value of the 'ADR_EML' field.
      * @param value The value of 'ADR_EML'.
      * @return This builder.
      */
    public com.mbusa.avro.dto.CmpgnCustDTO.Builder setADREML(java.lang.CharSequence value) {
      validate(fields()[13], value);
      this.ADR_EML = value;
      fieldSetFlags()[13] = true;
      return this;
    }

    /**
      * Checks whether the 'ADR_EML' field has been set.
      * @return True if the 'ADR_EML' field has been set, false otherwise.
      */
    public boolean hasADREML() {
      return fieldSetFlags()[13];
    }


    /**
      * Clears the value of the 'ADR_EML' field.
      * @return This builder.
      */
    public com.mbusa.avro.dto.CmpgnCustDTO.Builder clearADREML() {
      ADR_EML = null;
      fieldSetFlags()[13] = false;
      return this;
    }

    /**
      * Gets the value of the 'NUM_TEL' field.
      * @return The value.
      */
    public java.lang.CharSequence getNUMTEL() {
      return NUM_TEL;
    }


    /**
      * Sets the value of the 'NUM_TEL' field.
      * @param value The value of 'NUM_TEL'.
      * @return This builder.
      */
    public com.mbusa.avro.dto.CmpgnCustDTO.Builder setNUMTEL(java.lang.CharSequence value) {
      validate(fields()[14], value);
      this.NUM_TEL = value;
      fieldSetFlags()[14] = true;
      return this;
    }

    /**
      * Checks whether the 'NUM_TEL' field has been set.
      * @return True if the 'NUM_TEL' field has been set, false otherwise.
      */
    public boolean hasNUMTEL() {
      return fieldSetFlags()[14];
    }


    /**
      * Clears the value of the 'NUM_TEL' field.
      * @return This builder.
      */
    public com.mbusa.avro.dto.CmpgnCustDTO.Builder clearNUMTEL() {
      NUM_TEL = null;
      fieldSetFlags()[14] = false;
      return this;
    }

    /**
      * Gets the value of the 'CDE_CUST_CTRY' field.
      * @return The value.
      */
    public java.lang.CharSequence getCDECUSTCTRY() {
      return CDE_CUST_CTRY;
    }


    /**
      * Sets the value of the 'CDE_CUST_CTRY' field.
      * @param value The value of 'CDE_CUST_CTRY'.
      * @return This builder.
      */
    public com.mbusa.avro.dto.CmpgnCustDTO.Builder setCDECUSTCTRY(java.lang.CharSequence value) {
      validate(fields()[15], value);
      this.CDE_CUST_CTRY = value;
      fieldSetFlags()[15] = true;
      return this;
    }

    /**
      * Checks whether the 'CDE_CUST_CTRY' field has been set.
      * @return True if the 'CDE_CUST_CTRY' field has been set, false otherwise.
      */
    public boolean hasCDECUSTCTRY() {
      return fieldSetFlags()[15];
    }


    /**
      * Clears the value of the 'CDE_CUST_CTRY' field.
      * @return This builder.
      */
    public com.mbusa.avro.dto.CmpgnCustDTO.Builder clearCDECUSTCTRY() {
      CDE_CUST_CTRY = null;
      fieldSetFlags()[15] = false;
      return this;
    }

    /**
      * Gets the value of the 'DTE_SRC_RCD_UPDT' field.
      * @return The value.
      */
    public java.lang.CharSequence getDTESRCRCDUPDT() {
      return DTE_SRC_RCD_UPDT;
    }


    /**
      * Sets the value of the 'DTE_SRC_RCD_UPDT' field.
      * @param value The value of 'DTE_SRC_RCD_UPDT'.
      * @return This builder.
      */
    public com.mbusa.avro.dto.CmpgnCustDTO.Builder setDTESRCRCDUPDT(java.lang.CharSequence value) {
      validate(fields()[16], value);
      this.DTE_SRC_RCD_UPDT = value;
      fieldSetFlags()[16] = true;
      return this;
    }

    /**
      * Checks whether the 'DTE_SRC_RCD_UPDT' field has been set.
      * @return True if the 'DTE_SRC_RCD_UPDT' field has been set, false otherwise.
      */
    public boolean hasDTESRCRCDUPDT() {
      return fieldSetFlags()[16];
    }


    /**
      * Clears the value of the 'DTE_SRC_RCD_UPDT' field.
      * @return This builder.
      */
    public com.mbusa.avro.dto.CmpgnCustDTO.Builder clearDTESRCRCDUPDT() {
      DTE_SRC_RCD_UPDT = null;
      fieldSetFlags()[16] = false;
      return this;
    }

    /**
      * Gets the value of the 'TME_SRC_RCD_UPDT' field.
      * @return The value.
      */
    public java.lang.CharSequence getTMESRCRCDUPDT() {
      return TME_SRC_RCD_UPDT;
    }


    /**
      * Sets the value of the 'TME_SRC_RCD_UPDT' field.
      * @param value The value of 'TME_SRC_RCD_UPDT'.
      * @return This builder.
      */
    public com.mbusa.avro.dto.CmpgnCustDTO.Builder setTMESRCRCDUPDT(java.lang.CharSequence value) {
      validate(fields()[17], value);
      this.TME_SRC_RCD_UPDT = value;
      fieldSetFlags()[17] = true;
      return this;
    }

    /**
      * Checks whether the 'TME_SRC_RCD_UPDT' field has been set.
      * @return True if the 'TME_SRC_RCD_UPDT' field has been set, false otherwise.
      */
    public boolean hasTMESRCRCDUPDT() {
      return fieldSetFlags()[17];
    }


    /**
      * Clears the value of the 'TME_SRC_RCD_UPDT' field.
      * @return This builder.
      */
    public com.mbusa.avro.dto.CmpgnCustDTO.Builder clearTMESRCRCDUPDT() {
      TME_SRC_RCD_UPDT = null;
      fieldSetFlags()[17] = false;
      return this;
    }

    /**
      * Gets the value of the 'ID_SRC_RCD_UPDT_USER' field.
      * @return The value.
      */
    public java.lang.CharSequence getIDSRCRCDUPDTUSER() {
      return ID_SRC_RCD_UPDT_USER;
    }


    /**
      * Sets the value of the 'ID_SRC_RCD_UPDT_USER' field.
      * @param value The value of 'ID_SRC_RCD_UPDT_USER'.
      * @return This builder.
      */
    public com.mbusa.avro.dto.CmpgnCustDTO.Builder setIDSRCRCDUPDTUSER(java.lang.CharSequence value) {
      validate(fields()[18], value);
      this.ID_SRC_RCD_UPDT_USER = value;
      fieldSetFlags()[18] = true;
      return this;
    }

    /**
      * Checks whether the 'ID_SRC_RCD_UPDT_USER' field has been set.
      * @return True if the 'ID_SRC_RCD_UPDT_USER' field has been set, false otherwise.
      */
    public boolean hasIDSRCRCDUPDTUSER() {
      return fieldSetFlags()[18];
    }


    /**
      * Clears the value of the 'ID_SRC_RCD_UPDT_USER' field.
      * @return This builder.
      */
    public com.mbusa.avro.dto.CmpgnCustDTO.Builder clearIDSRCRCDUPDTUSER() {
      ID_SRC_RCD_UPDT_USER = null;
      fieldSetFlags()[18] = false;
      return this;
    }

    /**
      * Gets the value of the 'DTS_CREA' field.
      * @return The value.
      */
    public java.lang.CharSequence getDTSCREA() {
      return DTS_CREA;
    }


    /**
      * Sets the value of the 'DTS_CREA' field.
      * @param value The value of 'DTS_CREA'.
      * @return This builder.
      */
    public com.mbusa.avro.dto.CmpgnCustDTO.Builder setDTSCREA(java.lang.CharSequence value) {
      validate(fields()[19], value);
      this.DTS_CREA = value;
      fieldSetFlags()[19] = true;
      return this;
    }

    /**
      * Checks whether the 'DTS_CREA' field has been set.
      * @return True if the 'DTS_CREA' field has been set, false otherwise.
      */
    public boolean hasDTSCREA() {
      return fieldSetFlags()[19];
    }


    /**
      * Clears the value of the 'DTS_CREA' field.
      * @return This builder.
      */
    public com.mbusa.avro.dto.CmpgnCustDTO.Builder clearDTSCREA() {
      DTS_CREA = null;
      fieldSetFlags()[19] = false;
      return this;
    }

    /**
      * Gets the value of the 'ID_CREA_USER' field.
      * @return The value.
      */
    public java.lang.CharSequence getIDCREAUSER() {
      return ID_CREA_USER;
    }


    /**
      * Sets the value of the 'ID_CREA_USER' field.
      * @param value The value of 'ID_CREA_USER'.
      * @return This builder.
      */
    public com.mbusa.avro.dto.CmpgnCustDTO.Builder setIDCREAUSER(java.lang.CharSequence value) {
      validate(fields()[20], value);
      this.ID_CREA_USER = value;
      fieldSetFlags()[20] = true;
      return this;
    }

    /**
      * Checks whether the 'ID_CREA_USER' field has been set.
      * @return True if the 'ID_CREA_USER' field has been set, false otherwise.
      */
    public boolean hasIDCREAUSER() {
      return fieldSetFlags()[20];
    }


    /**
      * Clears the value of the 'ID_CREA_USER' field.
      * @return This builder.
      */
    public com.mbusa.avro.dto.CmpgnCustDTO.Builder clearIDCREAUSER() {
      ID_CREA_USER = null;
      fieldSetFlags()[20] = false;
      return this;
    }

    /**
      * Gets the value of the 'DTS_LAST_UPDT' field.
      * @return The value.
      */
    public java.lang.CharSequence getDTSLASTUPDT() {
      return DTS_LAST_UPDT;
    }


    /**
      * Sets the value of the 'DTS_LAST_UPDT' field.
      * @param value The value of 'DTS_LAST_UPDT'.
      * @return This builder.
      */
    public com.mbusa.avro.dto.CmpgnCustDTO.Builder setDTSLASTUPDT(java.lang.CharSequence value) {
      validate(fields()[21], value);
      this.DTS_LAST_UPDT = value;
      fieldSetFlags()[21] = true;
      return this;
    }

    /**
      * Checks whether the 'DTS_LAST_UPDT' field has been set.
      * @return True if the 'DTS_LAST_UPDT' field has been set, false otherwise.
      */
    public boolean hasDTSLASTUPDT() {
      return fieldSetFlags()[21];
    }


    /**
      * Clears the value of the 'DTS_LAST_UPDT' field.
      * @return This builder.
      */
    public com.mbusa.avro.dto.CmpgnCustDTO.Builder clearDTSLASTUPDT() {
      DTS_LAST_UPDT = null;
      fieldSetFlags()[21] = false;
      return this;
    }

    /**
      * Gets the value of the 'ID_LAST_UPDT_USER' field.
      * @return The value.
      */
    public java.lang.CharSequence getIDLASTUPDTUSER() {
      return ID_LAST_UPDT_USER;
    }


    /**
      * Sets the value of the 'ID_LAST_UPDT_USER' field.
      * @param value The value of 'ID_LAST_UPDT_USER'.
      * @return This builder.
      */
    public com.mbusa.avro.dto.CmpgnCustDTO.Builder setIDLASTUPDTUSER(java.lang.CharSequence value) {
      validate(fields()[22], value);
      this.ID_LAST_UPDT_USER = value;
      fieldSetFlags()[22] = true;
      return this;
    }

    /**
      * Checks whether the 'ID_LAST_UPDT_USER' field has been set.
      * @return True if the 'ID_LAST_UPDT_USER' field has been set, false otherwise.
      */
    public boolean hasIDLASTUPDTUSER() {
      return fieldSetFlags()[22];
    }


    /**
      * Clears the value of the 'ID_LAST_UPDT_USER' field.
      * @return This builder.
      */
    public com.mbusa.avro.dto.CmpgnCustDTO.Builder clearIDLASTUPDTUSER() {
      ID_LAST_UPDT_USER = null;
      fieldSetFlags()[22] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public CmpgnCustDTO build() {
      try {
        CmpgnCustDTO record = new CmpgnCustDTO();
        record.ID_CUST = fieldSetFlags()[0] ? this.ID_CUST : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.NAM_LAST = fieldSetFlags()[1] ? this.NAM_LAST : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.NAM_FIR = fieldSetFlags()[2] ? this.NAM_FIR : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.NAM_MID_INIT = fieldSetFlags()[3] ? this.NAM_MID_INIT : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.NAM_PFX = fieldSetFlags()[4] ? this.NAM_PFX : (java.lang.CharSequence) defaultValue(fields()[4]);
        record.NAM_SFX = fieldSetFlags()[5] ? this.NAM_SFX : (java.lang.CharSequence) defaultValue(fields()[5]);
        record.ADR_LN_1 = fieldSetFlags()[6] ? this.ADR_LN_1 : (java.lang.CharSequence) defaultValue(fields()[6]);
        record.ADR_LN_2 = fieldSetFlags()[7] ? this.ADR_LN_2 : (java.lang.CharSequence) defaultValue(fields()[7]);
        record.ADR_LN_3 = fieldSetFlags()[8] ? this.ADR_LN_3 : (java.lang.CharSequence) defaultValue(fields()[8]);
        record.NAM_CITY = fieldSetFlags()[9] ? this.NAM_CITY : (java.lang.CharSequence) defaultValue(fields()[9]);
        record.CDE_ST = fieldSetFlags()[10] ? this.CDE_ST : (java.lang.CharSequence) defaultValue(fields()[10]);
        record.CDE_ZIP = fieldSetFlags()[11] ? this.CDE_ZIP : (java.lang.CharSequence) defaultValue(fields()[11]);
        record.DTE_EFF = fieldSetFlags()[12] ? this.DTE_EFF : (java.lang.CharSequence) defaultValue(fields()[12]);
        record.ADR_EML = fieldSetFlags()[13] ? this.ADR_EML : (java.lang.CharSequence) defaultValue(fields()[13]);
        record.NUM_TEL = fieldSetFlags()[14] ? this.NUM_TEL : (java.lang.CharSequence) defaultValue(fields()[14]);
        record.CDE_CUST_CTRY = fieldSetFlags()[15] ? this.CDE_CUST_CTRY : (java.lang.CharSequence) defaultValue(fields()[15]);
        record.DTE_SRC_RCD_UPDT = fieldSetFlags()[16] ? this.DTE_SRC_RCD_UPDT : (java.lang.CharSequence) defaultValue(fields()[16]);
        record.TME_SRC_RCD_UPDT = fieldSetFlags()[17] ? this.TME_SRC_RCD_UPDT : (java.lang.CharSequence) defaultValue(fields()[17]);
        record.ID_SRC_RCD_UPDT_USER = fieldSetFlags()[18] ? this.ID_SRC_RCD_UPDT_USER : (java.lang.CharSequence) defaultValue(fields()[18]);
        record.DTS_CREA = fieldSetFlags()[19] ? this.DTS_CREA : (java.lang.CharSequence) defaultValue(fields()[19]);
        record.ID_CREA_USER = fieldSetFlags()[20] ? this.ID_CREA_USER : (java.lang.CharSequence) defaultValue(fields()[20]);
        record.DTS_LAST_UPDT = fieldSetFlags()[21] ? this.DTS_LAST_UPDT : (java.lang.CharSequence) defaultValue(fields()[21]);
        record.ID_LAST_UPDT_USER = fieldSetFlags()[22] ? this.ID_LAST_UPDT_USER : (java.lang.CharSequence) defaultValue(fields()[22]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<CmpgnCustDTO>
    WRITER$ = (org.apache.avro.io.DatumWriter<CmpgnCustDTO>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<CmpgnCustDTO>
    READER$ = (org.apache.avro.io.DatumReader<CmpgnCustDTO>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.ID_CUST);

    out.writeString(this.NAM_LAST);

    out.writeString(this.NAM_FIR);

    out.writeString(this.NAM_MID_INIT);

    out.writeString(this.NAM_PFX);

    out.writeString(this.NAM_SFX);

    out.writeString(this.ADR_LN_1);

    out.writeString(this.ADR_LN_2);

    out.writeString(this.ADR_LN_3);

    out.writeString(this.NAM_CITY);

    out.writeString(this.CDE_ST);

    out.writeString(this.CDE_ZIP);

    out.writeString(this.DTE_EFF);

    out.writeString(this.ADR_EML);

    out.writeString(this.NUM_TEL);

    out.writeString(this.CDE_CUST_CTRY);

    out.writeString(this.DTE_SRC_RCD_UPDT);

    out.writeString(this.TME_SRC_RCD_UPDT);

    out.writeString(this.ID_SRC_RCD_UPDT_USER);

    out.writeString(this.DTS_CREA);

    out.writeString(this.ID_CREA_USER);

    out.writeString(this.DTS_LAST_UPDT);

    out.writeString(this.ID_LAST_UPDT_USER);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.ID_CUST = in.readString(this.ID_CUST instanceof Utf8 ? (Utf8)this.ID_CUST : null);

      this.NAM_LAST = in.readString(this.NAM_LAST instanceof Utf8 ? (Utf8)this.NAM_LAST : null);

      this.NAM_FIR = in.readString(this.NAM_FIR instanceof Utf8 ? (Utf8)this.NAM_FIR : null);

      this.NAM_MID_INIT = in.readString(this.NAM_MID_INIT instanceof Utf8 ? (Utf8)this.NAM_MID_INIT : null);

      this.NAM_PFX = in.readString(this.NAM_PFX instanceof Utf8 ? (Utf8)this.NAM_PFX : null);

      this.NAM_SFX = in.readString(this.NAM_SFX instanceof Utf8 ? (Utf8)this.NAM_SFX : null);

      this.ADR_LN_1 = in.readString(this.ADR_LN_1 instanceof Utf8 ? (Utf8)this.ADR_LN_1 : null);

      this.ADR_LN_2 = in.readString(this.ADR_LN_2 instanceof Utf8 ? (Utf8)this.ADR_LN_2 : null);

      this.ADR_LN_3 = in.readString(this.ADR_LN_3 instanceof Utf8 ? (Utf8)this.ADR_LN_3 : null);

      this.NAM_CITY = in.readString(this.NAM_CITY instanceof Utf8 ? (Utf8)this.NAM_CITY : null);

      this.CDE_ST = in.readString(this.CDE_ST instanceof Utf8 ? (Utf8)this.CDE_ST : null);

      this.CDE_ZIP = in.readString(this.CDE_ZIP instanceof Utf8 ? (Utf8)this.CDE_ZIP : null);

      this.DTE_EFF = in.readString(this.DTE_EFF instanceof Utf8 ? (Utf8)this.DTE_EFF : null);

      this.ADR_EML = in.readString(this.ADR_EML instanceof Utf8 ? (Utf8)this.ADR_EML : null);

      this.NUM_TEL = in.readString(this.NUM_TEL instanceof Utf8 ? (Utf8)this.NUM_TEL : null);

      this.CDE_CUST_CTRY = in.readString(this.CDE_CUST_CTRY instanceof Utf8 ? (Utf8)this.CDE_CUST_CTRY : null);

      this.DTE_SRC_RCD_UPDT = in.readString(this.DTE_SRC_RCD_UPDT instanceof Utf8 ? (Utf8)this.DTE_SRC_RCD_UPDT : null);

      this.TME_SRC_RCD_UPDT = in.readString(this.TME_SRC_RCD_UPDT instanceof Utf8 ? (Utf8)this.TME_SRC_RCD_UPDT : null);

      this.ID_SRC_RCD_UPDT_USER = in.readString(this.ID_SRC_RCD_UPDT_USER instanceof Utf8 ? (Utf8)this.ID_SRC_RCD_UPDT_USER : null);

      this.DTS_CREA = in.readString(this.DTS_CREA instanceof Utf8 ? (Utf8)this.DTS_CREA : null);

      this.ID_CREA_USER = in.readString(this.ID_CREA_USER instanceof Utf8 ? (Utf8)this.ID_CREA_USER : null);

      this.DTS_LAST_UPDT = in.readString(this.DTS_LAST_UPDT instanceof Utf8 ? (Utf8)this.DTS_LAST_UPDT : null);

      this.ID_LAST_UPDT_USER = in.readString(this.ID_LAST_UPDT_USER instanceof Utf8 ? (Utf8)this.ID_LAST_UPDT_USER : null);

    } else {
      for (int i = 0; i < 23; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.ID_CUST = in.readString(this.ID_CUST instanceof Utf8 ? (Utf8)this.ID_CUST : null);
          break;

        case 1:
          this.NAM_LAST = in.readString(this.NAM_LAST instanceof Utf8 ? (Utf8)this.NAM_LAST : null);
          break;

        case 2:
          this.NAM_FIR = in.readString(this.NAM_FIR instanceof Utf8 ? (Utf8)this.NAM_FIR : null);
          break;

        case 3:
          this.NAM_MID_INIT = in.readString(this.NAM_MID_INIT instanceof Utf8 ? (Utf8)this.NAM_MID_INIT : null);
          break;

        case 4:
          this.NAM_PFX = in.readString(this.NAM_PFX instanceof Utf8 ? (Utf8)this.NAM_PFX : null);
          break;

        case 5:
          this.NAM_SFX = in.readString(this.NAM_SFX instanceof Utf8 ? (Utf8)this.NAM_SFX : null);
          break;

        case 6:
          this.ADR_LN_1 = in.readString(this.ADR_LN_1 instanceof Utf8 ? (Utf8)this.ADR_LN_1 : null);
          break;

        case 7:
          this.ADR_LN_2 = in.readString(this.ADR_LN_2 instanceof Utf8 ? (Utf8)this.ADR_LN_2 : null);
          break;

        case 8:
          this.ADR_LN_3 = in.readString(this.ADR_LN_3 instanceof Utf8 ? (Utf8)this.ADR_LN_3 : null);
          break;

        case 9:
          this.NAM_CITY = in.readString(this.NAM_CITY instanceof Utf8 ? (Utf8)this.NAM_CITY : null);
          break;

        case 10:
          this.CDE_ST = in.readString(this.CDE_ST instanceof Utf8 ? (Utf8)this.CDE_ST : null);
          break;

        case 11:
          this.CDE_ZIP = in.readString(this.CDE_ZIP instanceof Utf8 ? (Utf8)this.CDE_ZIP : null);
          break;

        case 12:
          this.DTE_EFF = in.readString(this.DTE_EFF instanceof Utf8 ? (Utf8)this.DTE_EFF : null);
          break;

        case 13:
          this.ADR_EML = in.readString(this.ADR_EML instanceof Utf8 ? (Utf8)this.ADR_EML : null);
          break;

        case 14:
          this.NUM_TEL = in.readString(this.NUM_TEL instanceof Utf8 ? (Utf8)this.NUM_TEL : null);
          break;

        case 15:
          this.CDE_CUST_CTRY = in.readString(this.CDE_CUST_CTRY instanceof Utf8 ? (Utf8)this.CDE_CUST_CTRY : null);
          break;

        case 16:
          this.DTE_SRC_RCD_UPDT = in.readString(this.DTE_SRC_RCD_UPDT instanceof Utf8 ? (Utf8)this.DTE_SRC_RCD_UPDT : null);
          break;

        case 17:
          this.TME_SRC_RCD_UPDT = in.readString(this.TME_SRC_RCD_UPDT instanceof Utf8 ? (Utf8)this.TME_SRC_RCD_UPDT : null);
          break;

        case 18:
          this.ID_SRC_RCD_UPDT_USER = in.readString(this.ID_SRC_RCD_UPDT_USER instanceof Utf8 ? (Utf8)this.ID_SRC_RCD_UPDT_USER : null);
          break;

        case 19:
          this.DTS_CREA = in.readString(this.DTS_CREA instanceof Utf8 ? (Utf8)this.DTS_CREA : null);
          break;

        case 20:
          this.ID_CREA_USER = in.readString(this.ID_CREA_USER instanceof Utf8 ? (Utf8)this.ID_CREA_USER : null);
          break;

        case 21:
          this.DTS_LAST_UPDT = in.readString(this.DTS_LAST_UPDT instanceof Utf8 ? (Utf8)this.DTS_LAST_UPDT : null);
          break;

        case 22:
          this.ID_LAST_UPDT_USER = in.readString(this.ID_LAST_UPDT_USER instanceof Utf8 ? (Utf8)this.ID_LAST_UPDT_USER : null);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










