/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.mbusa.avro.dto;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class CmpgnVehDlrAsgmtDTO extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 9185938807555411594L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"CmpgnVehDlrAsgmtDTO\",\"namespace\":\"com.mbusa.avro.dto\",\"fields\":[{\"name\":\"CDE_DLR\",\"type\":\"string\"},{\"name\":\"NUM_CMPGN\",\"type\":\"string\"},{\"name\":\"ID_FIN\",\"type\":\"string\"},{\"name\":\"CDE_CTRY\",\"type\":\"string\"},{\"name\":\"CDE_CMPGN_TYP\",\"type\":\"string\"},{\"name\":\"CDE_DLR_ASGMT_RULE\",\"type\":\"string\"},{\"name\":\"DTE_VEH_GRND\",\"type\":\"string\"},{\"name\":\"IND_VEH_LNCH\",\"type\":\"string\"},{\"name\":\"IND_VEH_CA\",\"type\":\"string\"},{\"name\":\"DTS_CREA\",\"type\":\"string\"},{\"name\":\"ID_CREA_USER\",\"type\":\"string\"},{\"name\":\"DTS_LAST_UPDT\",\"type\":\"string\"},{\"name\":\"ID_LAST_UPDT_USER\",\"type\":\"string\"},{\"name\":\"IND_OPER\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<CmpgnVehDlrAsgmtDTO> ENCODER =
      new BinaryMessageEncoder<CmpgnVehDlrAsgmtDTO>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<CmpgnVehDlrAsgmtDTO> DECODER =
      new BinaryMessageDecoder<CmpgnVehDlrAsgmtDTO>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<CmpgnVehDlrAsgmtDTO> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<CmpgnVehDlrAsgmtDTO> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<CmpgnVehDlrAsgmtDTO> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<CmpgnVehDlrAsgmtDTO>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this CmpgnVehDlrAsgmtDTO to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a CmpgnVehDlrAsgmtDTO from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a CmpgnVehDlrAsgmtDTO instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static CmpgnVehDlrAsgmtDTO fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private java.lang.CharSequence CDE_DLR;
   private java.lang.CharSequence NUM_CMPGN;
   private java.lang.CharSequence ID_FIN;
   private java.lang.CharSequence CDE_CTRY;
   private java.lang.CharSequence CDE_CMPGN_TYP;
   private java.lang.CharSequence CDE_DLR_ASGMT_RULE;
   private java.lang.CharSequence DTE_VEH_GRND;
   private java.lang.CharSequence IND_VEH_LNCH;
   private java.lang.CharSequence IND_VEH_CA;
   private java.lang.CharSequence DTS_CREA;
   private java.lang.CharSequence ID_CREA_USER;
   private java.lang.CharSequence DTS_LAST_UPDT;
   private java.lang.CharSequence ID_LAST_UPDT_USER;
   private java.lang.CharSequence IND_OPER;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public CmpgnVehDlrAsgmtDTO() {}

  /**
   * All-args constructor.
   * @param CDE_DLR The new value for CDE_DLR
   * @param NUM_CMPGN The new value for NUM_CMPGN
   * @param ID_FIN The new value for ID_FIN
   * @param CDE_CTRY The new value for CDE_CTRY
   * @param CDE_CMPGN_TYP The new value for CDE_CMPGN_TYP
   * @param CDE_DLR_ASGMT_RULE The new value for CDE_DLR_ASGMT_RULE
   * @param DTE_VEH_GRND The new value for DTE_VEH_GRND
   * @param IND_VEH_LNCH The new value for IND_VEH_LNCH
   * @param IND_VEH_CA The new value for IND_VEH_CA
   * @param DTS_CREA The new value for DTS_CREA
   * @param ID_CREA_USER The new value for ID_CREA_USER
   * @param DTS_LAST_UPDT The new value for DTS_LAST_UPDT
   * @param ID_LAST_UPDT_USER The new value for ID_LAST_UPDT_USER
   * @param IND_OPER The new value for IND_OPER
   */
  public CmpgnVehDlrAsgmtDTO(java.lang.CharSequence CDE_DLR, java.lang.CharSequence NUM_CMPGN, java.lang.CharSequence ID_FIN, java.lang.CharSequence CDE_CTRY, java.lang.CharSequence CDE_CMPGN_TYP, java.lang.CharSequence CDE_DLR_ASGMT_RULE, java.lang.CharSequence DTE_VEH_GRND, java.lang.CharSequence IND_VEH_LNCH, java.lang.CharSequence IND_VEH_CA, java.lang.CharSequence DTS_CREA, java.lang.CharSequence ID_CREA_USER, java.lang.CharSequence DTS_LAST_UPDT, java.lang.CharSequence ID_LAST_UPDT_USER, java.lang.CharSequence IND_OPER) {
    this.CDE_DLR = CDE_DLR;
    this.NUM_CMPGN = NUM_CMPGN;
    this.ID_FIN = ID_FIN;
    this.CDE_CTRY = CDE_CTRY;
    this.CDE_CMPGN_TYP = CDE_CMPGN_TYP;
    this.CDE_DLR_ASGMT_RULE = CDE_DLR_ASGMT_RULE;
    this.DTE_VEH_GRND = DTE_VEH_GRND;
    this.IND_VEH_LNCH = IND_VEH_LNCH;
    this.IND_VEH_CA = IND_VEH_CA;
    this.DTS_CREA = DTS_CREA;
    this.ID_CREA_USER = ID_CREA_USER;
    this.DTS_LAST_UPDT = DTS_LAST_UPDT;
    this.ID_LAST_UPDT_USER = ID_LAST_UPDT_USER;
    this.IND_OPER = IND_OPER;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return CDE_DLR;
    case 1: return NUM_CMPGN;
    case 2: return ID_FIN;
    case 3: return CDE_CTRY;
    case 4: return CDE_CMPGN_TYP;
    case 5: return CDE_DLR_ASGMT_RULE;
    case 6: return DTE_VEH_GRND;
    case 7: return IND_VEH_LNCH;
    case 8: return IND_VEH_CA;
    case 9: return DTS_CREA;
    case 10: return ID_CREA_USER;
    case 11: return DTS_LAST_UPDT;
    case 12: return ID_LAST_UPDT_USER;
    case 13: return IND_OPER;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: CDE_DLR = (java.lang.CharSequence)value$; break;
    case 1: NUM_CMPGN = (java.lang.CharSequence)value$; break;
    case 2: ID_FIN = (java.lang.CharSequence)value$; break;
    case 3: CDE_CTRY = (java.lang.CharSequence)value$; break;
    case 4: CDE_CMPGN_TYP = (java.lang.CharSequence)value$; break;
    case 5: CDE_DLR_ASGMT_RULE = (java.lang.CharSequence)value$; break;
    case 6: DTE_VEH_GRND = (java.lang.CharSequence)value$; break;
    case 7: IND_VEH_LNCH = (java.lang.CharSequence)value$; break;
    case 8: IND_VEH_CA = (java.lang.CharSequence)value$; break;
    case 9: DTS_CREA = (java.lang.CharSequence)value$; break;
    case 10: ID_CREA_USER = (java.lang.CharSequence)value$; break;
    case 11: DTS_LAST_UPDT = (java.lang.CharSequence)value$; break;
    case 12: ID_LAST_UPDT_USER = (java.lang.CharSequence)value$; break;
    case 13: IND_OPER = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'CDE_DLR' field.
   * @return The value of the 'CDE_DLR' field.
   */
  public java.lang.CharSequence getCDEDLR() {
    return CDE_DLR;
  }


  /**
   * Sets the value of the 'CDE_DLR' field.
   * @param value the value to set.
   */
  public void setCDEDLR(java.lang.CharSequence value) {
    this.CDE_DLR = value;
  }

  /**
   * Gets the value of the 'NUM_CMPGN' field.
   * @return The value of the 'NUM_CMPGN' field.
   */
  public java.lang.CharSequence getNUMCMPGN() {
    return NUM_CMPGN;
  }


  /**
   * Sets the value of the 'NUM_CMPGN' field.
   * @param value the value to set.
   */
  public void setNUMCMPGN(java.lang.CharSequence value) {
    this.NUM_CMPGN = value;
  }

  /**
   * Gets the value of the 'ID_FIN' field.
   * @return The value of the 'ID_FIN' field.
   */
  public java.lang.CharSequence getIDFIN() {
    return ID_FIN;
  }


  /**
   * Sets the value of the 'ID_FIN' field.
   * @param value the value to set.
   */
  public void setIDFIN(java.lang.CharSequence value) {
    this.ID_FIN = value;
  }

  /**
   * Gets the value of the 'CDE_CTRY' field.
   * @return The value of the 'CDE_CTRY' field.
   */
  public java.lang.CharSequence getCDECTRY() {
    return CDE_CTRY;
  }


  /**
   * Sets the value of the 'CDE_CTRY' field.
   * @param value the value to set.
   */
  public void setCDECTRY(java.lang.CharSequence value) {
    this.CDE_CTRY = value;
  }

  /**
   * Gets the value of the 'CDE_CMPGN_TYP' field.
   * @return The value of the 'CDE_CMPGN_TYP' field.
   */
  public java.lang.CharSequence getCDECMPGNTYP() {
    return CDE_CMPGN_TYP;
  }


  /**
   * Sets the value of the 'CDE_CMPGN_TYP' field.
   * @param value the value to set.
   */
  public void setCDECMPGNTYP(java.lang.CharSequence value) {
    this.CDE_CMPGN_TYP = value;
  }

  /**
   * Gets the value of the 'CDE_DLR_ASGMT_RULE' field.
   * @return The value of the 'CDE_DLR_ASGMT_RULE' field.
   */
  public java.lang.CharSequence getCDEDLRASGMTRULE() {
    return CDE_DLR_ASGMT_RULE;
  }


  /**
   * Sets the value of the 'CDE_DLR_ASGMT_RULE' field.
   * @param value the value to set.
   */
  public void setCDEDLRASGMTRULE(java.lang.CharSequence value) {
    this.CDE_DLR_ASGMT_RULE = value;
  }

  /**
   * Gets the value of the 'DTE_VEH_GRND' field.
   * @return The value of the 'DTE_VEH_GRND' field.
   */
  public java.lang.CharSequence getDTEVEHGRND() {
    return DTE_VEH_GRND;
  }


  /**
   * Sets the value of the 'DTE_VEH_GRND' field.
   * @param value the value to set.
   */
  public void setDTEVEHGRND(java.lang.CharSequence value) {
    this.DTE_VEH_GRND = value;
  }

  /**
   * Gets the value of the 'IND_VEH_LNCH' field.
   * @return The value of the 'IND_VEH_LNCH' field.
   */
  public java.lang.CharSequence getINDVEHLNCH() {
    return IND_VEH_LNCH;
  }


  /**
   * Sets the value of the 'IND_VEH_LNCH' field.
   * @param value the value to set.
   */
  public void setINDVEHLNCH(java.lang.CharSequence value) {
    this.IND_VEH_LNCH = value;
  }

  /**
   * Gets the value of the 'IND_VEH_CA' field.
   * @return The value of the 'IND_VEH_CA' field.
   */
  public java.lang.CharSequence getINDVEHCA() {
    return IND_VEH_CA;
  }


  /**
   * Sets the value of the 'IND_VEH_CA' field.
   * @param value the value to set.
   */
  public void setINDVEHCA(java.lang.CharSequence value) {
    this.IND_VEH_CA = value;
  }

  /**
   * Gets the value of the 'DTS_CREA' field.
   * @return The value of the 'DTS_CREA' field.
   */
  public java.lang.CharSequence getDTSCREA() {
    return DTS_CREA;
  }


  /**
   * Sets the value of the 'DTS_CREA' field.
   * @param value the value to set.
   */
  public void setDTSCREA(java.lang.CharSequence value) {
    this.DTS_CREA = value;
  }

  /**
   * Gets the value of the 'ID_CREA_USER' field.
   * @return The value of the 'ID_CREA_USER' field.
   */
  public java.lang.CharSequence getIDCREAUSER() {
    return ID_CREA_USER;
  }


  /**
   * Sets the value of the 'ID_CREA_USER' field.
   * @param value the value to set.
   */
  public void setIDCREAUSER(java.lang.CharSequence value) {
    this.ID_CREA_USER = value;
  }

  /**
   * Gets the value of the 'DTS_LAST_UPDT' field.
   * @return The value of the 'DTS_LAST_UPDT' field.
   */
  public java.lang.CharSequence getDTSLASTUPDT() {
    return DTS_LAST_UPDT;
  }


  /**
   * Sets the value of the 'DTS_LAST_UPDT' field.
   * @param value the value to set.
   */
  public void setDTSLASTUPDT(java.lang.CharSequence value) {
    this.DTS_LAST_UPDT = value;
  }

  /**
   * Gets the value of the 'ID_LAST_UPDT_USER' field.
   * @return The value of the 'ID_LAST_UPDT_USER' field.
   */
  public java.lang.CharSequence getIDLASTUPDTUSER() {
    return ID_LAST_UPDT_USER;
  }


  /**
   * Sets the value of the 'ID_LAST_UPDT_USER' field.
   * @param value the value to set.
   */
  public void setIDLASTUPDTUSER(java.lang.CharSequence value) {
    this.ID_LAST_UPDT_USER = value;
  }

  /**
   * Gets the value of the 'IND_OPER' field.
   * @return The value of the 'IND_OPER' field.
   */
  public java.lang.CharSequence getINDOPER() {
    return IND_OPER;
  }


  /**
   * Sets the value of the 'IND_OPER' field.
   * @param value the value to set.
   */
  public void setINDOPER(java.lang.CharSequence value) {
    this.IND_OPER = value;
  }

  /**
   * Creates a new CmpgnVehDlrAsgmtDTO RecordBuilder.
   * @return A new CmpgnVehDlrAsgmtDTO RecordBuilder
   */
  public static com.mbusa.avro.dto.CmpgnVehDlrAsgmtDTO.Builder newBuilder() {
    return new com.mbusa.avro.dto.CmpgnVehDlrAsgmtDTO.Builder();
  }

  /**
   * Creates a new CmpgnVehDlrAsgmtDTO RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new CmpgnVehDlrAsgmtDTO RecordBuilder
   */
  public static com.mbusa.avro.dto.CmpgnVehDlrAsgmtDTO.Builder newBuilder(com.mbusa.avro.dto.CmpgnVehDlrAsgmtDTO.Builder other) {
    if (other == null) {
      return new com.mbusa.avro.dto.CmpgnVehDlrAsgmtDTO.Builder();
    } else {
      return new com.mbusa.avro.dto.CmpgnVehDlrAsgmtDTO.Builder(other);
    }
  }

  /**
   * Creates a new CmpgnVehDlrAsgmtDTO RecordBuilder by copying an existing CmpgnVehDlrAsgmtDTO instance.
   * @param other The existing instance to copy.
   * @return A new CmpgnVehDlrAsgmtDTO RecordBuilder
   */
  public static com.mbusa.avro.dto.CmpgnVehDlrAsgmtDTO.Builder newBuilder(com.mbusa.avro.dto.CmpgnVehDlrAsgmtDTO other) {
    if (other == null) {
      return new com.mbusa.avro.dto.CmpgnVehDlrAsgmtDTO.Builder();
    } else {
      return new com.mbusa.avro.dto.CmpgnVehDlrAsgmtDTO.Builder(other);
    }
  }

  /**
   * RecordBuilder for CmpgnVehDlrAsgmtDTO instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<CmpgnVehDlrAsgmtDTO>
    implements org.apache.avro.data.RecordBuilder<CmpgnVehDlrAsgmtDTO> {

    private java.lang.CharSequence CDE_DLR;
    private java.lang.CharSequence NUM_CMPGN;
    private java.lang.CharSequence ID_FIN;
    private java.lang.CharSequence CDE_CTRY;
    private java.lang.CharSequence CDE_CMPGN_TYP;
    private java.lang.CharSequence CDE_DLR_ASGMT_RULE;
    private java.lang.CharSequence DTE_VEH_GRND;
    private java.lang.CharSequence IND_VEH_LNCH;
    private java.lang.CharSequence IND_VEH_CA;
    private java.lang.CharSequence DTS_CREA;
    private java.lang.CharSequence ID_CREA_USER;
    private java.lang.CharSequence DTS_LAST_UPDT;
    private java.lang.CharSequence ID_LAST_UPDT_USER;
    private java.lang.CharSequence IND_OPER;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.mbusa.avro.dto.CmpgnVehDlrAsgmtDTO.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.CDE_DLR)) {
        this.CDE_DLR = data().deepCopy(fields()[0].schema(), other.CDE_DLR);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.NUM_CMPGN)) {
        this.NUM_CMPGN = data().deepCopy(fields()[1].schema(), other.NUM_CMPGN);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.ID_FIN)) {
        this.ID_FIN = data().deepCopy(fields()[2].schema(), other.ID_FIN);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.CDE_CTRY)) {
        this.CDE_CTRY = data().deepCopy(fields()[3].schema(), other.CDE_CTRY);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.CDE_CMPGN_TYP)) {
        this.CDE_CMPGN_TYP = data().deepCopy(fields()[4].schema(), other.CDE_CMPGN_TYP);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.CDE_DLR_ASGMT_RULE)) {
        this.CDE_DLR_ASGMT_RULE = data().deepCopy(fields()[5].schema(), other.CDE_DLR_ASGMT_RULE);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.DTE_VEH_GRND)) {
        this.DTE_VEH_GRND = data().deepCopy(fields()[6].schema(), other.DTE_VEH_GRND);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
      if (isValidValue(fields()[7], other.IND_VEH_LNCH)) {
        this.IND_VEH_LNCH = data().deepCopy(fields()[7].schema(), other.IND_VEH_LNCH);
        fieldSetFlags()[7] = other.fieldSetFlags()[7];
      }
      if (isValidValue(fields()[8], other.IND_VEH_CA)) {
        this.IND_VEH_CA = data().deepCopy(fields()[8].schema(), other.IND_VEH_CA);
        fieldSetFlags()[8] = other.fieldSetFlags()[8];
      }
      if (isValidValue(fields()[9], other.DTS_CREA)) {
        this.DTS_CREA = data().deepCopy(fields()[9].schema(), other.DTS_CREA);
        fieldSetFlags()[9] = other.fieldSetFlags()[9];
      }
      if (isValidValue(fields()[10], other.ID_CREA_USER)) {
        this.ID_CREA_USER = data().deepCopy(fields()[10].schema(), other.ID_CREA_USER);
        fieldSetFlags()[10] = other.fieldSetFlags()[10];
      }
      if (isValidValue(fields()[11], other.DTS_LAST_UPDT)) {
        this.DTS_LAST_UPDT = data().deepCopy(fields()[11].schema(), other.DTS_LAST_UPDT);
        fieldSetFlags()[11] = other.fieldSetFlags()[11];
      }
      if (isValidValue(fields()[12], other.ID_LAST_UPDT_USER)) {
        this.ID_LAST_UPDT_USER = data().deepCopy(fields()[12].schema(), other.ID_LAST_UPDT_USER);
        fieldSetFlags()[12] = other.fieldSetFlags()[12];
      }
      if (isValidValue(fields()[13], other.IND_OPER)) {
        this.IND_OPER = data().deepCopy(fields()[13].schema(), other.IND_OPER);
        fieldSetFlags()[13] = other.fieldSetFlags()[13];
      }
    }

    /**
     * Creates a Builder by copying an existing CmpgnVehDlrAsgmtDTO instance
     * @param other The existing instance to copy.
     */
    private Builder(com.mbusa.avro.dto.CmpgnVehDlrAsgmtDTO other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.CDE_DLR)) {
        this.CDE_DLR = data().deepCopy(fields()[0].schema(), other.CDE_DLR);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.NUM_CMPGN)) {
        this.NUM_CMPGN = data().deepCopy(fields()[1].schema(), other.NUM_CMPGN);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.ID_FIN)) {
        this.ID_FIN = data().deepCopy(fields()[2].schema(), other.ID_FIN);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.CDE_CTRY)) {
        this.CDE_CTRY = data().deepCopy(fields()[3].schema(), other.CDE_CTRY);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.CDE_CMPGN_TYP)) {
        this.CDE_CMPGN_TYP = data().deepCopy(fields()[4].schema(), other.CDE_CMPGN_TYP);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.CDE_DLR_ASGMT_RULE)) {
        this.CDE_DLR_ASGMT_RULE = data().deepCopy(fields()[5].schema(), other.CDE_DLR_ASGMT_RULE);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.DTE_VEH_GRND)) {
        this.DTE_VEH_GRND = data().deepCopy(fields()[6].schema(), other.DTE_VEH_GRND);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.IND_VEH_LNCH)) {
        this.IND_VEH_LNCH = data().deepCopy(fields()[7].schema(), other.IND_VEH_LNCH);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.IND_VEH_CA)) {
        this.IND_VEH_CA = data().deepCopy(fields()[8].schema(), other.IND_VEH_CA);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.DTS_CREA)) {
        this.DTS_CREA = data().deepCopy(fields()[9].schema(), other.DTS_CREA);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.ID_CREA_USER)) {
        this.ID_CREA_USER = data().deepCopy(fields()[10].schema(), other.ID_CREA_USER);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.DTS_LAST_UPDT)) {
        this.DTS_LAST_UPDT = data().deepCopy(fields()[11].schema(), other.DTS_LAST_UPDT);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.ID_LAST_UPDT_USER)) {
        this.ID_LAST_UPDT_USER = data().deepCopy(fields()[12].schema(), other.ID_LAST_UPDT_USER);
        fieldSetFlags()[12] = true;
      }
      if (isValidValue(fields()[13], other.IND_OPER)) {
        this.IND_OPER = data().deepCopy(fields()[13].schema(), other.IND_OPER);
        fieldSetFlags()[13] = true;
      }
    }

    /**
      * Gets the value of the 'CDE_DLR' field.
      * @return The value.
      */
    public java.lang.CharSequence getCDEDLR() {
      return CDE_DLR;
    }


    /**
      * Sets the value of the 'CDE_DLR' field.
      * @param value The value of 'CDE_DLR'.
      * @return This builder.
      */
    public com.mbusa.avro.dto.CmpgnVehDlrAsgmtDTO.Builder setCDEDLR(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.CDE_DLR = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'CDE_DLR' field has been set.
      * @return True if the 'CDE_DLR' field has been set, false otherwise.
      */
    public boolean hasCDEDLR() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'CDE_DLR' field.
      * @return This builder.
      */
    public com.mbusa.avro.dto.CmpgnVehDlrAsgmtDTO.Builder clearCDEDLR() {
      CDE_DLR = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'NUM_CMPGN' field.
      * @return The value.
      */
    public java.lang.CharSequence getNUMCMPGN() {
      return NUM_CMPGN;
    }


    /**
      * Sets the value of the 'NUM_CMPGN' field.
      * @param value The value of 'NUM_CMPGN'.
      * @return This builder.
      */
    public com.mbusa.avro.dto.CmpgnVehDlrAsgmtDTO.Builder setNUMCMPGN(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.NUM_CMPGN = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'NUM_CMPGN' field has been set.
      * @return True if the 'NUM_CMPGN' field has been set, false otherwise.
      */
    public boolean hasNUMCMPGN() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'NUM_CMPGN' field.
      * @return This builder.
      */
    public com.mbusa.avro.dto.CmpgnVehDlrAsgmtDTO.Builder clearNUMCMPGN() {
      NUM_CMPGN = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'ID_FIN' field.
      * @return The value.
      */
    public java.lang.CharSequence getIDFIN() {
      return ID_FIN;
    }


    /**
      * Sets the value of the 'ID_FIN' field.
      * @param value The value of 'ID_FIN'.
      * @return This builder.
      */
    public com.mbusa.avro.dto.CmpgnVehDlrAsgmtDTO.Builder setIDFIN(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.ID_FIN = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'ID_FIN' field has been set.
      * @return True if the 'ID_FIN' field has been set, false otherwise.
      */
    public boolean hasIDFIN() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'ID_FIN' field.
      * @return This builder.
      */
    public com.mbusa.avro.dto.CmpgnVehDlrAsgmtDTO.Builder clearIDFIN() {
      ID_FIN = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'CDE_CTRY' field.
      * @return The value.
      */
    public java.lang.CharSequence getCDECTRY() {
      return CDE_CTRY;
    }


    /**
      * Sets the value of the 'CDE_CTRY' field.
      * @param value The value of 'CDE_CTRY'.
      * @return This builder.
      */
    public com.mbusa.avro.dto.CmpgnVehDlrAsgmtDTO.Builder setCDECTRY(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.CDE_CTRY = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'CDE_CTRY' field has been set.
      * @return True if the 'CDE_CTRY' field has been set, false otherwise.
      */
    public boolean hasCDECTRY() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'CDE_CTRY' field.
      * @return This builder.
      */
    public com.mbusa.avro.dto.CmpgnVehDlrAsgmtDTO.Builder clearCDECTRY() {
      CDE_CTRY = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'CDE_CMPGN_TYP' field.
      * @return The value.
      */
    public java.lang.CharSequence getCDECMPGNTYP() {
      return CDE_CMPGN_TYP;
    }


    /**
      * Sets the value of the 'CDE_CMPGN_TYP' field.
      * @param value The value of 'CDE_CMPGN_TYP'.
      * @return This builder.
      */
    public com.mbusa.avro.dto.CmpgnVehDlrAsgmtDTO.Builder setCDECMPGNTYP(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.CDE_CMPGN_TYP = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'CDE_CMPGN_TYP' field has been set.
      * @return True if the 'CDE_CMPGN_TYP' field has been set, false otherwise.
      */
    public boolean hasCDECMPGNTYP() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'CDE_CMPGN_TYP' field.
      * @return This builder.
      */
    public com.mbusa.avro.dto.CmpgnVehDlrAsgmtDTO.Builder clearCDECMPGNTYP() {
      CDE_CMPGN_TYP = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'CDE_DLR_ASGMT_RULE' field.
      * @return The value.
      */
    public java.lang.CharSequence getCDEDLRASGMTRULE() {
      return CDE_DLR_ASGMT_RULE;
    }


    /**
      * Sets the value of the 'CDE_DLR_ASGMT_RULE' field.
      * @param value The value of 'CDE_DLR_ASGMT_RULE'.
      * @return This builder.
      */
    public com.mbusa.avro.dto.CmpgnVehDlrAsgmtDTO.Builder setCDEDLRASGMTRULE(java.lang.CharSequence value) {
      validate(fields()[5], value);
      this.CDE_DLR_ASGMT_RULE = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'CDE_DLR_ASGMT_RULE' field has been set.
      * @return True if the 'CDE_DLR_ASGMT_RULE' field has been set, false otherwise.
      */
    public boolean hasCDEDLRASGMTRULE() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'CDE_DLR_ASGMT_RULE' field.
      * @return This builder.
      */
    public com.mbusa.avro.dto.CmpgnVehDlrAsgmtDTO.Builder clearCDEDLRASGMTRULE() {
      CDE_DLR_ASGMT_RULE = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'DTE_VEH_GRND' field.
      * @return The value.
      */
    public java.lang.CharSequence getDTEVEHGRND() {
      return DTE_VEH_GRND;
    }


    /**
      * Sets the value of the 'DTE_VEH_GRND' field.
      * @param value The value of 'DTE_VEH_GRND'.
      * @return This builder.
      */
    public com.mbusa.avro.dto.CmpgnVehDlrAsgmtDTO.Builder setDTEVEHGRND(java.lang.CharSequence value) {
      validate(fields()[6], value);
      this.DTE_VEH_GRND = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'DTE_VEH_GRND' field has been set.
      * @return True if the 'DTE_VEH_GRND' field has been set, false otherwise.
      */
    public boolean hasDTEVEHGRND() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'DTE_VEH_GRND' field.
      * @return This builder.
      */
    public com.mbusa.avro.dto.CmpgnVehDlrAsgmtDTO.Builder clearDTEVEHGRND() {
      DTE_VEH_GRND = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'IND_VEH_LNCH' field.
      * @return The value.
      */
    public java.lang.CharSequence getINDVEHLNCH() {
      return IND_VEH_LNCH;
    }


    /**
      * Sets the value of the 'IND_VEH_LNCH' field.
      * @param value The value of 'IND_VEH_LNCH'.
      * @return This builder.
      */
    public com.mbusa.avro.dto.CmpgnVehDlrAsgmtDTO.Builder setINDVEHLNCH(java.lang.CharSequence value) {
      validate(fields()[7], value);
      this.IND_VEH_LNCH = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'IND_VEH_LNCH' field has been set.
      * @return True if the 'IND_VEH_LNCH' field has been set, false otherwise.
      */
    public boolean hasINDVEHLNCH() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'IND_VEH_LNCH' field.
      * @return This builder.
      */
    public com.mbusa.avro.dto.CmpgnVehDlrAsgmtDTO.Builder clearINDVEHLNCH() {
      IND_VEH_LNCH = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    /**
      * Gets the value of the 'IND_VEH_CA' field.
      * @return The value.
      */
    public java.lang.CharSequence getINDVEHCA() {
      return IND_VEH_CA;
    }


    /**
      * Sets the value of the 'IND_VEH_CA' field.
      * @param value The value of 'IND_VEH_CA'.
      * @return This builder.
      */
    public com.mbusa.avro.dto.CmpgnVehDlrAsgmtDTO.Builder setINDVEHCA(java.lang.CharSequence value) {
      validate(fields()[8], value);
      this.IND_VEH_CA = value;
      fieldSetFlags()[8] = true;
      return this;
    }

    /**
      * Checks whether the 'IND_VEH_CA' field has been set.
      * @return True if the 'IND_VEH_CA' field has been set, false otherwise.
      */
    public boolean hasINDVEHCA() {
      return fieldSetFlags()[8];
    }


    /**
      * Clears the value of the 'IND_VEH_CA' field.
      * @return This builder.
      */
    public com.mbusa.avro.dto.CmpgnVehDlrAsgmtDTO.Builder clearINDVEHCA() {
      IND_VEH_CA = null;
      fieldSetFlags()[8] = false;
      return this;
    }

    /**
      * Gets the value of the 'DTS_CREA' field.
      * @return The value.
      */
    public java.lang.CharSequence getDTSCREA() {
      return DTS_CREA;
    }


    /**
      * Sets the value of the 'DTS_CREA' field.
      * @param value The value of 'DTS_CREA'.
      * @return This builder.
      */
    public com.mbusa.avro.dto.CmpgnVehDlrAsgmtDTO.Builder setDTSCREA(java.lang.CharSequence value) {
      validate(fields()[9], value);
      this.DTS_CREA = value;
      fieldSetFlags()[9] = true;
      return this;
    }

    /**
      * Checks whether the 'DTS_CREA' field has been set.
      * @return True if the 'DTS_CREA' field has been set, false otherwise.
      */
    public boolean hasDTSCREA() {
      return fieldSetFlags()[9];
    }


    /**
      * Clears the value of the 'DTS_CREA' field.
      * @return This builder.
      */
    public com.mbusa.avro.dto.CmpgnVehDlrAsgmtDTO.Builder clearDTSCREA() {
      DTS_CREA = null;
      fieldSetFlags()[9] = false;
      return this;
    }

    /**
      * Gets the value of the 'ID_CREA_USER' field.
      * @return The value.
      */
    public java.lang.CharSequence getIDCREAUSER() {
      return ID_CREA_USER;
    }


    /**
      * Sets the value of the 'ID_CREA_USER' field.
      * @param value The value of 'ID_CREA_USER'.
      * @return This builder.
      */
    public com.mbusa.avro.dto.CmpgnVehDlrAsgmtDTO.Builder setIDCREAUSER(java.lang.CharSequence value) {
      validate(fields()[10], value);
      this.ID_CREA_USER = value;
      fieldSetFlags()[10] = true;
      return this;
    }

    /**
      * Checks whether the 'ID_CREA_USER' field has been set.
      * @return True if the 'ID_CREA_USER' field has been set, false otherwise.
      */
    public boolean hasIDCREAUSER() {
      return fieldSetFlags()[10];
    }


    /**
      * Clears the value of the 'ID_CREA_USER' field.
      * @return This builder.
      */
    public com.mbusa.avro.dto.CmpgnVehDlrAsgmtDTO.Builder clearIDCREAUSER() {
      ID_CREA_USER = null;
      fieldSetFlags()[10] = false;
      return this;
    }

    /**
      * Gets the value of the 'DTS_LAST_UPDT' field.
      * @return The value.
      */
    public java.lang.CharSequence getDTSLASTUPDT() {
      return DTS_LAST_UPDT;
    }


    /**
      * Sets the value of the 'DTS_LAST_UPDT' field.
      * @param value The value of 'DTS_LAST_UPDT'.
      * @return This builder.
      */
    public com.mbusa.avro.dto.CmpgnVehDlrAsgmtDTO.Builder setDTSLASTUPDT(java.lang.CharSequence value) {
      validate(fields()[11], value);
      this.DTS_LAST_UPDT = value;
      fieldSetFlags()[11] = true;
      return this;
    }

    /**
      * Checks whether the 'DTS_LAST_UPDT' field has been set.
      * @return True if the 'DTS_LAST_UPDT' field has been set, false otherwise.
      */
    public boolean hasDTSLASTUPDT() {
      return fieldSetFlags()[11];
    }


    /**
      * Clears the value of the 'DTS_LAST_UPDT' field.
      * @return This builder.
      */
    public com.mbusa.avro.dto.CmpgnVehDlrAsgmtDTO.Builder clearDTSLASTUPDT() {
      DTS_LAST_UPDT = null;
      fieldSetFlags()[11] = false;
      return this;
    }

    /**
      * Gets the value of the 'ID_LAST_UPDT_USER' field.
      * @return The value.
      */
    public java.lang.CharSequence getIDLASTUPDTUSER() {
      return ID_LAST_UPDT_USER;
    }


    /**
      * Sets the value of the 'ID_LAST_UPDT_USER' field.
      * @param value The value of 'ID_LAST_UPDT_USER'.
      * @return This builder.
      */
    public com.mbusa.avro.dto.CmpgnVehDlrAsgmtDTO.Builder setIDLASTUPDTUSER(java.lang.CharSequence value) {
      validate(fields()[12], value);
      this.ID_LAST_UPDT_USER = value;
      fieldSetFlags()[12] = true;
      return this;
    }

    /**
      * Checks whether the 'ID_LAST_UPDT_USER' field has been set.
      * @return True if the 'ID_LAST_UPDT_USER' field has been set, false otherwise.
      */
    public boolean hasIDLASTUPDTUSER() {
      return fieldSetFlags()[12];
    }


    /**
      * Clears the value of the 'ID_LAST_UPDT_USER' field.
      * @return This builder.
      */
    public com.mbusa.avro.dto.CmpgnVehDlrAsgmtDTO.Builder clearIDLASTUPDTUSER() {
      ID_LAST_UPDT_USER = null;
      fieldSetFlags()[12] = false;
      return this;
    }

    /**
      * Gets the value of the 'IND_OPER' field.
      * @return The value.
      */
    public java.lang.CharSequence getINDOPER() {
      return IND_OPER;
    }


    /**
      * Sets the value of the 'IND_OPER' field.
      * @param value The value of 'IND_OPER'.
      * @return This builder.
      */
    public com.mbusa.avro.dto.CmpgnVehDlrAsgmtDTO.Builder setINDOPER(java.lang.CharSequence value) {
      validate(fields()[13], value);
      this.IND_OPER = value;
      fieldSetFlags()[13] = true;
      return this;
    }

    /**
      * Checks whether the 'IND_OPER' field has been set.
      * @return True if the 'IND_OPER' field has been set, false otherwise.
      */
    public boolean hasINDOPER() {
      return fieldSetFlags()[13];
    }


    /**
      * Clears the value of the 'IND_OPER' field.
      * @return This builder.
      */
    public com.mbusa.avro.dto.CmpgnVehDlrAsgmtDTO.Builder clearINDOPER() {
      IND_OPER = null;
      fieldSetFlags()[13] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public CmpgnVehDlrAsgmtDTO build() {
      try {
        CmpgnVehDlrAsgmtDTO record = new CmpgnVehDlrAsgmtDTO();
        record.CDE_DLR = fieldSetFlags()[0] ? this.CDE_DLR : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.NUM_CMPGN = fieldSetFlags()[1] ? this.NUM_CMPGN : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.ID_FIN = fieldSetFlags()[2] ? this.ID_FIN : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.CDE_CTRY = fieldSetFlags()[3] ? this.CDE_CTRY : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.CDE_CMPGN_TYP = fieldSetFlags()[4] ? this.CDE_CMPGN_TYP : (java.lang.CharSequence) defaultValue(fields()[4]);
        record.CDE_DLR_ASGMT_RULE = fieldSetFlags()[5] ? this.CDE_DLR_ASGMT_RULE : (java.lang.CharSequence) defaultValue(fields()[5]);
        record.DTE_VEH_GRND = fieldSetFlags()[6] ? this.DTE_VEH_GRND : (java.lang.CharSequence) defaultValue(fields()[6]);
        record.IND_VEH_LNCH = fieldSetFlags()[7] ? this.IND_VEH_LNCH : (java.lang.CharSequence) defaultValue(fields()[7]);
        record.IND_VEH_CA = fieldSetFlags()[8] ? this.IND_VEH_CA : (java.lang.CharSequence) defaultValue(fields()[8]);
        record.DTS_CREA = fieldSetFlags()[9] ? this.DTS_CREA : (java.lang.CharSequence) defaultValue(fields()[9]);
        record.ID_CREA_USER = fieldSetFlags()[10] ? this.ID_CREA_USER : (java.lang.CharSequence) defaultValue(fields()[10]);
        record.DTS_LAST_UPDT = fieldSetFlags()[11] ? this.DTS_LAST_UPDT : (java.lang.CharSequence) defaultValue(fields()[11]);
        record.ID_LAST_UPDT_USER = fieldSetFlags()[12] ? this.ID_LAST_UPDT_USER : (java.lang.CharSequence) defaultValue(fields()[12]);
        record.IND_OPER = fieldSetFlags()[13] ? this.IND_OPER : (java.lang.CharSequence) defaultValue(fields()[13]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<CmpgnVehDlrAsgmtDTO>
    WRITER$ = (org.apache.avro.io.DatumWriter<CmpgnVehDlrAsgmtDTO>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<CmpgnVehDlrAsgmtDTO>
    READER$ = (org.apache.avro.io.DatumReader<CmpgnVehDlrAsgmtDTO>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.CDE_DLR);

    out.writeString(this.NUM_CMPGN);

    out.writeString(this.ID_FIN);

    out.writeString(this.CDE_CTRY);

    out.writeString(this.CDE_CMPGN_TYP);

    out.writeString(this.CDE_DLR_ASGMT_RULE);

    out.writeString(this.DTE_VEH_GRND);

    out.writeString(this.IND_VEH_LNCH);

    out.writeString(this.IND_VEH_CA);

    out.writeString(this.DTS_CREA);

    out.writeString(this.ID_CREA_USER);

    out.writeString(this.DTS_LAST_UPDT);

    out.writeString(this.ID_LAST_UPDT_USER);

    out.writeString(this.IND_OPER);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.CDE_DLR = in.readString(this.CDE_DLR instanceof Utf8 ? (Utf8)this.CDE_DLR : null);

      this.NUM_CMPGN = in.readString(this.NUM_CMPGN instanceof Utf8 ? (Utf8)this.NUM_CMPGN : null);

      this.ID_FIN = in.readString(this.ID_FIN instanceof Utf8 ? (Utf8)this.ID_FIN : null);

      this.CDE_CTRY = in.readString(this.CDE_CTRY instanceof Utf8 ? (Utf8)this.CDE_CTRY : null);

      this.CDE_CMPGN_TYP = in.readString(this.CDE_CMPGN_TYP instanceof Utf8 ? (Utf8)this.CDE_CMPGN_TYP : null);

      this.CDE_DLR_ASGMT_RULE = in.readString(this.CDE_DLR_ASGMT_RULE instanceof Utf8 ? (Utf8)this.CDE_DLR_ASGMT_RULE : null);

      this.DTE_VEH_GRND = in.readString(this.DTE_VEH_GRND instanceof Utf8 ? (Utf8)this.DTE_VEH_GRND : null);

      this.IND_VEH_LNCH = in.readString(this.IND_VEH_LNCH instanceof Utf8 ? (Utf8)this.IND_VEH_LNCH : null);

      this.IND_VEH_CA = in.readString(this.IND_VEH_CA instanceof Utf8 ? (Utf8)this.IND_VEH_CA : null);

      this.DTS_CREA = in.readString(this.DTS_CREA instanceof Utf8 ? (Utf8)this.DTS_CREA : null);

      this.ID_CREA_USER = in.readString(this.ID_CREA_USER instanceof Utf8 ? (Utf8)this.ID_CREA_USER : null);

      this.DTS_LAST_UPDT = in.readString(this.DTS_LAST_UPDT instanceof Utf8 ? (Utf8)this.DTS_LAST_UPDT : null);

      this.ID_LAST_UPDT_USER = in.readString(this.ID_LAST_UPDT_USER instanceof Utf8 ? (Utf8)this.ID_LAST_UPDT_USER : null);

      this.IND_OPER = in.readString(this.IND_OPER instanceof Utf8 ? (Utf8)this.IND_OPER : null);

    } else {
      for (int i = 0; i < 14; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.CDE_DLR = in.readString(this.CDE_DLR instanceof Utf8 ? (Utf8)this.CDE_DLR : null);
          break;

        case 1:
          this.NUM_CMPGN = in.readString(this.NUM_CMPGN instanceof Utf8 ? (Utf8)this.NUM_CMPGN : null);
          break;

        case 2:
          this.ID_FIN = in.readString(this.ID_FIN instanceof Utf8 ? (Utf8)this.ID_FIN : null);
          break;

        case 3:
          this.CDE_CTRY = in.readString(this.CDE_CTRY instanceof Utf8 ? (Utf8)this.CDE_CTRY : null);
          break;

        case 4:
          this.CDE_CMPGN_TYP = in.readString(this.CDE_CMPGN_TYP instanceof Utf8 ? (Utf8)this.CDE_CMPGN_TYP : null);
          break;

        case 5:
          this.CDE_DLR_ASGMT_RULE = in.readString(this.CDE_DLR_ASGMT_RULE instanceof Utf8 ? (Utf8)this.CDE_DLR_ASGMT_RULE : null);
          break;

        case 6:
          this.DTE_VEH_GRND = in.readString(this.DTE_VEH_GRND instanceof Utf8 ? (Utf8)this.DTE_VEH_GRND : null);
          break;

        case 7:
          this.IND_VEH_LNCH = in.readString(this.IND_VEH_LNCH instanceof Utf8 ? (Utf8)this.IND_VEH_LNCH : null);
          break;

        case 8:
          this.IND_VEH_CA = in.readString(this.IND_VEH_CA instanceof Utf8 ? (Utf8)this.IND_VEH_CA : null);
          break;

        case 9:
          this.DTS_CREA = in.readString(this.DTS_CREA instanceof Utf8 ? (Utf8)this.DTS_CREA : null);
          break;

        case 10:
          this.ID_CREA_USER = in.readString(this.ID_CREA_USER instanceof Utf8 ? (Utf8)this.ID_CREA_USER : null);
          break;

        case 11:
          this.DTS_LAST_UPDT = in.readString(this.DTS_LAST_UPDT instanceof Utf8 ? (Utf8)this.DTS_LAST_UPDT : null);
          break;

        case 12:
          this.ID_LAST_UPDT_USER = in.readString(this.ID_LAST_UPDT_USER instanceof Utf8 ? (Utf8)this.ID_LAST_UPDT_USER : null);
          break;

        case 13:
          this.IND_OPER = in.readString(this.IND_OPER instanceof Utf8 ? (Utf8)this.IND_OPER : null);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










