/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.mbusa.avro.dto;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class CmpgnCustVehDTO extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 4525507567525028286L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"CmpgnCustVehDTO\",\"namespace\":\"com.mbusa.avro.dto\",\"fields\":[{\"name\":\"ID_CUST\",\"type\":\"string\"},{\"name\":\"ID_FIN\",\"type\":\"string\"},{\"name\":\"DTE_STRT\",\"type\":\"string\"},{\"name\":\"DTE_END\",\"type\":\"string\"},{\"name\":\"IND_CUST_SRC_VEND\",\"type\":\"string\"},{\"name\":\"IND_VIO\",\"type\":\"string\"},{\"name\":\"NUM_VEH_LIC_PLT\",\"type\":\"string\"},{\"name\":\"DTE_VEH_RGS\",\"type\":\"string\"},{\"name\":\"DTE_SRC_RCD_UPDT\",\"type\":\"string\"},{\"name\":\"TME_SRC_RCD_UPDT\",\"type\":\"string\"},{\"name\":\"ID_SRC_RCD_UPDT_USER\",\"type\":\"string\"},{\"name\":\"CDE_SELL_DLR\",\"type\":\"string\"},{\"name\":\"DTS_CREA\",\"type\":\"string\"},{\"name\":\"ID_CREA_USER\",\"type\":\"string\"},{\"name\":\"DTS_LAST_UPDT\",\"type\":\"string\"},{\"name\":\"ID_LAST_UPDT_USER\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<CmpgnCustVehDTO> ENCODER =
      new BinaryMessageEncoder<CmpgnCustVehDTO>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<CmpgnCustVehDTO> DECODER =
      new BinaryMessageDecoder<CmpgnCustVehDTO>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<CmpgnCustVehDTO> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<CmpgnCustVehDTO> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<CmpgnCustVehDTO> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<CmpgnCustVehDTO>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this CmpgnCustVehDTO to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a CmpgnCustVehDTO from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a CmpgnCustVehDTO instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static CmpgnCustVehDTO fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private java.lang.CharSequence ID_CUST;
   private java.lang.CharSequence ID_FIN;
   private java.lang.CharSequence DTE_STRT;
   private java.lang.CharSequence DTE_END;
   private java.lang.CharSequence IND_CUST_SRC_VEND;
   private java.lang.CharSequence IND_VIO;
   private java.lang.CharSequence NUM_VEH_LIC_PLT;
   private java.lang.CharSequence DTE_VEH_RGS;
   private java.lang.CharSequence DTE_SRC_RCD_UPDT;
   private java.lang.CharSequence TME_SRC_RCD_UPDT;
   private java.lang.CharSequence ID_SRC_RCD_UPDT_USER;
   private java.lang.CharSequence CDE_SELL_DLR;
   private java.lang.CharSequence DTS_CREA;
   private java.lang.CharSequence ID_CREA_USER;
   private java.lang.CharSequence DTS_LAST_UPDT;
   private java.lang.CharSequence ID_LAST_UPDT_USER;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public CmpgnCustVehDTO() {}

  /**
   * All-args constructor.
   * @param ID_CUST The new value for ID_CUST
   * @param ID_FIN The new value for ID_FIN
   * @param DTE_STRT The new value for DTE_STRT
   * @param DTE_END The new value for DTE_END
   * @param IND_CUST_SRC_VEND The new value for IND_CUST_SRC_VEND
   * @param IND_VIO The new value for IND_VIO
   * @param NUM_VEH_LIC_PLT The new value for NUM_VEH_LIC_PLT
   * @param DTE_VEH_RGS The new value for DTE_VEH_RGS
   * @param DTE_SRC_RCD_UPDT The new value for DTE_SRC_RCD_UPDT
   * @param TME_SRC_RCD_UPDT The new value for TME_SRC_RCD_UPDT
   * @param ID_SRC_RCD_UPDT_USER The new value for ID_SRC_RCD_UPDT_USER
   * @param CDE_SELL_DLR The new value for CDE_SELL_DLR
   * @param DTS_CREA The new value for DTS_CREA
   * @param ID_CREA_USER The new value for ID_CREA_USER
   * @param DTS_LAST_UPDT The new value for DTS_LAST_UPDT
   * @param ID_LAST_UPDT_USER The new value for ID_LAST_UPDT_USER
   */
  public CmpgnCustVehDTO(java.lang.CharSequence ID_CUST, java.lang.CharSequence ID_FIN, java.lang.CharSequence DTE_STRT, java.lang.CharSequence DTE_END, java.lang.CharSequence IND_CUST_SRC_VEND, java.lang.CharSequence IND_VIO, java.lang.CharSequence NUM_VEH_LIC_PLT, java.lang.CharSequence DTE_VEH_RGS, java.lang.CharSequence DTE_SRC_RCD_UPDT, java.lang.CharSequence TME_SRC_RCD_UPDT, java.lang.CharSequence ID_SRC_RCD_UPDT_USER, java.lang.CharSequence CDE_SELL_DLR, java.lang.CharSequence DTS_CREA, java.lang.CharSequence ID_CREA_USER, java.lang.CharSequence DTS_LAST_UPDT, java.lang.CharSequence ID_LAST_UPDT_USER) {
    this.ID_CUST = ID_CUST;
    this.ID_FIN = ID_FIN;
    this.DTE_STRT = DTE_STRT;
    this.DTE_END = DTE_END;
    this.IND_CUST_SRC_VEND = IND_CUST_SRC_VEND;
    this.IND_VIO = IND_VIO;
    this.NUM_VEH_LIC_PLT = NUM_VEH_LIC_PLT;
    this.DTE_VEH_RGS = DTE_VEH_RGS;
    this.DTE_SRC_RCD_UPDT = DTE_SRC_RCD_UPDT;
    this.TME_SRC_RCD_UPDT = TME_SRC_RCD_UPDT;
    this.ID_SRC_RCD_UPDT_USER = ID_SRC_RCD_UPDT_USER;
    this.CDE_SELL_DLR = CDE_SELL_DLR;
    this.DTS_CREA = DTS_CREA;
    this.ID_CREA_USER = ID_CREA_USER;
    this.DTS_LAST_UPDT = DTS_LAST_UPDT;
    this.ID_LAST_UPDT_USER = ID_LAST_UPDT_USER;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return ID_CUST;
    case 1: return ID_FIN;
    case 2: return DTE_STRT;
    case 3: return DTE_END;
    case 4: return IND_CUST_SRC_VEND;
    case 5: return IND_VIO;
    case 6: return NUM_VEH_LIC_PLT;
    case 7: return DTE_VEH_RGS;
    case 8: return DTE_SRC_RCD_UPDT;
    case 9: return TME_SRC_RCD_UPDT;
    case 10: return ID_SRC_RCD_UPDT_USER;
    case 11: return CDE_SELL_DLR;
    case 12: return DTS_CREA;
    case 13: return ID_CREA_USER;
    case 14: return DTS_LAST_UPDT;
    case 15: return ID_LAST_UPDT_USER;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: ID_CUST = (java.lang.CharSequence)value$; break;
    case 1: ID_FIN = (java.lang.CharSequence)value$; break;
    case 2: DTE_STRT = (java.lang.CharSequence)value$; break;
    case 3: DTE_END = (java.lang.CharSequence)value$; break;
    case 4: IND_CUST_SRC_VEND = (java.lang.CharSequence)value$; break;
    case 5: IND_VIO = (java.lang.CharSequence)value$; break;
    case 6: NUM_VEH_LIC_PLT = (java.lang.CharSequence)value$; break;
    case 7: DTE_VEH_RGS = (java.lang.CharSequence)value$; break;
    case 8: DTE_SRC_RCD_UPDT = (java.lang.CharSequence)value$; break;
    case 9: TME_SRC_RCD_UPDT = (java.lang.CharSequence)value$; break;
    case 10: ID_SRC_RCD_UPDT_USER = (java.lang.CharSequence)value$; break;
    case 11: CDE_SELL_DLR = (java.lang.CharSequence)value$; break;
    case 12: DTS_CREA = (java.lang.CharSequence)value$; break;
    case 13: ID_CREA_USER = (java.lang.CharSequence)value$; break;
    case 14: DTS_LAST_UPDT = (java.lang.CharSequence)value$; break;
    case 15: ID_LAST_UPDT_USER = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'ID_CUST' field.
   * @return The value of the 'ID_CUST' field.
   */
  public java.lang.CharSequence getIDCUST() {
    return ID_CUST;
  }


  /**
   * Sets the value of the 'ID_CUST' field.
   * @param value the value to set.
   */
  public void setIDCUST(java.lang.CharSequence value) {
    this.ID_CUST = value;
  }

  /**
   * Gets the value of the 'ID_FIN' field.
   * @return The value of the 'ID_FIN' field.
   */
  public java.lang.CharSequence getIDFIN() {
    return ID_FIN;
  }


  /**
   * Sets the value of the 'ID_FIN' field.
   * @param value the value to set.
   */
  public void setIDFIN(java.lang.CharSequence value) {
    this.ID_FIN = value;
  }

  /**
   * Gets the value of the 'DTE_STRT' field.
   * @return The value of the 'DTE_STRT' field.
   */
  public java.lang.CharSequence getDTESTRT() {
    return DTE_STRT;
  }


  /**
   * Sets the value of the 'DTE_STRT' field.
   * @param value the value to set.
   */
  public void setDTESTRT(java.lang.CharSequence value) {
    this.DTE_STRT = value;
  }

  /**
   * Gets the value of the 'DTE_END' field.
   * @return The value of the 'DTE_END' field.
   */
  public java.lang.CharSequence getDTEEND() {
    return DTE_END;
  }


  /**
   * Sets the value of the 'DTE_END' field.
   * @param value the value to set.
   */
  public void setDTEEND(java.lang.CharSequence value) {
    this.DTE_END = value;
  }

  /**
   * Gets the value of the 'IND_CUST_SRC_VEND' field.
   * @return The value of the 'IND_CUST_SRC_VEND' field.
   */
  public java.lang.CharSequence getINDCUSTSRCVEND() {
    return IND_CUST_SRC_VEND;
  }


  /**
   * Sets the value of the 'IND_CUST_SRC_VEND' field.
   * @param value the value to set.
   */
  public void setINDCUSTSRCVEND(java.lang.CharSequence value) {
    this.IND_CUST_SRC_VEND = value;
  }

  /**
   * Gets the value of the 'IND_VIO' field.
   * @return The value of the 'IND_VIO' field.
   */
  public java.lang.CharSequence getINDVIO() {
    return IND_VIO;
  }


  /**
   * Sets the value of the 'IND_VIO' field.
   * @param value the value to set.
   */
  public void setINDVIO(java.lang.CharSequence value) {
    this.IND_VIO = value;
  }

  /**
   * Gets the value of the 'NUM_VEH_LIC_PLT' field.
   * @return The value of the 'NUM_VEH_LIC_PLT' field.
   */
  public java.lang.CharSequence getNUMVEHLICPLT() {
    return NUM_VEH_LIC_PLT;
  }


  /**
   * Sets the value of the 'NUM_VEH_LIC_PLT' field.
   * @param value the value to set.
   */
  public void setNUMVEHLICPLT(java.lang.CharSequence value) {
    this.NUM_VEH_LIC_PLT = value;
  }

  /**
   * Gets the value of the 'DTE_VEH_RGS' field.
   * @return The value of the 'DTE_VEH_RGS' field.
   */
  public java.lang.CharSequence getDTEVEHRGS() {
    return DTE_VEH_RGS;
  }


  /**
   * Sets the value of the 'DTE_VEH_RGS' field.
   * @param value the value to set.
   */
  public void setDTEVEHRGS(java.lang.CharSequence value) {
    this.DTE_VEH_RGS = value;
  }

  /**
   * Gets the value of the 'DTE_SRC_RCD_UPDT' field.
   * @return The value of the 'DTE_SRC_RCD_UPDT' field.
   */
  public java.lang.CharSequence getDTESRCRCDUPDT() {
    return DTE_SRC_RCD_UPDT;
  }


  /**
   * Sets the value of the 'DTE_SRC_RCD_UPDT' field.
   * @param value the value to set.
   */
  public void setDTESRCRCDUPDT(java.lang.CharSequence value) {
    this.DTE_SRC_RCD_UPDT = value;
  }

  /**
   * Gets the value of the 'TME_SRC_RCD_UPDT' field.
   * @return The value of the 'TME_SRC_RCD_UPDT' field.
   */
  public java.lang.CharSequence getTMESRCRCDUPDT() {
    return TME_SRC_RCD_UPDT;
  }


  /**
   * Sets the value of the 'TME_SRC_RCD_UPDT' field.
   * @param value the value to set.
   */
  public void setTMESRCRCDUPDT(java.lang.CharSequence value) {
    this.TME_SRC_RCD_UPDT = value;
  }

  /**
   * Gets the value of the 'ID_SRC_RCD_UPDT_USER' field.
   * @return The value of the 'ID_SRC_RCD_UPDT_USER' field.
   */
  public java.lang.CharSequence getIDSRCRCDUPDTUSER() {
    return ID_SRC_RCD_UPDT_USER;
  }


  /**
   * Sets the value of the 'ID_SRC_RCD_UPDT_USER' field.
   * @param value the value to set.
   */
  public void setIDSRCRCDUPDTUSER(java.lang.CharSequence value) {
    this.ID_SRC_RCD_UPDT_USER = value;
  }

  /**
   * Gets the value of the 'CDE_SELL_DLR' field.
   * @return The value of the 'CDE_SELL_DLR' field.
   */
  public java.lang.CharSequence getCDESELLDLR() {
    return CDE_SELL_DLR;
  }


  /**
   * Sets the value of the 'CDE_SELL_DLR' field.
   * @param value the value to set.
   */
  public void setCDESELLDLR(java.lang.CharSequence value) {
    this.CDE_SELL_DLR = value;
  }

  /**
   * Gets the value of the 'DTS_CREA' field.
   * @return The value of the 'DTS_CREA' field.
   */
  public java.lang.CharSequence getDTSCREA() {
    return DTS_CREA;
  }


  /**
   * Sets the value of the 'DTS_CREA' field.
   * @param value the value to set.
   */
  public void setDTSCREA(java.lang.CharSequence value) {
    this.DTS_CREA = value;
  }

  /**
   * Gets the value of the 'ID_CREA_USER' field.
   * @return The value of the 'ID_CREA_USER' field.
   */
  public java.lang.CharSequence getIDCREAUSER() {
    return ID_CREA_USER;
  }


  /**
   * Sets the value of the 'ID_CREA_USER' field.
   * @param value the value to set.
   */
  public void setIDCREAUSER(java.lang.CharSequence value) {
    this.ID_CREA_USER = value;
  }

  /**
   * Gets the value of the 'DTS_LAST_UPDT' field.
   * @return The value of the 'DTS_LAST_UPDT' field.
   */
  public java.lang.CharSequence getDTSLASTUPDT() {
    return DTS_LAST_UPDT;
  }


  /**
   * Sets the value of the 'DTS_LAST_UPDT' field.
   * @param value the value to set.
   */
  public void setDTSLASTUPDT(java.lang.CharSequence value) {
    this.DTS_LAST_UPDT = value;
  }

  /**
   * Gets the value of the 'ID_LAST_UPDT_USER' field.
   * @return The value of the 'ID_LAST_UPDT_USER' field.
   */
  public java.lang.CharSequence getIDLASTUPDTUSER() {
    return ID_LAST_UPDT_USER;
  }


  /**
   * Sets the value of the 'ID_LAST_UPDT_USER' field.
   * @param value the value to set.
   */
  public void setIDLASTUPDTUSER(java.lang.CharSequence value) {
    this.ID_LAST_UPDT_USER = value;
  }

  /**
   * Creates a new CmpgnCustVehDTO RecordBuilder.
   * @return A new CmpgnCustVehDTO RecordBuilder
   */
  public static com.mbusa.avro.dto.CmpgnCustVehDTO.Builder newBuilder() {
    return new com.mbusa.avro.dto.CmpgnCustVehDTO.Builder();
  }

  /**
   * Creates a new CmpgnCustVehDTO RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new CmpgnCustVehDTO RecordBuilder
   */
  public static com.mbusa.avro.dto.CmpgnCustVehDTO.Builder newBuilder(com.mbusa.avro.dto.CmpgnCustVehDTO.Builder other) {
    if (other == null) {
      return new com.mbusa.avro.dto.CmpgnCustVehDTO.Builder();
    } else {
      return new com.mbusa.avro.dto.CmpgnCustVehDTO.Builder(other);
    }
  }

  /**
   * Creates a new CmpgnCustVehDTO RecordBuilder by copying an existing CmpgnCustVehDTO instance.
   * @param other The existing instance to copy.
   * @return A new CmpgnCustVehDTO RecordBuilder
   */
  public static com.mbusa.avro.dto.CmpgnCustVehDTO.Builder newBuilder(com.mbusa.avro.dto.CmpgnCustVehDTO other) {
    if (other == null) {
      return new com.mbusa.avro.dto.CmpgnCustVehDTO.Builder();
    } else {
      return new com.mbusa.avro.dto.CmpgnCustVehDTO.Builder(other);
    }
  }

  /**
   * RecordBuilder for CmpgnCustVehDTO instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<CmpgnCustVehDTO>
    implements org.apache.avro.data.RecordBuilder<CmpgnCustVehDTO> {

    private java.lang.CharSequence ID_CUST;
    private java.lang.CharSequence ID_FIN;
    private java.lang.CharSequence DTE_STRT;
    private java.lang.CharSequence DTE_END;
    private java.lang.CharSequence IND_CUST_SRC_VEND;
    private java.lang.CharSequence IND_VIO;
    private java.lang.CharSequence NUM_VEH_LIC_PLT;
    private java.lang.CharSequence DTE_VEH_RGS;
    private java.lang.CharSequence DTE_SRC_RCD_UPDT;
    private java.lang.CharSequence TME_SRC_RCD_UPDT;
    private java.lang.CharSequence ID_SRC_RCD_UPDT_USER;
    private java.lang.CharSequence CDE_SELL_DLR;
    private java.lang.CharSequence DTS_CREA;
    private java.lang.CharSequence ID_CREA_USER;
    private java.lang.CharSequence DTS_LAST_UPDT;
    private java.lang.CharSequence ID_LAST_UPDT_USER;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.mbusa.avro.dto.CmpgnCustVehDTO.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.ID_CUST)) {
        this.ID_CUST = data().deepCopy(fields()[0].schema(), other.ID_CUST);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.ID_FIN)) {
        this.ID_FIN = data().deepCopy(fields()[1].schema(), other.ID_FIN);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.DTE_STRT)) {
        this.DTE_STRT = data().deepCopy(fields()[2].schema(), other.DTE_STRT);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.DTE_END)) {
        this.DTE_END = data().deepCopy(fields()[3].schema(), other.DTE_END);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.IND_CUST_SRC_VEND)) {
        this.IND_CUST_SRC_VEND = data().deepCopy(fields()[4].schema(), other.IND_CUST_SRC_VEND);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.IND_VIO)) {
        this.IND_VIO = data().deepCopy(fields()[5].schema(), other.IND_VIO);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.NUM_VEH_LIC_PLT)) {
        this.NUM_VEH_LIC_PLT = data().deepCopy(fields()[6].schema(), other.NUM_VEH_LIC_PLT);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
      if (isValidValue(fields()[7], other.DTE_VEH_RGS)) {
        this.DTE_VEH_RGS = data().deepCopy(fields()[7].schema(), other.DTE_VEH_RGS);
        fieldSetFlags()[7] = other.fieldSetFlags()[7];
      }
      if (isValidValue(fields()[8], other.DTE_SRC_RCD_UPDT)) {
        this.DTE_SRC_RCD_UPDT = data().deepCopy(fields()[8].schema(), other.DTE_SRC_RCD_UPDT);
        fieldSetFlags()[8] = other.fieldSetFlags()[8];
      }
      if (isValidValue(fields()[9], other.TME_SRC_RCD_UPDT)) {
        this.TME_SRC_RCD_UPDT = data().deepCopy(fields()[9].schema(), other.TME_SRC_RCD_UPDT);
        fieldSetFlags()[9] = other.fieldSetFlags()[9];
      }
      if (isValidValue(fields()[10], other.ID_SRC_RCD_UPDT_USER)) {
        this.ID_SRC_RCD_UPDT_USER = data().deepCopy(fields()[10].schema(), other.ID_SRC_RCD_UPDT_USER);
        fieldSetFlags()[10] = other.fieldSetFlags()[10];
      }
      if (isValidValue(fields()[11], other.CDE_SELL_DLR)) {
        this.CDE_SELL_DLR = data().deepCopy(fields()[11].schema(), other.CDE_SELL_DLR);
        fieldSetFlags()[11] = other.fieldSetFlags()[11];
      }
      if (isValidValue(fields()[12], other.DTS_CREA)) {
        this.DTS_CREA = data().deepCopy(fields()[12].schema(), other.DTS_CREA);
        fieldSetFlags()[12] = other.fieldSetFlags()[12];
      }
      if (isValidValue(fields()[13], other.ID_CREA_USER)) {
        this.ID_CREA_USER = data().deepCopy(fields()[13].schema(), other.ID_CREA_USER);
        fieldSetFlags()[13] = other.fieldSetFlags()[13];
      }
      if (isValidValue(fields()[14], other.DTS_LAST_UPDT)) {
        this.DTS_LAST_UPDT = data().deepCopy(fields()[14].schema(), other.DTS_LAST_UPDT);
        fieldSetFlags()[14] = other.fieldSetFlags()[14];
      }
      if (isValidValue(fields()[15], other.ID_LAST_UPDT_USER)) {
        this.ID_LAST_UPDT_USER = data().deepCopy(fields()[15].schema(), other.ID_LAST_UPDT_USER);
        fieldSetFlags()[15] = other.fieldSetFlags()[15];
      }
    }

    /**
     * Creates a Builder by copying an existing CmpgnCustVehDTO instance
     * @param other The existing instance to copy.
     */
    private Builder(com.mbusa.avro.dto.CmpgnCustVehDTO other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.ID_CUST)) {
        this.ID_CUST = data().deepCopy(fields()[0].schema(), other.ID_CUST);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.ID_FIN)) {
        this.ID_FIN = data().deepCopy(fields()[1].schema(), other.ID_FIN);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.DTE_STRT)) {
        this.DTE_STRT = data().deepCopy(fields()[2].schema(), other.DTE_STRT);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.DTE_END)) {
        this.DTE_END = data().deepCopy(fields()[3].schema(), other.DTE_END);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.IND_CUST_SRC_VEND)) {
        this.IND_CUST_SRC_VEND = data().deepCopy(fields()[4].schema(), other.IND_CUST_SRC_VEND);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.IND_VIO)) {
        this.IND_VIO = data().deepCopy(fields()[5].schema(), other.IND_VIO);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.NUM_VEH_LIC_PLT)) {
        this.NUM_VEH_LIC_PLT = data().deepCopy(fields()[6].schema(), other.NUM_VEH_LIC_PLT);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.DTE_VEH_RGS)) {
        this.DTE_VEH_RGS = data().deepCopy(fields()[7].schema(), other.DTE_VEH_RGS);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.DTE_SRC_RCD_UPDT)) {
        this.DTE_SRC_RCD_UPDT = data().deepCopy(fields()[8].schema(), other.DTE_SRC_RCD_UPDT);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.TME_SRC_RCD_UPDT)) {
        this.TME_SRC_RCD_UPDT = data().deepCopy(fields()[9].schema(), other.TME_SRC_RCD_UPDT);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.ID_SRC_RCD_UPDT_USER)) {
        this.ID_SRC_RCD_UPDT_USER = data().deepCopy(fields()[10].schema(), other.ID_SRC_RCD_UPDT_USER);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.CDE_SELL_DLR)) {
        this.CDE_SELL_DLR = data().deepCopy(fields()[11].schema(), other.CDE_SELL_DLR);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.DTS_CREA)) {
        this.DTS_CREA = data().deepCopy(fields()[12].schema(), other.DTS_CREA);
        fieldSetFlags()[12] = true;
      }
      if (isValidValue(fields()[13], other.ID_CREA_USER)) {
        this.ID_CREA_USER = data().deepCopy(fields()[13].schema(), other.ID_CREA_USER);
        fieldSetFlags()[13] = true;
      }
      if (isValidValue(fields()[14], other.DTS_LAST_UPDT)) {
        this.DTS_LAST_UPDT = data().deepCopy(fields()[14].schema(), other.DTS_LAST_UPDT);
        fieldSetFlags()[14] = true;
      }
      if (isValidValue(fields()[15], other.ID_LAST_UPDT_USER)) {
        this.ID_LAST_UPDT_USER = data().deepCopy(fields()[15].schema(), other.ID_LAST_UPDT_USER);
        fieldSetFlags()[15] = true;
      }
    }

    /**
      * Gets the value of the 'ID_CUST' field.
      * @return The value.
      */
    public java.lang.CharSequence getIDCUST() {
      return ID_CUST;
    }


    /**
      * Sets the value of the 'ID_CUST' field.
      * @param value The value of 'ID_CUST'.
      * @return This builder.
      */
    public com.mbusa.avro.dto.CmpgnCustVehDTO.Builder setIDCUST(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.ID_CUST = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'ID_CUST' field has been set.
      * @return True if the 'ID_CUST' field has been set, false otherwise.
      */
    public boolean hasIDCUST() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'ID_CUST' field.
      * @return This builder.
      */
    public com.mbusa.avro.dto.CmpgnCustVehDTO.Builder clearIDCUST() {
      ID_CUST = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'ID_FIN' field.
      * @return The value.
      */
    public java.lang.CharSequence getIDFIN() {
      return ID_FIN;
    }


    /**
      * Sets the value of the 'ID_FIN' field.
      * @param value The value of 'ID_FIN'.
      * @return This builder.
      */
    public com.mbusa.avro.dto.CmpgnCustVehDTO.Builder setIDFIN(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.ID_FIN = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'ID_FIN' field has been set.
      * @return True if the 'ID_FIN' field has been set, false otherwise.
      */
    public boolean hasIDFIN() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'ID_FIN' field.
      * @return This builder.
      */
    public com.mbusa.avro.dto.CmpgnCustVehDTO.Builder clearIDFIN() {
      ID_FIN = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'DTE_STRT' field.
      * @return The value.
      */
    public java.lang.CharSequence getDTESTRT() {
      return DTE_STRT;
    }


    /**
      * Sets the value of the 'DTE_STRT' field.
      * @param value The value of 'DTE_STRT'.
      * @return This builder.
      */
    public com.mbusa.avro.dto.CmpgnCustVehDTO.Builder setDTESTRT(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.DTE_STRT = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'DTE_STRT' field has been set.
      * @return True if the 'DTE_STRT' field has been set, false otherwise.
      */
    public boolean hasDTESTRT() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'DTE_STRT' field.
      * @return This builder.
      */
    public com.mbusa.avro.dto.CmpgnCustVehDTO.Builder clearDTESTRT() {
      DTE_STRT = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'DTE_END' field.
      * @return The value.
      */
    public java.lang.CharSequence getDTEEND() {
      return DTE_END;
    }


    /**
      * Sets the value of the 'DTE_END' field.
      * @param value The value of 'DTE_END'.
      * @return This builder.
      */
    public com.mbusa.avro.dto.CmpgnCustVehDTO.Builder setDTEEND(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.DTE_END = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'DTE_END' field has been set.
      * @return True if the 'DTE_END' field has been set, false otherwise.
      */
    public boolean hasDTEEND() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'DTE_END' field.
      * @return This builder.
      */
    public com.mbusa.avro.dto.CmpgnCustVehDTO.Builder clearDTEEND() {
      DTE_END = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'IND_CUST_SRC_VEND' field.
      * @return The value.
      */
    public java.lang.CharSequence getINDCUSTSRCVEND() {
      return IND_CUST_SRC_VEND;
    }


    /**
      * Sets the value of the 'IND_CUST_SRC_VEND' field.
      * @param value The value of 'IND_CUST_SRC_VEND'.
      * @return This builder.
      */
    public com.mbusa.avro.dto.CmpgnCustVehDTO.Builder setINDCUSTSRCVEND(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.IND_CUST_SRC_VEND = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'IND_CUST_SRC_VEND' field has been set.
      * @return True if the 'IND_CUST_SRC_VEND' field has been set, false otherwise.
      */
    public boolean hasINDCUSTSRCVEND() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'IND_CUST_SRC_VEND' field.
      * @return This builder.
      */
    public com.mbusa.avro.dto.CmpgnCustVehDTO.Builder clearINDCUSTSRCVEND() {
      IND_CUST_SRC_VEND = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'IND_VIO' field.
      * @return The value.
      */
    public java.lang.CharSequence getINDVIO() {
      return IND_VIO;
    }


    /**
      * Sets the value of the 'IND_VIO' field.
      * @param value The value of 'IND_VIO'.
      * @return This builder.
      */
    public com.mbusa.avro.dto.CmpgnCustVehDTO.Builder setINDVIO(java.lang.CharSequence value) {
      validate(fields()[5], value);
      this.IND_VIO = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'IND_VIO' field has been set.
      * @return True if the 'IND_VIO' field has been set, false otherwise.
      */
    public boolean hasINDVIO() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'IND_VIO' field.
      * @return This builder.
      */
    public com.mbusa.avro.dto.CmpgnCustVehDTO.Builder clearINDVIO() {
      IND_VIO = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'NUM_VEH_LIC_PLT' field.
      * @return The value.
      */
    public java.lang.CharSequence getNUMVEHLICPLT() {
      return NUM_VEH_LIC_PLT;
    }


    /**
      * Sets the value of the 'NUM_VEH_LIC_PLT' field.
      * @param value The value of 'NUM_VEH_LIC_PLT'.
      * @return This builder.
      */
    public com.mbusa.avro.dto.CmpgnCustVehDTO.Builder setNUMVEHLICPLT(java.lang.CharSequence value) {
      validate(fields()[6], value);
      this.NUM_VEH_LIC_PLT = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'NUM_VEH_LIC_PLT' field has been set.
      * @return True if the 'NUM_VEH_LIC_PLT' field has been set, false otherwise.
      */
    public boolean hasNUMVEHLICPLT() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'NUM_VEH_LIC_PLT' field.
      * @return This builder.
      */
    public com.mbusa.avro.dto.CmpgnCustVehDTO.Builder clearNUMVEHLICPLT() {
      NUM_VEH_LIC_PLT = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'DTE_VEH_RGS' field.
      * @return The value.
      */
    public java.lang.CharSequence getDTEVEHRGS() {
      return DTE_VEH_RGS;
    }


    /**
      * Sets the value of the 'DTE_VEH_RGS' field.
      * @param value The value of 'DTE_VEH_RGS'.
      * @return This builder.
      */
    public com.mbusa.avro.dto.CmpgnCustVehDTO.Builder setDTEVEHRGS(java.lang.CharSequence value) {
      validate(fields()[7], value);
      this.DTE_VEH_RGS = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'DTE_VEH_RGS' field has been set.
      * @return True if the 'DTE_VEH_RGS' field has been set, false otherwise.
      */
    public boolean hasDTEVEHRGS() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'DTE_VEH_RGS' field.
      * @return This builder.
      */
    public com.mbusa.avro.dto.CmpgnCustVehDTO.Builder clearDTEVEHRGS() {
      DTE_VEH_RGS = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    /**
      * Gets the value of the 'DTE_SRC_RCD_UPDT' field.
      * @return The value.
      */
    public java.lang.CharSequence getDTESRCRCDUPDT() {
      return DTE_SRC_RCD_UPDT;
    }


    /**
      * Sets the value of the 'DTE_SRC_RCD_UPDT' field.
      * @param value The value of 'DTE_SRC_RCD_UPDT'.
      * @return This builder.
      */
    public com.mbusa.avro.dto.CmpgnCustVehDTO.Builder setDTESRCRCDUPDT(java.lang.CharSequence value) {
      validate(fields()[8], value);
      this.DTE_SRC_RCD_UPDT = value;
      fieldSetFlags()[8] = true;
      return this;
    }

    /**
      * Checks whether the 'DTE_SRC_RCD_UPDT' field has been set.
      * @return True if the 'DTE_SRC_RCD_UPDT' field has been set, false otherwise.
      */
    public boolean hasDTESRCRCDUPDT() {
      return fieldSetFlags()[8];
    }


    /**
      * Clears the value of the 'DTE_SRC_RCD_UPDT' field.
      * @return This builder.
      */
    public com.mbusa.avro.dto.CmpgnCustVehDTO.Builder clearDTESRCRCDUPDT() {
      DTE_SRC_RCD_UPDT = null;
      fieldSetFlags()[8] = false;
      return this;
    }

    /**
      * Gets the value of the 'TME_SRC_RCD_UPDT' field.
      * @return The value.
      */
    public java.lang.CharSequence getTMESRCRCDUPDT() {
      return TME_SRC_RCD_UPDT;
    }


    /**
      * Sets the value of the 'TME_SRC_RCD_UPDT' field.
      * @param value The value of 'TME_SRC_RCD_UPDT'.
      * @return This builder.
      */
    public com.mbusa.avro.dto.CmpgnCustVehDTO.Builder setTMESRCRCDUPDT(java.lang.CharSequence value) {
      validate(fields()[9], value);
      this.TME_SRC_RCD_UPDT = value;
      fieldSetFlags()[9] = true;
      return this;
    }

    /**
      * Checks whether the 'TME_SRC_RCD_UPDT' field has been set.
      * @return True if the 'TME_SRC_RCD_UPDT' field has been set, false otherwise.
      */
    public boolean hasTMESRCRCDUPDT() {
      return fieldSetFlags()[9];
    }


    /**
      * Clears the value of the 'TME_SRC_RCD_UPDT' field.
      * @return This builder.
      */
    public com.mbusa.avro.dto.CmpgnCustVehDTO.Builder clearTMESRCRCDUPDT() {
      TME_SRC_RCD_UPDT = null;
      fieldSetFlags()[9] = false;
      return this;
    }

    /**
      * Gets the value of the 'ID_SRC_RCD_UPDT_USER' field.
      * @return The value.
      */
    public java.lang.CharSequence getIDSRCRCDUPDTUSER() {
      return ID_SRC_RCD_UPDT_USER;
    }


    /**
      * Sets the value of the 'ID_SRC_RCD_UPDT_USER' field.
      * @param value The value of 'ID_SRC_RCD_UPDT_USER'.
      * @return This builder.
      */
    public com.mbusa.avro.dto.CmpgnCustVehDTO.Builder setIDSRCRCDUPDTUSER(java.lang.CharSequence value) {
      validate(fields()[10], value);
      this.ID_SRC_RCD_UPDT_USER = value;
      fieldSetFlags()[10] = true;
      return this;
    }

    /**
      * Checks whether the 'ID_SRC_RCD_UPDT_USER' field has been set.
      * @return True if the 'ID_SRC_RCD_UPDT_USER' field has been set, false otherwise.
      */
    public boolean hasIDSRCRCDUPDTUSER() {
      return fieldSetFlags()[10];
    }


    /**
      * Clears the value of the 'ID_SRC_RCD_UPDT_USER' field.
      * @return This builder.
      */
    public com.mbusa.avro.dto.CmpgnCustVehDTO.Builder clearIDSRCRCDUPDTUSER() {
      ID_SRC_RCD_UPDT_USER = null;
      fieldSetFlags()[10] = false;
      return this;
    }

    /**
      * Gets the value of the 'CDE_SELL_DLR' field.
      * @return The value.
      */
    public java.lang.CharSequence getCDESELLDLR() {
      return CDE_SELL_DLR;
    }


    /**
      * Sets the value of the 'CDE_SELL_DLR' field.
      * @param value The value of 'CDE_SELL_DLR'.
      * @return This builder.
      */
    public com.mbusa.avro.dto.CmpgnCustVehDTO.Builder setCDESELLDLR(java.lang.CharSequence value) {
      validate(fields()[11], value);
      this.CDE_SELL_DLR = value;
      fieldSetFlags()[11] = true;
      return this;
    }

    /**
      * Checks whether the 'CDE_SELL_DLR' field has been set.
      * @return True if the 'CDE_SELL_DLR' field has been set, false otherwise.
      */
    public boolean hasCDESELLDLR() {
      return fieldSetFlags()[11];
    }


    /**
      * Clears the value of the 'CDE_SELL_DLR' field.
      * @return This builder.
      */
    public com.mbusa.avro.dto.CmpgnCustVehDTO.Builder clearCDESELLDLR() {
      CDE_SELL_DLR = null;
      fieldSetFlags()[11] = false;
      return this;
    }

    /**
      * Gets the value of the 'DTS_CREA' field.
      * @return The value.
      */
    public java.lang.CharSequence getDTSCREA() {
      return DTS_CREA;
    }


    /**
      * Sets the value of the 'DTS_CREA' field.
      * @param value The value of 'DTS_CREA'.
      * @return This builder.
      */
    public com.mbusa.avro.dto.CmpgnCustVehDTO.Builder setDTSCREA(java.lang.CharSequence value) {
      validate(fields()[12], value);
      this.DTS_CREA = value;
      fieldSetFlags()[12] = true;
      return this;
    }

    /**
      * Checks whether the 'DTS_CREA' field has been set.
      * @return True if the 'DTS_CREA' field has been set, false otherwise.
      */
    public boolean hasDTSCREA() {
      return fieldSetFlags()[12];
    }


    /**
      * Clears the value of the 'DTS_CREA' field.
      * @return This builder.
      */
    public com.mbusa.avro.dto.CmpgnCustVehDTO.Builder clearDTSCREA() {
      DTS_CREA = null;
      fieldSetFlags()[12] = false;
      return this;
    }

    /**
      * Gets the value of the 'ID_CREA_USER' field.
      * @return The value.
      */
    public java.lang.CharSequence getIDCREAUSER() {
      return ID_CREA_USER;
    }


    /**
      * Sets the value of the 'ID_CREA_USER' field.
      * @param value The value of 'ID_CREA_USER'.
      * @return This builder.
      */
    public com.mbusa.avro.dto.CmpgnCustVehDTO.Builder setIDCREAUSER(java.lang.CharSequence value) {
      validate(fields()[13], value);
      this.ID_CREA_USER = value;
      fieldSetFlags()[13] = true;
      return this;
    }

    /**
      * Checks whether the 'ID_CREA_USER' field has been set.
      * @return True if the 'ID_CREA_USER' field has been set, false otherwise.
      */
    public boolean hasIDCREAUSER() {
      return fieldSetFlags()[13];
    }


    /**
      * Clears the value of the 'ID_CREA_USER' field.
      * @return This builder.
      */
    public com.mbusa.avro.dto.CmpgnCustVehDTO.Builder clearIDCREAUSER() {
      ID_CREA_USER = null;
      fieldSetFlags()[13] = false;
      return this;
    }

    /**
      * Gets the value of the 'DTS_LAST_UPDT' field.
      * @return The value.
      */
    public java.lang.CharSequence getDTSLASTUPDT() {
      return DTS_LAST_UPDT;
    }


    /**
      * Sets the value of the 'DTS_LAST_UPDT' field.
      * @param value The value of 'DTS_LAST_UPDT'.
      * @return This builder.
      */
    public com.mbusa.avro.dto.CmpgnCustVehDTO.Builder setDTSLASTUPDT(java.lang.CharSequence value) {
      validate(fields()[14], value);
      this.DTS_LAST_UPDT = value;
      fieldSetFlags()[14] = true;
      return this;
    }

    /**
      * Checks whether the 'DTS_LAST_UPDT' field has been set.
      * @return True if the 'DTS_LAST_UPDT' field has been set, false otherwise.
      */
    public boolean hasDTSLASTUPDT() {
      return fieldSetFlags()[14];
    }


    /**
      * Clears the value of the 'DTS_LAST_UPDT' field.
      * @return This builder.
      */
    public com.mbusa.avro.dto.CmpgnCustVehDTO.Builder clearDTSLASTUPDT() {
      DTS_LAST_UPDT = null;
      fieldSetFlags()[14] = false;
      return this;
    }

    /**
      * Gets the value of the 'ID_LAST_UPDT_USER' field.
      * @return The value.
      */
    public java.lang.CharSequence getIDLASTUPDTUSER() {
      return ID_LAST_UPDT_USER;
    }


    /**
      * Sets the value of the 'ID_LAST_UPDT_USER' field.
      * @param value The value of 'ID_LAST_UPDT_USER'.
      * @return This builder.
      */
    public com.mbusa.avro.dto.CmpgnCustVehDTO.Builder setIDLASTUPDTUSER(java.lang.CharSequence value) {
      validate(fields()[15], value);
      this.ID_LAST_UPDT_USER = value;
      fieldSetFlags()[15] = true;
      return this;
    }

    /**
      * Checks whether the 'ID_LAST_UPDT_USER' field has been set.
      * @return True if the 'ID_LAST_UPDT_USER' field has been set, false otherwise.
      */
    public boolean hasIDLASTUPDTUSER() {
      return fieldSetFlags()[15];
    }


    /**
      * Clears the value of the 'ID_LAST_UPDT_USER' field.
      * @return This builder.
      */
    public com.mbusa.avro.dto.CmpgnCustVehDTO.Builder clearIDLASTUPDTUSER() {
      ID_LAST_UPDT_USER = null;
      fieldSetFlags()[15] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public CmpgnCustVehDTO build() {
      try {
        CmpgnCustVehDTO record = new CmpgnCustVehDTO();
        record.ID_CUST = fieldSetFlags()[0] ? this.ID_CUST : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.ID_FIN = fieldSetFlags()[1] ? this.ID_FIN : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.DTE_STRT = fieldSetFlags()[2] ? this.DTE_STRT : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.DTE_END = fieldSetFlags()[3] ? this.DTE_END : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.IND_CUST_SRC_VEND = fieldSetFlags()[4] ? this.IND_CUST_SRC_VEND : (java.lang.CharSequence) defaultValue(fields()[4]);
        record.IND_VIO = fieldSetFlags()[5] ? this.IND_VIO : (java.lang.CharSequence) defaultValue(fields()[5]);
        record.NUM_VEH_LIC_PLT = fieldSetFlags()[6] ? this.NUM_VEH_LIC_PLT : (java.lang.CharSequence) defaultValue(fields()[6]);
        record.DTE_VEH_RGS = fieldSetFlags()[7] ? this.DTE_VEH_RGS : (java.lang.CharSequence) defaultValue(fields()[7]);
        record.DTE_SRC_RCD_UPDT = fieldSetFlags()[8] ? this.DTE_SRC_RCD_UPDT : (java.lang.CharSequence) defaultValue(fields()[8]);
        record.TME_SRC_RCD_UPDT = fieldSetFlags()[9] ? this.TME_SRC_RCD_UPDT : (java.lang.CharSequence) defaultValue(fields()[9]);
        record.ID_SRC_RCD_UPDT_USER = fieldSetFlags()[10] ? this.ID_SRC_RCD_UPDT_USER : (java.lang.CharSequence) defaultValue(fields()[10]);
        record.CDE_SELL_DLR = fieldSetFlags()[11] ? this.CDE_SELL_DLR : (java.lang.CharSequence) defaultValue(fields()[11]);
        record.DTS_CREA = fieldSetFlags()[12] ? this.DTS_CREA : (java.lang.CharSequence) defaultValue(fields()[12]);
        record.ID_CREA_USER = fieldSetFlags()[13] ? this.ID_CREA_USER : (java.lang.CharSequence) defaultValue(fields()[13]);
        record.DTS_LAST_UPDT = fieldSetFlags()[14] ? this.DTS_LAST_UPDT : (java.lang.CharSequence) defaultValue(fields()[14]);
        record.ID_LAST_UPDT_USER = fieldSetFlags()[15] ? this.ID_LAST_UPDT_USER : (java.lang.CharSequence) defaultValue(fields()[15]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<CmpgnCustVehDTO>
    WRITER$ = (org.apache.avro.io.DatumWriter<CmpgnCustVehDTO>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<CmpgnCustVehDTO>
    READER$ = (org.apache.avro.io.DatumReader<CmpgnCustVehDTO>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.ID_CUST);

    out.writeString(this.ID_FIN);

    out.writeString(this.DTE_STRT);

    out.writeString(this.DTE_END);

    out.writeString(this.IND_CUST_SRC_VEND);

    out.writeString(this.IND_VIO);

    out.writeString(this.NUM_VEH_LIC_PLT);

    out.writeString(this.DTE_VEH_RGS);

    out.writeString(this.DTE_SRC_RCD_UPDT);

    out.writeString(this.TME_SRC_RCD_UPDT);

    out.writeString(this.ID_SRC_RCD_UPDT_USER);

    out.writeString(this.CDE_SELL_DLR);

    out.writeString(this.DTS_CREA);

    out.writeString(this.ID_CREA_USER);

    out.writeString(this.DTS_LAST_UPDT);

    out.writeString(this.ID_LAST_UPDT_USER);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.ID_CUST = in.readString(this.ID_CUST instanceof Utf8 ? (Utf8)this.ID_CUST : null);

      this.ID_FIN = in.readString(this.ID_FIN instanceof Utf8 ? (Utf8)this.ID_FIN : null);

      this.DTE_STRT = in.readString(this.DTE_STRT instanceof Utf8 ? (Utf8)this.DTE_STRT : null);

      this.DTE_END = in.readString(this.DTE_END instanceof Utf8 ? (Utf8)this.DTE_END : null);

      this.IND_CUST_SRC_VEND = in.readString(this.IND_CUST_SRC_VEND instanceof Utf8 ? (Utf8)this.IND_CUST_SRC_VEND : null);

      this.IND_VIO = in.readString(this.IND_VIO instanceof Utf8 ? (Utf8)this.IND_VIO : null);

      this.NUM_VEH_LIC_PLT = in.readString(this.NUM_VEH_LIC_PLT instanceof Utf8 ? (Utf8)this.NUM_VEH_LIC_PLT : null);

      this.DTE_VEH_RGS = in.readString(this.DTE_VEH_RGS instanceof Utf8 ? (Utf8)this.DTE_VEH_RGS : null);

      this.DTE_SRC_RCD_UPDT = in.readString(this.DTE_SRC_RCD_UPDT instanceof Utf8 ? (Utf8)this.DTE_SRC_RCD_UPDT : null);

      this.TME_SRC_RCD_UPDT = in.readString(this.TME_SRC_RCD_UPDT instanceof Utf8 ? (Utf8)this.TME_SRC_RCD_UPDT : null);

      this.ID_SRC_RCD_UPDT_USER = in.readString(this.ID_SRC_RCD_UPDT_USER instanceof Utf8 ? (Utf8)this.ID_SRC_RCD_UPDT_USER : null);

      this.CDE_SELL_DLR = in.readString(this.CDE_SELL_DLR instanceof Utf8 ? (Utf8)this.CDE_SELL_DLR : null);

      this.DTS_CREA = in.readString(this.DTS_CREA instanceof Utf8 ? (Utf8)this.DTS_CREA : null);

      this.ID_CREA_USER = in.readString(this.ID_CREA_USER instanceof Utf8 ? (Utf8)this.ID_CREA_USER : null);

      this.DTS_LAST_UPDT = in.readString(this.DTS_LAST_UPDT instanceof Utf8 ? (Utf8)this.DTS_LAST_UPDT : null);

      this.ID_LAST_UPDT_USER = in.readString(this.ID_LAST_UPDT_USER instanceof Utf8 ? (Utf8)this.ID_LAST_UPDT_USER : null);

    } else {
      for (int i = 0; i < 16; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.ID_CUST = in.readString(this.ID_CUST instanceof Utf8 ? (Utf8)this.ID_CUST : null);
          break;

        case 1:
          this.ID_FIN = in.readString(this.ID_FIN instanceof Utf8 ? (Utf8)this.ID_FIN : null);
          break;

        case 2:
          this.DTE_STRT = in.readString(this.DTE_STRT instanceof Utf8 ? (Utf8)this.DTE_STRT : null);
          break;

        case 3:
          this.DTE_END = in.readString(this.DTE_END instanceof Utf8 ? (Utf8)this.DTE_END : null);
          break;

        case 4:
          this.IND_CUST_SRC_VEND = in.readString(this.IND_CUST_SRC_VEND instanceof Utf8 ? (Utf8)this.IND_CUST_SRC_VEND : null);
          break;

        case 5:
          this.IND_VIO = in.readString(this.IND_VIO instanceof Utf8 ? (Utf8)this.IND_VIO : null);
          break;

        case 6:
          this.NUM_VEH_LIC_PLT = in.readString(this.NUM_VEH_LIC_PLT instanceof Utf8 ? (Utf8)this.NUM_VEH_LIC_PLT : null);
          break;

        case 7:
          this.DTE_VEH_RGS = in.readString(this.DTE_VEH_RGS instanceof Utf8 ? (Utf8)this.DTE_VEH_RGS : null);
          break;

        case 8:
          this.DTE_SRC_RCD_UPDT = in.readString(this.DTE_SRC_RCD_UPDT instanceof Utf8 ? (Utf8)this.DTE_SRC_RCD_UPDT : null);
          break;

        case 9:
          this.TME_SRC_RCD_UPDT = in.readString(this.TME_SRC_RCD_UPDT instanceof Utf8 ? (Utf8)this.TME_SRC_RCD_UPDT : null);
          break;

        case 10:
          this.ID_SRC_RCD_UPDT_USER = in.readString(this.ID_SRC_RCD_UPDT_USER instanceof Utf8 ? (Utf8)this.ID_SRC_RCD_UPDT_USER : null);
          break;

        case 11:
          this.CDE_SELL_DLR = in.readString(this.CDE_SELL_DLR instanceof Utf8 ? (Utf8)this.CDE_SELL_DLR : null);
          break;

        case 12:
          this.DTS_CREA = in.readString(this.DTS_CREA instanceof Utf8 ? (Utf8)this.DTS_CREA : null);
          break;

        case 13:
          this.ID_CREA_USER = in.readString(this.ID_CREA_USER instanceof Utf8 ? (Utf8)this.ID_CREA_USER : null);
          break;

        case 14:
          this.DTS_LAST_UPDT = in.readString(this.DTS_LAST_UPDT instanceof Utf8 ? (Utf8)this.DTS_LAST_UPDT : null);
          break;

        case 15:
          this.ID_LAST_UPDT_USER = in.readString(this.ID_LAST_UPDT_USER instanceof Utf8 ? (Utf8)this.ID_LAST_UPDT_USER : null);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










