/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.mbusa.avro.dto;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class TktCmpgnVehCustStatCdeDTO extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 4137880811612505150L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"TktCmpgnVehCustStatCdeDTO\",\"namespace\":\"com.mbusa.avro.dto\",\"fields\":[{\"name\":\"CDE_CMPGN_VEH_CUST_STAT\",\"type\":\"string\"},{\"name\":\"DES_CMPGN_VEH_CUST_STAT\",\"type\":\"string\"},{\"name\":\"DTS_CREA\",\"type\":\"string\"},{\"name\":\"ID_CREA_USER\",\"type\":\"string\"},{\"name\":\"DTS_LAST_UPDT\",\"type\":\"string\"},{\"name\":\"ID_LAST_UPDT_USER\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<TktCmpgnVehCustStatCdeDTO> ENCODER =
      new BinaryMessageEncoder<TktCmpgnVehCustStatCdeDTO>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<TktCmpgnVehCustStatCdeDTO> DECODER =
      new BinaryMessageDecoder<TktCmpgnVehCustStatCdeDTO>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<TktCmpgnVehCustStatCdeDTO> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<TktCmpgnVehCustStatCdeDTO> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<TktCmpgnVehCustStatCdeDTO> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<TktCmpgnVehCustStatCdeDTO>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this TktCmpgnVehCustStatCdeDTO to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a TktCmpgnVehCustStatCdeDTO from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a TktCmpgnVehCustStatCdeDTO instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static TktCmpgnVehCustStatCdeDTO fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private java.lang.CharSequence CDE_CMPGN_VEH_CUST_STAT;
   private java.lang.CharSequence DES_CMPGN_VEH_CUST_STAT;
   private java.lang.CharSequence DTS_CREA;
   private java.lang.CharSequence ID_CREA_USER;
   private java.lang.CharSequence DTS_LAST_UPDT;
   private java.lang.CharSequence ID_LAST_UPDT_USER;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public TktCmpgnVehCustStatCdeDTO() {}

  /**
   * All-args constructor.
   * @param CDE_CMPGN_VEH_CUST_STAT The new value for CDE_CMPGN_VEH_CUST_STAT
   * @param DES_CMPGN_VEH_CUST_STAT The new value for DES_CMPGN_VEH_CUST_STAT
   * @param DTS_CREA The new value for DTS_CREA
   * @param ID_CREA_USER The new value for ID_CREA_USER
   * @param DTS_LAST_UPDT The new value for DTS_LAST_UPDT
   * @param ID_LAST_UPDT_USER The new value for ID_LAST_UPDT_USER
   */
  public TktCmpgnVehCustStatCdeDTO(java.lang.CharSequence CDE_CMPGN_VEH_CUST_STAT, java.lang.CharSequence DES_CMPGN_VEH_CUST_STAT, java.lang.CharSequence DTS_CREA, java.lang.CharSequence ID_CREA_USER, java.lang.CharSequence DTS_LAST_UPDT, java.lang.CharSequence ID_LAST_UPDT_USER) {
    this.CDE_CMPGN_VEH_CUST_STAT = CDE_CMPGN_VEH_CUST_STAT;
    this.DES_CMPGN_VEH_CUST_STAT = DES_CMPGN_VEH_CUST_STAT;
    this.DTS_CREA = DTS_CREA;
    this.ID_CREA_USER = ID_CREA_USER;
    this.DTS_LAST_UPDT = DTS_LAST_UPDT;
    this.ID_LAST_UPDT_USER = ID_LAST_UPDT_USER;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return CDE_CMPGN_VEH_CUST_STAT;
    case 1: return DES_CMPGN_VEH_CUST_STAT;
    case 2: return DTS_CREA;
    case 3: return ID_CREA_USER;
    case 4: return DTS_LAST_UPDT;
    case 5: return ID_LAST_UPDT_USER;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: CDE_CMPGN_VEH_CUST_STAT = (java.lang.CharSequence)value$; break;
    case 1: DES_CMPGN_VEH_CUST_STAT = (java.lang.CharSequence)value$; break;
    case 2: DTS_CREA = (java.lang.CharSequence)value$; break;
    case 3: ID_CREA_USER = (java.lang.CharSequence)value$; break;
    case 4: DTS_LAST_UPDT = (java.lang.CharSequence)value$; break;
    case 5: ID_LAST_UPDT_USER = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'CDE_CMPGN_VEH_CUST_STAT' field.
   * @return The value of the 'CDE_CMPGN_VEH_CUST_STAT' field.
   */
  public java.lang.CharSequence getCDECMPGNVEHCUSTSTAT() {
    return CDE_CMPGN_VEH_CUST_STAT;
  }


  /**
   * Sets the value of the 'CDE_CMPGN_VEH_CUST_STAT' field.
   * @param value the value to set.
   */
  public void setCDECMPGNVEHCUSTSTAT(java.lang.CharSequence value) {
    this.CDE_CMPGN_VEH_CUST_STAT = value;
  }

  /**
   * Gets the value of the 'DES_CMPGN_VEH_CUST_STAT' field.
   * @return The value of the 'DES_CMPGN_VEH_CUST_STAT' field.
   */
  public java.lang.CharSequence getDESCMPGNVEHCUSTSTAT() {
    return DES_CMPGN_VEH_CUST_STAT;
  }


  /**
   * Sets the value of the 'DES_CMPGN_VEH_CUST_STAT' field.
   * @param value the value to set.
   */
  public void setDESCMPGNVEHCUSTSTAT(java.lang.CharSequence value) {
    this.DES_CMPGN_VEH_CUST_STAT = value;
  }

  /**
   * Gets the value of the 'DTS_CREA' field.
   * @return The value of the 'DTS_CREA' field.
   */
  public java.lang.CharSequence getDTSCREA() {
    return DTS_CREA;
  }


  /**
   * Sets the value of the 'DTS_CREA' field.
   * @param value the value to set.
   */
  public void setDTSCREA(java.lang.CharSequence value) {
    this.DTS_CREA = value;
  }

  /**
   * Gets the value of the 'ID_CREA_USER' field.
   * @return The value of the 'ID_CREA_USER' field.
   */
  public java.lang.CharSequence getIDCREAUSER() {
    return ID_CREA_USER;
  }


  /**
   * Sets the value of the 'ID_CREA_USER' field.
   * @param value the value to set.
   */
  public void setIDCREAUSER(java.lang.CharSequence value) {
    this.ID_CREA_USER = value;
  }

  /**
   * Gets the value of the 'DTS_LAST_UPDT' field.
   * @return The value of the 'DTS_LAST_UPDT' field.
   */
  public java.lang.CharSequence getDTSLASTUPDT() {
    return DTS_LAST_UPDT;
  }


  /**
   * Sets the value of the 'DTS_LAST_UPDT' field.
   * @param value the value to set.
   */
  public void setDTSLASTUPDT(java.lang.CharSequence value) {
    this.DTS_LAST_UPDT = value;
  }

  /**
   * Gets the value of the 'ID_LAST_UPDT_USER' field.
   * @return The value of the 'ID_LAST_UPDT_USER' field.
   */
  public java.lang.CharSequence getIDLASTUPDTUSER() {
    return ID_LAST_UPDT_USER;
  }


  /**
   * Sets the value of the 'ID_LAST_UPDT_USER' field.
   * @param value the value to set.
   */
  public void setIDLASTUPDTUSER(java.lang.CharSequence value) {
    this.ID_LAST_UPDT_USER = value;
  }

  /**
   * Creates a new TktCmpgnVehCustStatCdeDTO RecordBuilder.
   * @return A new TktCmpgnVehCustStatCdeDTO RecordBuilder
   */
  public static com.mbusa.avro.dto.TktCmpgnVehCustStatCdeDTO.Builder newBuilder() {
    return new com.mbusa.avro.dto.TktCmpgnVehCustStatCdeDTO.Builder();
  }

  /**
   * Creates a new TktCmpgnVehCustStatCdeDTO RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new TktCmpgnVehCustStatCdeDTO RecordBuilder
   */
  public static com.mbusa.avro.dto.TktCmpgnVehCustStatCdeDTO.Builder newBuilder(com.mbusa.avro.dto.TktCmpgnVehCustStatCdeDTO.Builder other) {
    if (other == null) {
      return new com.mbusa.avro.dto.TktCmpgnVehCustStatCdeDTO.Builder();
    } else {
      return new com.mbusa.avro.dto.TktCmpgnVehCustStatCdeDTO.Builder(other);
    }
  }

  /**
   * Creates a new TktCmpgnVehCustStatCdeDTO RecordBuilder by copying an existing TktCmpgnVehCustStatCdeDTO instance.
   * @param other The existing instance to copy.
   * @return A new TktCmpgnVehCustStatCdeDTO RecordBuilder
   */
  public static com.mbusa.avro.dto.TktCmpgnVehCustStatCdeDTO.Builder newBuilder(com.mbusa.avro.dto.TktCmpgnVehCustStatCdeDTO other) {
    if (other == null) {
      return new com.mbusa.avro.dto.TktCmpgnVehCustStatCdeDTO.Builder();
    } else {
      return new com.mbusa.avro.dto.TktCmpgnVehCustStatCdeDTO.Builder(other);
    }
  }

  /**
   * RecordBuilder for TktCmpgnVehCustStatCdeDTO instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<TktCmpgnVehCustStatCdeDTO>
    implements org.apache.avro.data.RecordBuilder<TktCmpgnVehCustStatCdeDTO> {

    private java.lang.CharSequence CDE_CMPGN_VEH_CUST_STAT;
    private java.lang.CharSequence DES_CMPGN_VEH_CUST_STAT;
    private java.lang.CharSequence DTS_CREA;
    private java.lang.CharSequence ID_CREA_USER;
    private java.lang.CharSequence DTS_LAST_UPDT;
    private java.lang.CharSequence ID_LAST_UPDT_USER;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.mbusa.avro.dto.TktCmpgnVehCustStatCdeDTO.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.CDE_CMPGN_VEH_CUST_STAT)) {
        this.CDE_CMPGN_VEH_CUST_STAT = data().deepCopy(fields()[0].schema(), other.CDE_CMPGN_VEH_CUST_STAT);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.DES_CMPGN_VEH_CUST_STAT)) {
        this.DES_CMPGN_VEH_CUST_STAT = data().deepCopy(fields()[1].schema(), other.DES_CMPGN_VEH_CUST_STAT);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.DTS_CREA)) {
        this.DTS_CREA = data().deepCopy(fields()[2].schema(), other.DTS_CREA);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.ID_CREA_USER)) {
        this.ID_CREA_USER = data().deepCopy(fields()[3].schema(), other.ID_CREA_USER);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.DTS_LAST_UPDT)) {
        this.DTS_LAST_UPDT = data().deepCopy(fields()[4].schema(), other.DTS_LAST_UPDT);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.ID_LAST_UPDT_USER)) {
        this.ID_LAST_UPDT_USER = data().deepCopy(fields()[5].schema(), other.ID_LAST_UPDT_USER);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
    }

    /**
     * Creates a Builder by copying an existing TktCmpgnVehCustStatCdeDTO instance
     * @param other The existing instance to copy.
     */
    private Builder(com.mbusa.avro.dto.TktCmpgnVehCustStatCdeDTO other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.CDE_CMPGN_VEH_CUST_STAT)) {
        this.CDE_CMPGN_VEH_CUST_STAT = data().deepCopy(fields()[0].schema(), other.CDE_CMPGN_VEH_CUST_STAT);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.DES_CMPGN_VEH_CUST_STAT)) {
        this.DES_CMPGN_VEH_CUST_STAT = data().deepCopy(fields()[1].schema(), other.DES_CMPGN_VEH_CUST_STAT);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.DTS_CREA)) {
        this.DTS_CREA = data().deepCopy(fields()[2].schema(), other.DTS_CREA);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.ID_CREA_USER)) {
        this.ID_CREA_USER = data().deepCopy(fields()[3].schema(), other.ID_CREA_USER);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.DTS_LAST_UPDT)) {
        this.DTS_LAST_UPDT = data().deepCopy(fields()[4].schema(), other.DTS_LAST_UPDT);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.ID_LAST_UPDT_USER)) {
        this.ID_LAST_UPDT_USER = data().deepCopy(fields()[5].schema(), other.ID_LAST_UPDT_USER);
        fieldSetFlags()[5] = true;
      }
    }

    /**
      * Gets the value of the 'CDE_CMPGN_VEH_CUST_STAT' field.
      * @return The value.
      */
    public java.lang.CharSequence getCDECMPGNVEHCUSTSTAT() {
      return CDE_CMPGN_VEH_CUST_STAT;
    }


    /**
      * Sets the value of the 'CDE_CMPGN_VEH_CUST_STAT' field.
      * @param value The value of 'CDE_CMPGN_VEH_CUST_STAT'.
      * @return This builder.
      */
    public com.mbusa.avro.dto.TktCmpgnVehCustStatCdeDTO.Builder setCDECMPGNVEHCUSTSTAT(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.CDE_CMPGN_VEH_CUST_STAT = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'CDE_CMPGN_VEH_CUST_STAT' field has been set.
      * @return True if the 'CDE_CMPGN_VEH_CUST_STAT' field has been set, false otherwise.
      */
    public boolean hasCDECMPGNVEHCUSTSTAT() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'CDE_CMPGN_VEH_CUST_STAT' field.
      * @return This builder.
      */
    public com.mbusa.avro.dto.TktCmpgnVehCustStatCdeDTO.Builder clearCDECMPGNVEHCUSTSTAT() {
      CDE_CMPGN_VEH_CUST_STAT = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'DES_CMPGN_VEH_CUST_STAT' field.
      * @return The value.
      */
    public java.lang.CharSequence getDESCMPGNVEHCUSTSTAT() {
      return DES_CMPGN_VEH_CUST_STAT;
    }


    /**
      * Sets the value of the 'DES_CMPGN_VEH_CUST_STAT' field.
      * @param value The value of 'DES_CMPGN_VEH_CUST_STAT'.
      * @return This builder.
      */
    public com.mbusa.avro.dto.TktCmpgnVehCustStatCdeDTO.Builder setDESCMPGNVEHCUSTSTAT(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.DES_CMPGN_VEH_CUST_STAT = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'DES_CMPGN_VEH_CUST_STAT' field has been set.
      * @return True if the 'DES_CMPGN_VEH_CUST_STAT' field has been set, false otherwise.
      */
    public boolean hasDESCMPGNVEHCUSTSTAT() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'DES_CMPGN_VEH_CUST_STAT' field.
      * @return This builder.
      */
    public com.mbusa.avro.dto.TktCmpgnVehCustStatCdeDTO.Builder clearDESCMPGNVEHCUSTSTAT() {
      DES_CMPGN_VEH_CUST_STAT = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'DTS_CREA' field.
      * @return The value.
      */
    public java.lang.CharSequence getDTSCREA() {
      return DTS_CREA;
    }


    /**
      * Sets the value of the 'DTS_CREA' field.
      * @param value The value of 'DTS_CREA'.
      * @return This builder.
      */
    public com.mbusa.avro.dto.TktCmpgnVehCustStatCdeDTO.Builder setDTSCREA(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.DTS_CREA = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'DTS_CREA' field has been set.
      * @return True if the 'DTS_CREA' field has been set, false otherwise.
      */
    public boolean hasDTSCREA() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'DTS_CREA' field.
      * @return This builder.
      */
    public com.mbusa.avro.dto.TktCmpgnVehCustStatCdeDTO.Builder clearDTSCREA() {
      DTS_CREA = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'ID_CREA_USER' field.
      * @return The value.
      */
    public java.lang.CharSequence getIDCREAUSER() {
      return ID_CREA_USER;
    }


    /**
      * Sets the value of the 'ID_CREA_USER' field.
      * @param value The value of 'ID_CREA_USER'.
      * @return This builder.
      */
    public com.mbusa.avro.dto.TktCmpgnVehCustStatCdeDTO.Builder setIDCREAUSER(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.ID_CREA_USER = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'ID_CREA_USER' field has been set.
      * @return True if the 'ID_CREA_USER' field has been set, false otherwise.
      */
    public boolean hasIDCREAUSER() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'ID_CREA_USER' field.
      * @return This builder.
      */
    public com.mbusa.avro.dto.TktCmpgnVehCustStatCdeDTO.Builder clearIDCREAUSER() {
      ID_CREA_USER = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'DTS_LAST_UPDT' field.
      * @return The value.
      */
    public java.lang.CharSequence getDTSLASTUPDT() {
      return DTS_LAST_UPDT;
    }


    /**
      * Sets the value of the 'DTS_LAST_UPDT' field.
      * @param value The value of 'DTS_LAST_UPDT'.
      * @return This builder.
      */
    public com.mbusa.avro.dto.TktCmpgnVehCustStatCdeDTO.Builder setDTSLASTUPDT(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.DTS_LAST_UPDT = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'DTS_LAST_UPDT' field has been set.
      * @return True if the 'DTS_LAST_UPDT' field has been set, false otherwise.
      */
    public boolean hasDTSLASTUPDT() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'DTS_LAST_UPDT' field.
      * @return This builder.
      */
    public com.mbusa.avro.dto.TktCmpgnVehCustStatCdeDTO.Builder clearDTSLASTUPDT() {
      DTS_LAST_UPDT = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'ID_LAST_UPDT_USER' field.
      * @return The value.
      */
    public java.lang.CharSequence getIDLASTUPDTUSER() {
      return ID_LAST_UPDT_USER;
    }


    /**
      * Sets the value of the 'ID_LAST_UPDT_USER' field.
      * @param value The value of 'ID_LAST_UPDT_USER'.
      * @return This builder.
      */
    public com.mbusa.avro.dto.TktCmpgnVehCustStatCdeDTO.Builder setIDLASTUPDTUSER(java.lang.CharSequence value) {
      validate(fields()[5], value);
      this.ID_LAST_UPDT_USER = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'ID_LAST_UPDT_USER' field has been set.
      * @return True if the 'ID_LAST_UPDT_USER' field has been set, false otherwise.
      */
    public boolean hasIDLASTUPDTUSER() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'ID_LAST_UPDT_USER' field.
      * @return This builder.
      */
    public com.mbusa.avro.dto.TktCmpgnVehCustStatCdeDTO.Builder clearIDLASTUPDTUSER() {
      ID_LAST_UPDT_USER = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public TktCmpgnVehCustStatCdeDTO build() {
      try {
        TktCmpgnVehCustStatCdeDTO record = new TktCmpgnVehCustStatCdeDTO();
        record.CDE_CMPGN_VEH_CUST_STAT = fieldSetFlags()[0] ? this.CDE_CMPGN_VEH_CUST_STAT : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.DES_CMPGN_VEH_CUST_STAT = fieldSetFlags()[1] ? this.DES_CMPGN_VEH_CUST_STAT : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.DTS_CREA = fieldSetFlags()[2] ? this.DTS_CREA : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.ID_CREA_USER = fieldSetFlags()[3] ? this.ID_CREA_USER : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.DTS_LAST_UPDT = fieldSetFlags()[4] ? this.DTS_LAST_UPDT : (java.lang.CharSequence) defaultValue(fields()[4]);
        record.ID_LAST_UPDT_USER = fieldSetFlags()[5] ? this.ID_LAST_UPDT_USER : (java.lang.CharSequence) defaultValue(fields()[5]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<TktCmpgnVehCustStatCdeDTO>
    WRITER$ = (org.apache.avro.io.DatumWriter<TktCmpgnVehCustStatCdeDTO>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<TktCmpgnVehCustStatCdeDTO>
    READER$ = (org.apache.avro.io.DatumReader<TktCmpgnVehCustStatCdeDTO>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.CDE_CMPGN_VEH_CUST_STAT);

    out.writeString(this.DES_CMPGN_VEH_CUST_STAT);

    out.writeString(this.DTS_CREA);

    out.writeString(this.ID_CREA_USER);

    out.writeString(this.DTS_LAST_UPDT);

    out.writeString(this.ID_LAST_UPDT_USER);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.CDE_CMPGN_VEH_CUST_STAT = in.readString(this.CDE_CMPGN_VEH_CUST_STAT instanceof Utf8 ? (Utf8)this.CDE_CMPGN_VEH_CUST_STAT : null);

      this.DES_CMPGN_VEH_CUST_STAT = in.readString(this.DES_CMPGN_VEH_CUST_STAT instanceof Utf8 ? (Utf8)this.DES_CMPGN_VEH_CUST_STAT : null);

      this.DTS_CREA = in.readString(this.DTS_CREA instanceof Utf8 ? (Utf8)this.DTS_CREA : null);

      this.ID_CREA_USER = in.readString(this.ID_CREA_USER instanceof Utf8 ? (Utf8)this.ID_CREA_USER : null);

      this.DTS_LAST_UPDT = in.readString(this.DTS_LAST_UPDT instanceof Utf8 ? (Utf8)this.DTS_LAST_UPDT : null);

      this.ID_LAST_UPDT_USER = in.readString(this.ID_LAST_UPDT_USER instanceof Utf8 ? (Utf8)this.ID_LAST_UPDT_USER : null);

    } else {
      for (int i = 0; i < 6; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.CDE_CMPGN_VEH_CUST_STAT = in.readString(this.CDE_CMPGN_VEH_CUST_STAT instanceof Utf8 ? (Utf8)this.CDE_CMPGN_VEH_CUST_STAT : null);
          break;

        case 1:
          this.DES_CMPGN_VEH_CUST_STAT = in.readString(this.DES_CMPGN_VEH_CUST_STAT instanceof Utf8 ? (Utf8)this.DES_CMPGN_VEH_CUST_STAT : null);
          break;

        case 2:
          this.DTS_CREA = in.readString(this.DTS_CREA instanceof Utf8 ? (Utf8)this.DTS_CREA : null);
          break;

        case 3:
          this.ID_CREA_USER = in.readString(this.ID_CREA_USER instanceof Utf8 ? (Utf8)this.ID_CREA_USER : null);
          break;

        case 4:
          this.DTS_LAST_UPDT = in.readString(this.DTS_LAST_UPDT instanceof Utf8 ? (Utf8)this.DTS_LAST_UPDT : null);
          break;

        case 5:
          this.ID_LAST_UPDT_USER = in.readString(this.ID_LAST_UPDT_USER instanceof Utf8 ? (Utf8)this.ID_LAST_UPDT_USER : null);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










