/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.mbusa.avro.dto;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class VehMstrDTO extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -5136509668162501923L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"VehMstrDTO\",\"namespace\":\"com.mbusa.avro.dto\",\"fields\":[{\"name\":\"ID_FIN\",\"type\":\"string\"},{\"name\":\"ID_NUM_VIN\",\"type\":\"string\"},{\"name\":\"NUM_MODL_YR\",\"type\":\"string\"},{\"name\":\"CDE_MODL_CLS\",\"type\":\"string\"},{\"name\":\"CDE_WRLD_MFR\",\"type\":\"string\"},{\"name\":\"CDE_FIN_BAUREIHE\",\"type\":\"string\"},{\"name\":\"CDE_MODL_SER\",\"type\":\"string\"},{\"name\":\"CDE_STR_PLANT\",\"type\":\"string\"},{\"name\":\"CDE_SER_NUM\",\"type\":\"string\"},{\"name\":\"DES_SLS_MDL\",\"type\":\"string\"},{\"name\":\"NUM_PORD\",\"type\":\"string\"},{\"name\":\"CDE_LTST_VEH_RTL_STAT\",\"type\":\"string\"},{\"name\":\"ID_LTST_DLR\",\"type\":\"string\"},{\"name\":\"DTE_LTST_CUST_RTL_VEH\",\"type\":\"string\"},{\"name\":\"CDE_LTST_SLS_PRI\",\"type\":\"string\"},{\"name\":\"CDE_CTRY\",\"type\":\"string\"},{\"name\":\"DES_WRNTY_MODL\",\"type\":\"string\"},{\"name\":\"IND_WRNTY_VEH_STAT\",\"type\":\"string\"},{\"name\":\"CDE_INV_DLR\",\"type\":\"string\"},{\"name\":\"DTE_REGIS\",\"type\":\"string\"},{\"name\":\"DTE_PROD\",\"type\":\"string\"},{\"name\":\"DTS_CREA\",\"type\":\"string\"},{\"name\":\"ID_CREA_USER\",\"type\":\"string\"},{\"name\":\"DTS_LAST_UPDT\",\"type\":\"string\"},{\"name\":\"ID_LAST_UPDT_USER\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<VehMstrDTO> ENCODER =
      new BinaryMessageEncoder<VehMstrDTO>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<VehMstrDTO> DECODER =
      new BinaryMessageDecoder<VehMstrDTO>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<VehMstrDTO> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<VehMstrDTO> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<VehMstrDTO> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<VehMstrDTO>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this VehMstrDTO to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a VehMstrDTO from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a VehMstrDTO instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static VehMstrDTO fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private java.lang.CharSequence ID_FIN;
   private java.lang.CharSequence ID_NUM_VIN;
   private java.lang.CharSequence NUM_MODL_YR;
   private java.lang.CharSequence CDE_MODL_CLS;
   private java.lang.CharSequence CDE_WRLD_MFR;
   private java.lang.CharSequence CDE_FIN_BAUREIHE;
   private java.lang.CharSequence CDE_MODL_SER;
   private java.lang.CharSequence CDE_STR_PLANT;
   private java.lang.CharSequence CDE_SER_NUM;
   private java.lang.CharSequence DES_SLS_MDL;
   private java.lang.CharSequence NUM_PORD;
   private java.lang.CharSequence CDE_LTST_VEH_RTL_STAT;
   private java.lang.CharSequence ID_LTST_DLR;
   private java.lang.CharSequence DTE_LTST_CUST_RTL_VEH;
   private java.lang.CharSequence CDE_LTST_SLS_PRI;
   private java.lang.CharSequence CDE_CTRY;
   private java.lang.CharSequence DES_WRNTY_MODL;
   private java.lang.CharSequence IND_WRNTY_VEH_STAT;
   private java.lang.CharSequence CDE_INV_DLR;
   private java.lang.CharSequence DTE_REGIS;
   private java.lang.CharSequence DTE_PROD;
   private java.lang.CharSequence DTS_CREA;
   private java.lang.CharSequence ID_CREA_USER;
   private java.lang.CharSequence DTS_LAST_UPDT;
   private java.lang.CharSequence ID_LAST_UPDT_USER;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public VehMstrDTO() {}

  /**
   * All-args constructor.
   * @param ID_FIN The new value for ID_FIN
   * @param ID_NUM_VIN The new value for ID_NUM_VIN
   * @param NUM_MODL_YR The new value for NUM_MODL_YR
   * @param CDE_MODL_CLS The new value for CDE_MODL_CLS
   * @param CDE_WRLD_MFR The new value for CDE_WRLD_MFR
   * @param CDE_FIN_BAUREIHE The new value for CDE_FIN_BAUREIHE
   * @param CDE_MODL_SER The new value for CDE_MODL_SER
   * @param CDE_STR_PLANT The new value for CDE_STR_PLANT
   * @param CDE_SER_NUM The new value for CDE_SER_NUM
   * @param DES_SLS_MDL The new value for DES_SLS_MDL
   * @param NUM_PORD The new value for NUM_PORD
   * @param CDE_LTST_VEH_RTL_STAT The new value for CDE_LTST_VEH_RTL_STAT
   * @param ID_LTST_DLR The new value for ID_LTST_DLR
   * @param DTE_LTST_CUST_RTL_VEH The new value for DTE_LTST_CUST_RTL_VEH
   * @param CDE_LTST_SLS_PRI The new value for CDE_LTST_SLS_PRI
   * @param CDE_CTRY The new value for CDE_CTRY
   * @param DES_WRNTY_MODL The new value for DES_WRNTY_MODL
   * @param IND_WRNTY_VEH_STAT The new value for IND_WRNTY_VEH_STAT
   * @param CDE_INV_DLR The new value for CDE_INV_DLR
   * @param DTE_REGIS The new value for DTE_REGIS
   * @param DTE_PROD The new value for DTE_PROD
   * @param DTS_CREA The new value for DTS_CREA
   * @param ID_CREA_USER The new value for ID_CREA_USER
   * @param DTS_LAST_UPDT The new value for DTS_LAST_UPDT
   * @param ID_LAST_UPDT_USER The new value for ID_LAST_UPDT_USER
   */
  public VehMstrDTO(java.lang.CharSequence ID_FIN, java.lang.CharSequence ID_NUM_VIN, java.lang.CharSequence NUM_MODL_YR, java.lang.CharSequence CDE_MODL_CLS, java.lang.CharSequence CDE_WRLD_MFR, java.lang.CharSequence CDE_FIN_BAUREIHE, java.lang.CharSequence CDE_MODL_SER, java.lang.CharSequence CDE_STR_PLANT, java.lang.CharSequence CDE_SER_NUM, java.lang.CharSequence DES_SLS_MDL, java.lang.CharSequence NUM_PORD, java.lang.CharSequence CDE_LTST_VEH_RTL_STAT, java.lang.CharSequence ID_LTST_DLR, java.lang.CharSequence DTE_LTST_CUST_RTL_VEH, java.lang.CharSequence CDE_LTST_SLS_PRI, java.lang.CharSequence CDE_CTRY, java.lang.CharSequence DES_WRNTY_MODL, java.lang.CharSequence IND_WRNTY_VEH_STAT, java.lang.CharSequence CDE_INV_DLR, java.lang.CharSequence DTE_REGIS, java.lang.CharSequence DTE_PROD, java.lang.CharSequence DTS_CREA, java.lang.CharSequence ID_CREA_USER, java.lang.CharSequence DTS_LAST_UPDT, java.lang.CharSequence ID_LAST_UPDT_USER) {
    this.ID_FIN = ID_FIN;
    this.ID_NUM_VIN = ID_NUM_VIN;
    this.NUM_MODL_YR = NUM_MODL_YR;
    this.CDE_MODL_CLS = CDE_MODL_CLS;
    this.CDE_WRLD_MFR = CDE_WRLD_MFR;
    this.CDE_FIN_BAUREIHE = CDE_FIN_BAUREIHE;
    this.CDE_MODL_SER = CDE_MODL_SER;
    this.CDE_STR_PLANT = CDE_STR_PLANT;
    this.CDE_SER_NUM = CDE_SER_NUM;
    this.DES_SLS_MDL = DES_SLS_MDL;
    this.NUM_PORD = NUM_PORD;
    this.CDE_LTST_VEH_RTL_STAT = CDE_LTST_VEH_RTL_STAT;
    this.ID_LTST_DLR = ID_LTST_DLR;
    this.DTE_LTST_CUST_RTL_VEH = DTE_LTST_CUST_RTL_VEH;
    this.CDE_LTST_SLS_PRI = CDE_LTST_SLS_PRI;
    this.CDE_CTRY = CDE_CTRY;
    this.DES_WRNTY_MODL = DES_WRNTY_MODL;
    this.IND_WRNTY_VEH_STAT = IND_WRNTY_VEH_STAT;
    this.CDE_INV_DLR = CDE_INV_DLR;
    this.DTE_REGIS = DTE_REGIS;
    this.DTE_PROD = DTE_PROD;
    this.DTS_CREA = DTS_CREA;
    this.ID_CREA_USER = ID_CREA_USER;
    this.DTS_LAST_UPDT = DTS_LAST_UPDT;
    this.ID_LAST_UPDT_USER = ID_LAST_UPDT_USER;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return ID_FIN;
    case 1: return ID_NUM_VIN;
    case 2: return NUM_MODL_YR;
    case 3: return CDE_MODL_CLS;
    case 4: return CDE_WRLD_MFR;
    case 5: return CDE_FIN_BAUREIHE;
    case 6: return CDE_MODL_SER;
    case 7: return CDE_STR_PLANT;
    case 8: return CDE_SER_NUM;
    case 9: return DES_SLS_MDL;
    case 10: return NUM_PORD;
    case 11: return CDE_LTST_VEH_RTL_STAT;
    case 12: return ID_LTST_DLR;
    case 13: return DTE_LTST_CUST_RTL_VEH;
    case 14: return CDE_LTST_SLS_PRI;
    case 15: return CDE_CTRY;
    case 16: return DES_WRNTY_MODL;
    case 17: return IND_WRNTY_VEH_STAT;
    case 18: return CDE_INV_DLR;
    case 19: return DTE_REGIS;
    case 20: return DTE_PROD;
    case 21: return DTS_CREA;
    case 22: return ID_CREA_USER;
    case 23: return DTS_LAST_UPDT;
    case 24: return ID_LAST_UPDT_USER;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: ID_FIN = (java.lang.CharSequence)value$; break;
    case 1: ID_NUM_VIN = (java.lang.CharSequence)value$; break;
    case 2: NUM_MODL_YR = (java.lang.CharSequence)value$; break;
    case 3: CDE_MODL_CLS = (java.lang.CharSequence)value$; break;
    case 4: CDE_WRLD_MFR = (java.lang.CharSequence)value$; break;
    case 5: CDE_FIN_BAUREIHE = (java.lang.CharSequence)value$; break;
    case 6: CDE_MODL_SER = (java.lang.CharSequence)value$; break;
    case 7: CDE_STR_PLANT = (java.lang.CharSequence)value$; break;
    case 8: CDE_SER_NUM = (java.lang.CharSequence)value$; break;
    case 9: DES_SLS_MDL = (java.lang.CharSequence)value$; break;
    case 10: NUM_PORD = (java.lang.CharSequence)value$; break;
    case 11: CDE_LTST_VEH_RTL_STAT = (java.lang.CharSequence)value$; break;
    case 12: ID_LTST_DLR = (java.lang.CharSequence)value$; break;
    case 13: DTE_LTST_CUST_RTL_VEH = (java.lang.CharSequence)value$; break;
    case 14: CDE_LTST_SLS_PRI = (java.lang.CharSequence)value$; break;
    case 15: CDE_CTRY = (java.lang.CharSequence)value$; break;
    case 16: DES_WRNTY_MODL = (java.lang.CharSequence)value$; break;
    case 17: IND_WRNTY_VEH_STAT = (java.lang.CharSequence)value$; break;
    case 18: CDE_INV_DLR = (java.lang.CharSequence)value$; break;
    case 19: DTE_REGIS = (java.lang.CharSequence)value$; break;
    case 20: DTE_PROD = (java.lang.CharSequence)value$; break;
    case 21: DTS_CREA = (java.lang.CharSequence)value$; break;
    case 22: ID_CREA_USER = (java.lang.CharSequence)value$; break;
    case 23: DTS_LAST_UPDT = (java.lang.CharSequence)value$; break;
    case 24: ID_LAST_UPDT_USER = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'ID_FIN' field.
   * @return The value of the 'ID_FIN' field.
   */
  public java.lang.CharSequence getIDFIN() {
    return ID_FIN;
  }


  /**
   * Sets the value of the 'ID_FIN' field.
   * @param value the value to set.
   */
  public void setIDFIN(java.lang.CharSequence value) {
    this.ID_FIN = value;
  }

  /**
   * Gets the value of the 'ID_NUM_VIN' field.
   * @return The value of the 'ID_NUM_VIN' field.
   */
  public java.lang.CharSequence getIDNUMVIN() {
    return ID_NUM_VIN;
  }


  /**
   * Sets the value of the 'ID_NUM_VIN' field.
   * @param value the value to set.
   */
  public void setIDNUMVIN(java.lang.CharSequence value) {
    this.ID_NUM_VIN = value;
  }

  /**
   * Gets the value of the 'NUM_MODL_YR' field.
   * @return The value of the 'NUM_MODL_YR' field.
   */
  public java.lang.CharSequence getNUMMODLYR() {
    return NUM_MODL_YR;
  }


  /**
   * Sets the value of the 'NUM_MODL_YR' field.
   * @param value the value to set.
   */
  public void setNUMMODLYR(java.lang.CharSequence value) {
    this.NUM_MODL_YR = value;
  }

  /**
   * Gets the value of the 'CDE_MODL_CLS' field.
   * @return The value of the 'CDE_MODL_CLS' field.
   */
  public java.lang.CharSequence getCDEMODLCLS() {
    return CDE_MODL_CLS;
  }


  /**
   * Sets the value of the 'CDE_MODL_CLS' field.
   * @param value the value to set.
   */
  public void setCDEMODLCLS(java.lang.CharSequence value) {
    this.CDE_MODL_CLS = value;
  }

  /**
   * Gets the value of the 'CDE_WRLD_MFR' field.
   * @return The value of the 'CDE_WRLD_MFR' field.
   */
  public java.lang.CharSequence getCDEWRLDMFR() {
    return CDE_WRLD_MFR;
  }


  /**
   * Sets the value of the 'CDE_WRLD_MFR' field.
   * @param value the value to set.
   */
  public void setCDEWRLDMFR(java.lang.CharSequence value) {
    this.CDE_WRLD_MFR = value;
  }

  /**
   * Gets the value of the 'CDE_FIN_BAUREIHE' field.
   * @return The value of the 'CDE_FIN_BAUREIHE' field.
   */
  public java.lang.CharSequence getCDEFINBAUREIHE() {
    return CDE_FIN_BAUREIHE;
  }


  /**
   * Sets the value of the 'CDE_FIN_BAUREIHE' field.
   * @param value the value to set.
   */
  public void setCDEFINBAUREIHE(java.lang.CharSequence value) {
    this.CDE_FIN_BAUREIHE = value;
  }

  /**
   * Gets the value of the 'CDE_MODL_SER' field.
   * @return The value of the 'CDE_MODL_SER' field.
   */
  public java.lang.CharSequence getCDEMODLSER() {
    return CDE_MODL_SER;
  }


  /**
   * Sets the value of the 'CDE_MODL_SER' field.
   * @param value the value to set.
   */
  public void setCDEMODLSER(java.lang.CharSequence value) {
    this.CDE_MODL_SER = value;
  }

  /**
   * Gets the value of the 'CDE_STR_PLANT' field.
   * @return The value of the 'CDE_STR_PLANT' field.
   */
  public java.lang.CharSequence getCDESTRPLANT() {
    return CDE_STR_PLANT;
  }


  /**
   * Sets the value of the 'CDE_STR_PLANT' field.
   * @param value the value to set.
   */
  public void setCDESTRPLANT(java.lang.CharSequence value) {
    this.CDE_STR_PLANT = value;
  }

  /**
   * Gets the value of the 'CDE_SER_NUM' field.
   * @return The value of the 'CDE_SER_NUM' field.
   */
  public java.lang.CharSequence getCDESERNUM() {
    return CDE_SER_NUM;
  }


  /**
   * Sets the value of the 'CDE_SER_NUM' field.
   * @param value the value to set.
   */
  public void setCDESERNUM(java.lang.CharSequence value) {
    this.CDE_SER_NUM = value;
  }

  /**
   * Gets the value of the 'DES_SLS_MDL' field.
   * @return The value of the 'DES_SLS_MDL' field.
   */
  public java.lang.CharSequence getDESSLSMDL() {
    return DES_SLS_MDL;
  }


  /**
   * Sets the value of the 'DES_SLS_MDL' field.
   * @param value the value to set.
   */
  public void setDESSLSMDL(java.lang.CharSequence value) {
    this.DES_SLS_MDL = value;
  }

  /**
   * Gets the value of the 'NUM_PORD' field.
   * @return The value of the 'NUM_PORD' field.
   */
  public java.lang.CharSequence getNUMPORD() {
    return NUM_PORD;
  }


  /**
   * Sets the value of the 'NUM_PORD' field.
   * @param value the value to set.
   */
  public void setNUMPORD(java.lang.CharSequence value) {
    this.NUM_PORD = value;
  }

  /**
   * Gets the value of the 'CDE_LTST_VEH_RTL_STAT' field.
   * @return The value of the 'CDE_LTST_VEH_RTL_STAT' field.
   */
  public java.lang.CharSequence getCDELTSTVEHRTLSTAT() {
    return CDE_LTST_VEH_RTL_STAT;
  }


  /**
   * Sets the value of the 'CDE_LTST_VEH_RTL_STAT' field.
   * @param value the value to set.
   */
  public void setCDELTSTVEHRTLSTAT(java.lang.CharSequence value) {
    this.CDE_LTST_VEH_RTL_STAT = value;
  }

  /**
   * Gets the value of the 'ID_LTST_DLR' field.
   * @return The value of the 'ID_LTST_DLR' field.
   */
  public java.lang.CharSequence getIDLTSTDLR() {
    return ID_LTST_DLR;
  }


  /**
   * Sets the value of the 'ID_LTST_DLR' field.
   * @param value the value to set.
   */
  public void setIDLTSTDLR(java.lang.CharSequence value) {
    this.ID_LTST_DLR = value;
  }

  /**
   * Gets the value of the 'DTE_LTST_CUST_RTL_VEH' field.
   * @return The value of the 'DTE_LTST_CUST_RTL_VEH' field.
   */
  public java.lang.CharSequence getDTELTSTCUSTRTLVEH() {
    return DTE_LTST_CUST_RTL_VEH;
  }


  /**
   * Sets the value of the 'DTE_LTST_CUST_RTL_VEH' field.
   * @param value the value to set.
   */
  public void setDTELTSTCUSTRTLVEH(java.lang.CharSequence value) {
    this.DTE_LTST_CUST_RTL_VEH = value;
  }

  /**
   * Gets the value of the 'CDE_LTST_SLS_PRI' field.
   * @return The value of the 'CDE_LTST_SLS_PRI' field.
   */
  public java.lang.CharSequence getCDELTSTSLSPRI() {
    return CDE_LTST_SLS_PRI;
  }


  /**
   * Sets the value of the 'CDE_LTST_SLS_PRI' field.
   * @param value the value to set.
   */
  public void setCDELTSTSLSPRI(java.lang.CharSequence value) {
    this.CDE_LTST_SLS_PRI = value;
  }

  /**
   * Gets the value of the 'CDE_CTRY' field.
   * @return The value of the 'CDE_CTRY' field.
   */
  public java.lang.CharSequence getCDECTRY() {
    return CDE_CTRY;
  }


  /**
   * Sets the value of the 'CDE_CTRY' field.
   * @param value the value to set.
   */
  public void setCDECTRY(java.lang.CharSequence value) {
    this.CDE_CTRY = value;
  }

  /**
   * Gets the value of the 'DES_WRNTY_MODL' field.
   * @return The value of the 'DES_WRNTY_MODL' field.
   */
  public java.lang.CharSequence getDESWRNTYMODL() {
    return DES_WRNTY_MODL;
  }


  /**
   * Sets the value of the 'DES_WRNTY_MODL' field.
   * @param value the value to set.
   */
  public void setDESWRNTYMODL(java.lang.CharSequence value) {
    this.DES_WRNTY_MODL = value;
  }

  /**
   * Gets the value of the 'IND_WRNTY_VEH_STAT' field.
   * @return The value of the 'IND_WRNTY_VEH_STAT' field.
   */
  public java.lang.CharSequence getINDWRNTYVEHSTAT() {
    return IND_WRNTY_VEH_STAT;
  }


  /**
   * Sets the value of the 'IND_WRNTY_VEH_STAT' field.
   * @param value the value to set.
   */
  public void setINDWRNTYVEHSTAT(java.lang.CharSequence value) {
    this.IND_WRNTY_VEH_STAT = value;
  }

  /**
   * Gets the value of the 'CDE_INV_DLR' field.
   * @return The value of the 'CDE_INV_DLR' field.
   */
  public java.lang.CharSequence getCDEINVDLR() {
    return CDE_INV_DLR;
  }


  /**
   * Sets the value of the 'CDE_INV_DLR' field.
   * @param value the value to set.
   */
  public void setCDEINVDLR(java.lang.CharSequence value) {
    this.CDE_INV_DLR = value;
  }

  /**
   * Gets the value of the 'DTE_REGIS' field.
   * @return The value of the 'DTE_REGIS' field.
   */
  public java.lang.CharSequence getDTEREGIS() {
    return DTE_REGIS;
  }


  /**
   * Sets the value of the 'DTE_REGIS' field.
   * @param value the value to set.
   */
  public void setDTEREGIS(java.lang.CharSequence value) {
    this.DTE_REGIS = value;
  }

  /**
   * Gets the value of the 'DTE_PROD' field.
   * @return The value of the 'DTE_PROD' field.
   */
  public java.lang.CharSequence getDTEPROD() {
    return DTE_PROD;
  }


  /**
   * Sets the value of the 'DTE_PROD' field.
   * @param value the value to set.
   */
  public void setDTEPROD(java.lang.CharSequence value) {
    this.DTE_PROD = value;
  }

  /**
   * Gets the value of the 'DTS_CREA' field.
   * @return The value of the 'DTS_CREA' field.
   */
  public java.lang.CharSequence getDTSCREA() {
    return DTS_CREA;
  }


  /**
   * Sets the value of the 'DTS_CREA' field.
   * @param value the value to set.
   */
  public void setDTSCREA(java.lang.CharSequence value) {
    this.DTS_CREA = value;
  }

  /**
   * Gets the value of the 'ID_CREA_USER' field.
   * @return The value of the 'ID_CREA_USER' field.
   */
  public java.lang.CharSequence getIDCREAUSER() {
    return ID_CREA_USER;
  }


  /**
   * Sets the value of the 'ID_CREA_USER' field.
   * @param value the value to set.
   */
  public void setIDCREAUSER(java.lang.CharSequence value) {
    this.ID_CREA_USER = value;
  }

  /**
   * Gets the value of the 'DTS_LAST_UPDT' field.
   * @return The value of the 'DTS_LAST_UPDT' field.
   */
  public java.lang.CharSequence getDTSLASTUPDT() {
    return DTS_LAST_UPDT;
  }


  /**
   * Sets the value of the 'DTS_LAST_UPDT' field.
   * @param value the value to set.
   */
  public void setDTSLASTUPDT(java.lang.CharSequence value) {
    this.DTS_LAST_UPDT = value;
  }

  /**
   * Gets the value of the 'ID_LAST_UPDT_USER' field.
   * @return The value of the 'ID_LAST_UPDT_USER' field.
   */
  public java.lang.CharSequence getIDLASTUPDTUSER() {
    return ID_LAST_UPDT_USER;
  }


  /**
   * Sets the value of the 'ID_LAST_UPDT_USER' field.
   * @param value the value to set.
   */
  public void setIDLASTUPDTUSER(java.lang.CharSequence value) {
    this.ID_LAST_UPDT_USER = value;
  }

  /**
   * Creates a new VehMstrDTO RecordBuilder.
   * @return A new VehMstrDTO RecordBuilder
   */
  public static com.mbusa.avro.dto.VehMstrDTO.Builder newBuilder() {
    return new com.mbusa.avro.dto.VehMstrDTO.Builder();
  }

  /**
   * Creates a new VehMstrDTO RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new VehMstrDTO RecordBuilder
   */
  public static com.mbusa.avro.dto.VehMstrDTO.Builder newBuilder(com.mbusa.avro.dto.VehMstrDTO.Builder other) {
    if (other == null) {
      return new com.mbusa.avro.dto.VehMstrDTO.Builder();
    } else {
      return new com.mbusa.avro.dto.VehMstrDTO.Builder(other);
    }
  }

  /**
   * Creates a new VehMstrDTO RecordBuilder by copying an existing VehMstrDTO instance.
   * @param other The existing instance to copy.
   * @return A new VehMstrDTO RecordBuilder
   */
  public static com.mbusa.avro.dto.VehMstrDTO.Builder newBuilder(com.mbusa.avro.dto.VehMstrDTO other) {
    if (other == null) {
      return new com.mbusa.avro.dto.VehMstrDTO.Builder();
    } else {
      return new com.mbusa.avro.dto.VehMstrDTO.Builder(other);
    }
  }

  /**
   * RecordBuilder for VehMstrDTO instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<VehMstrDTO>
    implements org.apache.avro.data.RecordBuilder<VehMstrDTO> {

    private java.lang.CharSequence ID_FIN;
    private java.lang.CharSequence ID_NUM_VIN;
    private java.lang.CharSequence NUM_MODL_YR;
    private java.lang.CharSequence CDE_MODL_CLS;
    private java.lang.CharSequence CDE_WRLD_MFR;
    private java.lang.CharSequence CDE_FIN_BAUREIHE;
    private java.lang.CharSequence CDE_MODL_SER;
    private java.lang.CharSequence CDE_STR_PLANT;
    private java.lang.CharSequence CDE_SER_NUM;
    private java.lang.CharSequence DES_SLS_MDL;
    private java.lang.CharSequence NUM_PORD;
    private java.lang.CharSequence CDE_LTST_VEH_RTL_STAT;
    private java.lang.CharSequence ID_LTST_DLR;
    private java.lang.CharSequence DTE_LTST_CUST_RTL_VEH;
    private java.lang.CharSequence CDE_LTST_SLS_PRI;
    private java.lang.CharSequence CDE_CTRY;
    private java.lang.CharSequence DES_WRNTY_MODL;
    private java.lang.CharSequence IND_WRNTY_VEH_STAT;
    private java.lang.CharSequence CDE_INV_DLR;
    private java.lang.CharSequence DTE_REGIS;
    private java.lang.CharSequence DTE_PROD;
    private java.lang.CharSequence DTS_CREA;
    private java.lang.CharSequence ID_CREA_USER;
    private java.lang.CharSequence DTS_LAST_UPDT;
    private java.lang.CharSequence ID_LAST_UPDT_USER;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.mbusa.avro.dto.VehMstrDTO.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.ID_FIN)) {
        this.ID_FIN = data().deepCopy(fields()[0].schema(), other.ID_FIN);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.ID_NUM_VIN)) {
        this.ID_NUM_VIN = data().deepCopy(fields()[1].schema(), other.ID_NUM_VIN);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.NUM_MODL_YR)) {
        this.NUM_MODL_YR = data().deepCopy(fields()[2].schema(), other.NUM_MODL_YR);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.CDE_MODL_CLS)) {
        this.CDE_MODL_CLS = data().deepCopy(fields()[3].schema(), other.CDE_MODL_CLS);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.CDE_WRLD_MFR)) {
        this.CDE_WRLD_MFR = data().deepCopy(fields()[4].schema(), other.CDE_WRLD_MFR);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.CDE_FIN_BAUREIHE)) {
        this.CDE_FIN_BAUREIHE = data().deepCopy(fields()[5].schema(), other.CDE_FIN_BAUREIHE);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.CDE_MODL_SER)) {
        this.CDE_MODL_SER = data().deepCopy(fields()[6].schema(), other.CDE_MODL_SER);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
      if (isValidValue(fields()[7], other.CDE_STR_PLANT)) {
        this.CDE_STR_PLANT = data().deepCopy(fields()[7].schema(), other.CDE_STR_PLANT);
        fieldSetFlags()[7] = other.fieldSetFlags()[7];
      }
      if (isValidValue(fields()[8], other.CDE_SER_NUM)) {
        this.CDE_SER_NUM = data().deepCopy(fields()[8].schema(), other.CDE_SER_NUM);
        fieldSetFlags()[8] = other.fieldSetFlags()[8];
      }
      if (isValidValue(fields()[9], other.DES_SLS_MDL)) {
        this.DES_SLS_MDL = data().deepCopy(fields()[9].schema(), other.DES_SLS_MDL);
        fieldSetFlags()[9] = other.fieldSetFlags()[9];
      }
      if (isValidValue(fields()[10], other.NUM_PORD)) {
        this.NUM_PORD = data().deepCopy(fields()[10].schema(), other.NUM_PORD);
        fieldSetFlags()[10] = other.fieldSetFlags()[10];
      }
      if (isValidValue(fields()[11], other.CDE_LTST_VEH_RTL_STAT)) {
        this.CDE_LTST_VEH_RTL_STAT = data().deepCopy(fields()[11].schema(), other.CDE_LTST_VEH_RTL_STAT);
        fieldSetFlags()[11] = other.fieldSetFlags()[11];
      }
      if (isValidValue(fields()[12], other.ID_LTST_DLR)) {
        this.ID_LTST_DLR = data().deepCopy(fields()[12].schema(), other.ID_LTST_DLR);
        fieldSetFlags()[12] = other.fieldSetFlags()[12];
      }
      if (isValidValue(fields()[13], other.DTE_LTST_CUST_RTL_VEH)) {
        this.DTE_LTST_CUST_RTL_VEH = data().deepCopy(fields()[13].schema(), other.DTE_LTST_CUST_RTL_VEH);
        fieldSetFlags()[13] = other.fieldSetFlags()[13];
      }
      if (isValidValue(fields()[14], other.CDE_LTST_SLS_PRI)) {
        this.CDE_LTST_SLS_PRI = data().deepCopy(fields()[14].schema(), other.CDE_LTST_SLS_PRI);
        fieldSetFlags()[14] = other.fieldSetFlags()[14];
      }
      if (isValidValue(fields()[15], other.CDE_CTRY)) {
        this.CDE_CTRY = data().deepCopy(fields()[15].schema(), other.CDE_CTRY);
        fieldSetFlags()[15] = other.fieldSetFlags()[15];
      }
      if (isValidValue(fields()[16], other.DES_WRNTY_MODL)) {
        this.DES_WRNTY_MODL = data().deepCopy(fields()[16].schema(), other.DES_WRNTY_MODL);
        fieldSetFlags()[16] = other.fieldSetFlags()[16];
      }
      if (isValidValue(fields()[17], other.IND_WRNTY_VEH_STAT)) {
        this.IND_WRNTY_VEH_STAT = data().deepCopy(fields()[17].schema(), other.IND_WRNTY_VEH_STAT);
        fieldSetFlags()[17] = other.fieldSetFlags()[17];
      }
      if (isValidValue(fields()[18], other.CDE_INV_DLR)) {
        this.CDE_INV_DLR = data().deepCopy(fields()[18].schema(), other.CDE_INV_DLR);
        fieldSetFlags()[18] = other.fieldSetFlags()[18];
      }
      if (isValidValue(fields()[19], other.DTE_REGIS)) {
        this.DTE_REGIS = data().deepCopy(fields()[19].schema(), other.DTE_REGIS);
        fieldSetFlags()[19] = other.fieldSetFlags()[19];
      }
      if (isValidValue(fields()[20], other.DTE_PROD)) {
        this.DTE_PROD = data().deepCopy(fields()[20].schema(), other.DTE_PROD);
        fieldSetFlags()[20] = other.fieldSetFlags()[20];
      }
      if (isValidValue(fields()[21], other.DTS_CREA)) {
        this.DTS_CREA = data().deepCopy(fields()[21].schema(), other.DTS_CREA);
        fieldSetFlags()[21] = other.fieldSetFlags()[21];
      }
      if (isValidValue(fields()[22], other.ID_CREA_USER)) {
        this.ID_CREA_USER = data().deepCopy(fields()[22].schema(), other.ID_CREA_USER);
        fieldSetFlags()[22] = other.fieldSetFlags()[22];
      }
      if (isValidValue(fields()[23], other.DTS_LAST_UPDT)) {
        this.DTS_LAST_UPDT = data().deepCopy(fields()[23].schema(), other.DTS_LAST_UPDT);
        fieldSetFlags()[23] = other.fieldSetFlags()[23];
      }
      if (isValidValue(fields()[24], other.ID_LAST_UPDT_USER)) {
        this.ID_LAST_UPDT_USER = data().deepCopy(fields()[24].schema(), other.ID_LAST_UPDT_USER);
        fieldSetFlags()[24] = other.fieldSetFlags()[24];
      }
    }

    /**
     * Creates a Builder by copying an existing VehMstrDTO instance
     * @param other The existing instance to copy.
     */
    private Builder(com.mbusa.avro.dto.VehMstrDTO other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.ID_FIN)) {
        this.ID_FIN = data().deepCopy(fields()[0].schema(), other.ID_FIN);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.ID_NUM_VIN)) {
        this.ID_NUM_VIN = data().deepCopy(fields()[1].schema(), other.ID_NUM_VIN);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.NUM_MODL_YR)) {
        this.NUM_MODL_YR = data().deepCopy(fields()[2].schema(), other.NUM_MODL_YR);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.CDE_MODL_CLS)) {
        this.CDE_MODL_CLS = data().deepCopy(fields()[3].schema(), other.CDE_MODL_CLS);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.CDE_WRLD_MFR)) {
        this.CDE_WRLD_MFR = data().deepCopy(fields()[4].schema(), other.CDE_WRLD_MFR);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.CDE_FIN_BAUREIHE)) {
        this.CDE_FIN_BAUREIHE = data().deepCopy(fields()[5].schema(), other.CDE_FIN_BAUREIHE);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.CDE_MODL_SER)) {
        this.CDE_MODL_SER = data().deepCopy(fields()[6].schema(), other.CDE_MODL_SER);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.CDE_STR_PLANT)) {
        this.CDE_STR_PLANT = data().deepCopy(fields()[7].schema(), other.CDE_STR_PLANT);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.CDE_SER_NUM)) {
        this.CDE_SER_NUM = data().deepCopy(fields()[8].schema(), other.CDE_SER_NUM);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.DES_SLS_MDL)) {
        this.DES_SLS_MDL = data().deepCopy(fields()[9].schema(), other.DES_SLS_MDL);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.NUM_PORD)) {
        this.NUM_PORD = data().deepCopy(fields()[10].schema(), other.NUM_PORD);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.CDE_LTST_VEH_RTL_STAT)) {
        this.CDE_LTST_VEH_RTL_STAT = data().deepCopy(fields()[11].schema(), other.CDE_LTST_VEH_RTL_STAT);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.ID_LTST_DLR)) {
        this.ID_LTST_DLR = data().deepCopy(fields()[12].schema(), other.ID_LTST_DLR);
        fieldSetFlags()[12] = true;
      }
      if (isValidValue(fields()[13], other.DTE_LTST_CUST_RTL_VEH)) {
        this.DTE_LTST_CUST_RTL_VEH = data().deepCopy(fields()[13].schema(), other.DTE_LTST_CUST_RTL_VEH);
        fieldSetFlags()[13] = true;
      }
      if (isValidValue(fields()[14], other.CDE_LTST_SLS_PRI)) {
        this.CDE_LTST_SLS_PRI = data().deepCopy(fields()[14].schema(), other.CDE_LTST_SLS_PRI);
        fieldSetFlags()[14] = true;
      }
      if (isValidValue(fields()[15], other.CDE_CTRY)) {
        this.CDE_CTRY = data().deepCopy(fields()[15].schema(), other.CDE_CTRY);
        fieldSetFlags()[15] = true;
      }
      if (isValidValue(fields()[16], other.DES_WRNTY_MODL)) {
        this.DES_WRNTY_MODL = data().deepCopy(fields()[16].schema(), other.DES_WRNTY_MODL);
        fieldSetFlags()[16] = true;
      }
      if (isValidValue(fields()[17], other.IND_WRNTY_VEH_STAT)) {
        this.IND_WRNTY_VEH_STAT = data().deepCopy(fields()[17].schema(), other.IND_WRNTY_VEH_STAT);
        fieldSetFlags()[17] = true;
      }
      if (isValidValue(fields()[18], other.CDE_INV_DLR)) {
        this.CDE_INV_DLR = data().deepCopy(fields()[18].schema(), other.CDE_INV_DLR);
        fieldSetFlags()[18] = true;
      }
      if (isValidValue(fields()[19], other.DTE_REGIS)) {
        this.DTE_REGIS = data().deepCopy(fields()[19].schema(), other.DTE_REGIS);
        fieldSetFlags()[19] = true;
      }
      if (isValidValue(fields()[20], other.DTE_PROD)) {
        this.DTE_PROD = data().deepCopy(fields()[20].schema(), other.DTE_PROD);
        fieldSetFlags()[20] = true;
      }
      if (isValidValue(fields()[21], other.DTS_CREA)) {
        this.DTS_CREA = data().deepCopy(fields()[21].schema(), other.DTS_CREA);
        fieldSetFlags()[21] = true;
      }
      if (isValidValue(fields()[22], other.ID_CREA_USER)) {
        this.ID_CREA_USER = data().deepCopy(fields()[22].schema(), other.ID_CREA_USER);
        fieldSetFlags()[22] = true;
      }
      if (isValidValue(fields()[23], other.DTS_LAST_UPDT)) {
        this.DTS_LAST_UPDT = data().deepCopy(fields()[23].schema(), other.DTS_LAST_UPDT);
        fieldSetFlags()[23] = true;
      }
      if (isValidValue(fields()[24], other.ID_LAST_UPDT_USER)) {
        this.ID_LAST_UPDT_USER = data().deepCopy(fields()[24].schema(), other.ID_LAST_UPDT_USER);
        fieldSetFlags()[24] = true;
      }
    }

    /**
      * Gets the value of the 'ID_FIN' field.
      * @return The value.
      */
    public java.lang.CharSequence getIDFIN() {
      return ID_FIN;
    }


    /**
      * Sets the value of the 'ID_FIN' field.
      * @param value The value of 'ID_FIN'.
      * @return This builder.
      */
    public com.mbusa.avro.dto.VehMstrDTO.Builder setIDFIN(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.ID_FIN = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'ID_FIN' field has been set.
      * @return True if the 'ID_FIN' field has been set, false otherwise.
      */
    public boolean hasIDFIN() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'ID_FIN' field.
      * @return This builder.
      */
    public com.mbusa.avro.dto.VehMstrDTO.Builder clearIDFIN() {
      ID_FIN = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'ID_NUM_VIN' field.
      * @return The value.
      */
    public java.lang.CharSequence getIDNUMVIN() {
      return ID_NUM_VIN;
    }


    /**
      * Sets the value of the 'ID_NUM_VIN' field.
      * @param value The value of 'ID_NUM_VIN'.
      * @return This builder.
      */
    public com.mbusa.avro.dto.VehMstrDTO.Builder setIDNUMVIN(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.ID_NUM_VIN = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'ID_NUM_VIN' field has been set.
      * @return True if the 'ID_NUM_VIN' field has been set, false otherwise.
      */
    public boolean hasIDNUMVIN() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'ID_NUM_VIN' field.
      * @return This builder.
      */
    public com.mbusa.avro.dto.VehMstrDTO.Builder clearIDNUMVIN() {
      ID_NUM_VIN = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'NUM_MODL_YR' field.
      * @return The value.
      */
    public java.lang.CharSequence getNUMMODLYR() {
      return NUM_MODL_YR;
    }


    /**
      * Sets the value of the 'NUM_MODL_YR' field.
      * @param value The value of 'NUM_MODL_YR'.
      * @return This builder.
      */
    public com.mbusa.avro.dto.VehMstrDTO.Builder setNUMMODLYR(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.NUM_MODL_YR = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'NUM_MODL_YR' field has been set.
      * @return True if the 'NUM_MODL_YR' field has been set, false otherwise.
      */
    public boolean hasNUMMODLYR() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'NUM_MODL_YR' field.
      * @return This builder.
      */
    public com.mbusa.avro.dto.VehMstrDTO.Builder clearNUMMODLYR() {
      NUM_MODL_YR = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'CDE_MODL_CLS' field.
      * @return The value.
      */
    public java.lang.CharSequence getCDEMODLCLS() {
      return CDE_MODL_CLS;
    }


    /**
      * Sets the value of the 'CDE_MODL_CLS' field.
      * @param value The value of 'CDE_MODL_CLS'.
      * @return This builder.
      */
    public com.mbusa.avro.dto.VehMstrDTO.Builder setCDEMODLCLS(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.CDE_MODL_CLS = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'CDE_MODL_CLS' field has been set.
      * @return True if the 'CDE_MODL_CLS' field has been set, false otherwise.
      */
    public boolean hasCDEMODLCLS() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'CDE_MODL_CLS' field.
      * @return This builder.
      */
    public com.mbusa.avro.dto.VehMstrDTO.Builder clearCDEMODLCLS() {
      CDE_MODL_CLS = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'CDE_WRLD_MFR' field.
      * @return The value.
      */
    public java.lang.CharSequence getCDEWRLDMFR() {
      return CDE_WRLD_MFR;
    }


    /**
      * Sets the value of the 'CDE_WRLD_MFR' field.
      * @param value The value of 'CDE_WRLD_MFR'.
      * @return This builder.
      */
    public com.mbusa.avro.dto.VehMstrDTO.Builder setCDEWRLDMFR(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.CDE_WRLD_MFR = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'CDE_WRLD_MFR' field has been set.
      * @return True if the 'CDE_WRLD_MFR' field has been set, false otherwise.
      */
    public boolean hasCDEWRLDMFR() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'CDE_WRLD_MFR' field.
      * @return This builder.
      */
    public com.mbusa.avro.dto.VehMstrDTO.Builder clearCDEWRLDMFR() {
      CDE_WRLD_MFR = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'CDE_FIN_BAUREIHE' field.
      * @return The value.
      */
    public java.lang.CharSequence getCDEFINBAUREIHE() {
      return CDE_FIN_BAUREIHE;
    }


    /**
      * Sets the value of the 'CDE_FIN_BAUREIHE' field.
      * @param value The value of 'CDE_FIN_BAUREIHE'.
      * @return This builder.
      */
    public com.mbusa.avro.dto.VehMstrDTO.Builder setCDEFINBAUREIHE(java.lang.CharSequence value) {
      validate(fields()[5], value);
      this.CDE_FIN_BAUREIHE = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'CDE_FIN_BAUREIHE' field has been set.
      * @return True if the 'CDE_FIN_BAUREIHE' field has been set, false otherwise.
      */
    public boolean hasCDEFINBAUREIHE() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'CDE_FIN_BAUREIHE' field.
      * @return This builder.
      */
    public com.mbusa.avro.dto.VehMstrDTO.Builder clearCDEFINBAUREIHE() {
      CDE_FIN_BAUREIHE = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'CDE_MODL_SER' field.
      * @return The value.
      */
    public java.lang.CharSequence getCDEMODLSER() {
      return CDE_MODL_SER;
    }


    /**
      * Sets the value of the 'CDE_MODL_SER' field.
      * @param value The value of 'CDE_MODL_SER'.
      * @return This builder.
      */
    public com.mbusa.avro.dto.VehMstrDTO.Builder setCDEMODLSER(java.lang.CharSequence value) {
      validate(fields()[6], value);
      this.CDE_MODL_SER = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'CDE_MODL_SER' field has been set.
      * @return True if the 'CDE_MODL_SER' field has been set, false otherwise.
      */
    public boolean hasCDEMODLSER() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'CDE_MODL_SER' field.
      * @return This builder.
      */
    public com.mbusa.avro.dto.VehMstrDTO.Builder clearCDEMODLSER() {
      CDE_MODL_SER = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'CDE_STR_PLANT' field.
      * @return The value.
      */
    public java.lang.CharSequence getCDESTRPLANT() {
      return CDE_STR_PLANT;
    }


    /**
      * Sets the value of the 'CDE_STR_PLANT' field.
      * @param value The value of 'CDE_STR_PLANT'.
      * @return This builder.
      */
    public com.mbusa.avro.dto.VehMstrDTO.Builder setCDESTRPLANT(java.lang.CharSequence value) {
      validate(fields()[7], value);
      this.CDE_STR_PLANT = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'CDE_STR_PLANT' field has been set.
      * @return True if the 'CDE_STR_PLANT' field has been set, false otherwise.
      */
    public boolean hasCDESTRPLANT() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'CDE_STR_PLANT' field.
      * @return This builder.
      */
    public com.mbusa.avro.dto.VehMstrDTO.Builder clearCDESTRPLANT() {
      CDE_STR_PLANT = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    /**
      * Gets the value of the 'CDE_SER_NUM' field.
      * @return The value.
      */
    public java.lang.CharSequence getCDESERNUM() {
      return CDE_SER_NUM;
    }


    /**
      * Sets the value of the 'CDE_SER_NUM' field.
      * @param value The value of 'CDE_SER_NUM'.
      * @return This builder.
      */
    public com.mbusa.avro.dto.VehMstrDTO.Builder setCDESERNUM(java.lang.CharSequence value) {
      validate(fields()[8], value);
      this.CDE_SER_NUM = value;
      fieldSetFlags()[8] = true;
      return this;
    }

    /**
      * Checks whether the 'CDE_SER_NUM' field has been set.
      * @return True if the 'CDE_SER_NUM' field has been set, false otherwise.
      */
    public boolean hasCDESERNUM() {
      return fieldSetFlags()[8];
    }


    /**
      * Clears the value of the 'CDE_SER_NUM' field.
      * @return This builder.
      */
    public com.mbusa.avro.dto.VehMstrDTO.Builder clearCDESERNUM() {
      CDE_SER_NUM = null;
      fieldSetFlags()[8] = false;
      return this;
    }

    /**
      * Gets the value of the 'DES_SLS_MDL' field.
      * @return The value.
      */
    public java.lang.CharSequence getDESSLSMDL() {
      return DES_SLS_MDL;
    }


    /**
      * Sets the value of the 'DES_SLS_MDL' field.
      * @param value The value of 'DES_SLS_MDL'.
      * @return This builder.
      */
    public com.mbusa.avro.dto.VehMstrDTO.Builder setDESSLSMDL(java.lang.CharSequence value) {
      validate(fields()[9], value);
      this.DES_SLS_MDL = value;
      fieldSetFlags()[9] = true;
      return this;
    }

    /**
      * Checks whether the 'DES_SLS_MDL' field has been set.
      * @return True if the 'DES_SLS_MDL' field has been set, false otherwise.
      */
    public boolean hasDESSLSMDL() {
      return fieldSetFlags()[9];
    }


    /**
      * Clears the value of the 'DES_SLS_MDL' field.
      * @return This builder.
      */
    public com.mbusa.avro.dto.VehMstrDTO.Builder clearDESSLSMDL() {
      DES_SLS_MDL = null;
      fieldSetFlags()[9] = false;
      return this;
    }

    /**
      * Gets the value of the 'NUM_PORD' field.
      * @return The value.
      */
    public java.lang.CharSequence getNUMPORD() {
      return NUM_PORD;
    }


    /**
      * Sets the value of the 'NUM_PORD' field.
      * @param value The value of 'NUM_PORD'.
      * @return This builder.
      */
    public com.mbusa.avro.dto.VehMstrDTO.Builder setNUMPORD(java.lang.CharSequence value) {
      validate(fields()[10], value);
      this.NUM_PORD = value;
      fieldSetFlags()[10] = true;
      return this;
    }

    /**
      * Checks whether the 'NUM_PORD' field has been set.
      * @return True if the 'NUM_PORD' field has been set, false otherwise.
      */
    public boolean hasNUMPORD() {
      return fieldSetFlags()[10];
    }


    /**
      * Clears the value of the 'NUM_PORD' field.
      * @return This builder.
      */
    public com.mbusa.avro.dto.VehMstrDTO.Builder clearNUMPORD() {
      NUM_PORD = null;
      fieldSetFlags()[10] = false;
      return this;
    }

    /**
      * Gets the value of the 'CDE_LTST_VEH_RTL_STAT' field.
      * @return The value.
      */
    public java.lang.CharSequence getCDELTSTVEHRTLSTAT() {
      return CDE_LTST_VEH_RTL_STAT;
    }


    /**
      * Sets the value of the 'CDE_LTST_VEH_RTL_STAT' field.
      * @param value The value of 'CDE_LTST_VEH_RTL_STAT'.
      * @return This builder.
      */
    public com.mbusa.avro.dto.VehMstrDTO.Builder setCDELTSTVEHRTLSTAT(java.lang.CharSequence value) {
      validate(fields()[11], value);
      this.CDE_LTST_VEH_RTL_STAT = value;
      fieldSetFlags()[11] = true;
      return this;
    }

    /**
      * Checks whether the 'CDE_LTST_VEH_RTL_STAT' field has been set.
      * @return True if the 'CDE_LTST_VEH_RTL_STAT' field has been set, false otherwise.
      */
    public boolean hasCDELTSTVEHRTLSTAT() {
      return fieldSetFlags()[11];
    }


    /**
      * Clears the value of the 'CDE_LTST_VEH_RTL_STAT' field.
      * @return This builder.
      */
    public com.mbusa.avro.dto.VehMstrDTO.Builder clearCDELTSTVEHRTLSTAT() {
      CDE_LTST_VEH_RTL_STAT = null;
      fieldSetFlags()[11] = false;
      return this;
    }

    /**
      * Gets the value of the 'ID_LTST_DLR' field.
      * @return The value.
      */
    public java.lang.CharSequence getIDLTSTDLR() {
      return ID_LTST_DLR;
    }


    /**
      * Sets the value of the 'ID_LTST_DLR' field.
      * @param value The value of 'ID_LTST_DLR'.
      * @return This builder.
      */
    public com.mbusa.avro.dto.VehMstrDTO.Builder setIDLTSTDLR(java.lang.CharSequence value) {
      validate(fields()[12], value);
      this.ID_LTST_DLR = value;
      fieldSetFlags()[12] = true;
      return this;
    }

    /**
      * Checks whether the 'ID_LTST_DLR' field has been set.
      * @return True if the 'ID_LTST_DLR' field has been set, false otherwise.
      */
    public boolean hasIDLTSTDLR() {
      return fieldSetFlags()[12];
    }


    /**
      * Clears the value of the 'ID_LTST_DLR' field.
      * @return This builder.
      */
    public com.mbusa.avro.dto.VehMstrDTO.Builder clearIDLTSTDLR() {
      ID_LTST_DLR = null;
      fieldSetFlags()[12] = false;
      return this;
    }

    /**
      * Gets the value of the 'DTE_LTST_CUST_RTL_VEH' field.
      * @return The value.
      */
    public java.lang.CharSequence getDTELTSTCUSTRTLVEH() {
      return DTE_LTST_CUST_RTL_VEH;
    }


    /**
      * Sets the value of the 'DTE_LTST_CUST_RTL_VEH' field.
      * @param value The value of 'DTE_LTST_CUST_RTL_VEH'.
      * @return This builder.
      */
    public com.mbusa.avro.dto.VehMstrDTO.Builder setDTELTSTCUSTRTLVEH(java.lang.CharSequence value) {
      validate(fields()[13], value);
      this.DTE_LTST_CUST_RTL_VEH = value;
      fieldSetFlags()[13] = true;
      return this;
    }

    /**
      * Checks whether the 'DTE_LTST_CUST_RTL_VEH' field has been set.
      * @return True if the 'DTE_LTST_CUST_RTL_VEH' field has been set, false otherwise.
      */
    public boolean hasDTELTSTCUSTRTLVEH() {
      return fieldSetFlags()[13];
    }


    /**
      * Clears the value of the 'DTE_LTST_CUST_RTL_VEH' field.
      * @return This builder.
      */
    public com.mbusa.avro.dto.VehMstrDTO.Builder clearDTELTSTCUSTRTLVEH() {
      DTE_LTST_CUST_RTL_VEH = null;
      fieldSetFlags()[13] = false;
      return this;
    }

    /**
      * Gets the value of the 'CDE_LTST_SLS_PRI' field.
      * @return The value.
      */
    public java.lang.CharSequence getCDELTSTSLSPRI() {
      return CDE_LTST_SLS_PRI;
    }


    /**
      * Sets the value of the 'CDE_LTST_SLS_PRI' field.
      * @param value The value of 'CDE_LTST_SLS_PRI'.
      * @return This builder.
      */
    public com.mbusa.avro.dto.VehMstrDTO.Builder setCDELTSTSLSPRI(java.lang.CharSequence value) {
      validate(fields()[14], value);
      this.CDE_LTST_SLS_PRI = value;
      fieldSetFlags()[14] = true;
      return this;
    }

    /**
      * Checks whether the 'CDE_LTST_SLS_PRI' field has been set.
      * @return True if the 'CDE_LTST_SLS_PRI' field has been set, false otherwise.
      */
    public boolean hasCDELTSTSLSPRI() {
      return fieldSetFlags()[14];
    }


    /**
      * Clears the value of the 'CDE_LTST_SLS_PRI' field.
      * @return This builder.
      */
    public com.mbusa.avro.dto.VehMstrDTO.Builder clearCDELTSTSLSPRI() {
      CDE_LTST_SLS_PRI = null;
      fieldSetFlags()[14] = false;
      return this;
    }

    /**
      * Gets the value of the 'CDE_CTRY' field.
      * @return The value.
      */
    public java.lang.CharSequence getCDECTRY() {
      return CDE_CTRY;
    }


    /**
      * Sets the value of the 'CDE_CTRY' field.
      * @param value The value of 'CDE_CTRY'.
      * @return This builder.
      */
    public com.mbusa.avro.dto.VehMstrDTO.Builder setCDECTRY(java.lang.CharSequence value) {
      validate(fields()[15], value);
      this.CDE_CTRY = value;
      fieldSetFlags()[15] = true;
      return this;
    }

    /**
      * Checks whether the 'CDE_CTRY' field has been set.
      * @return True if the 'CDE_CTRY' field has been set, false otherwise.
      */
    public boolean hasCDECTRY() {
      return fieldSetFlags()[15];
    }


    /**
      * Clears the value of the 'CDE_CTRY' field.
      * @return This builder.
      */
    public com.mbusa.avro.dto.VehMstrDTO.Builder clearCDECTRY() {
      CDE_CTRY = null;
      fieldSetFlags()[15] = false;
      return this;
    }

    /**
      * Gets the value of the 'DES_WRNTY_MODL' field.
      * @return The value.
      */
    public java.lang.CharSequence getDESWRNTYMODL() {
      return DES_WRNTY_MODL;
    }


    /**
      * Sets the value of the 'DES_WRNTY_MODL' field.
      * @param value The value of 'DES_WRNTY_MODL'.
      * @return This builder.
      */
    public com.mbusa.avro.dto.VehMstrDTO.Builder setDESWRNTYMODL(java.lang.CharSequence value) {
      validate(fields()[16], value);
      this.DES_WRNTY_MODL = value;
      fieldSetFlags()[16] = true;
      return this;
    }

    /**
      * Checks whether the 'DES_WRNTY_MODL' field has been set.
      * @return True if the 'DES_WRNTY_MODL' field has been set, false otherwise.
      */
    public boolean hasDESWRNTYMODL() {
      return fieldSetFlags()[16];
    }


    /**
      * Clears the value of the 'DES_WRNTY_MODL' field.
      * @return This builder.
      */
    public com.mbusa.avro.dto.VehMstrDTO.Builder clearDESWRNTYMODL() {
      DES_WRNTY_MODL = null;
      fieldSetFlags()[16] = false;
      return this;
    }

    /**
      * Gets the value of the 'IND_WRNTY_VEH_STAT' field.
      * @return The value.
      */
    public java.lang.CharSequence getINDWRNTYVEHSTAT() {
      return IND_WRNTY_VEH_STAT;
    }


    /**
      * Sets the value of the 'IND_WRNTY_VEH_STAT' field.
      * @param value The value of 'IND_WRNTY_VEH_STAT'.
      * @return This builder.
      */
    public com.mbusa.avro.dto.VehMstrDTO.Builder setINDWRNTYVEHSTAT(java.lang.CharSequence value) {
      validate(fields()[17], value);
      this.IND_WRNTY_VEH_STAT = value;
      fieldSetFlags()[17] = true;
      return this;
    }

    /**
      * Checks whether the 'IND_WRNTY_VEH_STAT' field has been set.
      * @return True if the 'IND_WRNTY_VEH_STAT' field has been set, false otherwise.
      */
    public boolean hasINDWRNTYVEHSTAT() {
      return fieldSetFlags()[17];
    }


    /**
      * Clears the value of the 'IND_WRNTY_VEH_STAT' field.
      * @return This builder.
      */
    public com.mbusa.avro.dto.VehMstrDTO.Builder clearINDWRNTYVEHSTAT() {
      IND_WRNTY_VEH_STAT = null;
      fieldSetFlags()[17] = false;
      return this;
    }

    /**
      * Gets the value of the 'CDE_INV_DLR' field.
      * @return The value.
      */
    public java.lang.CharSequence getCDEINVDLR() {
      return CDE_INV_DLR;
    }


    /**
      * Sets the value of the 'CDE_INV_DLR' field.
      * @param value The value of 'CDE_INV_DLR'.
      * @return This builder.
      */
    public com.mbusa.avro.dto.VehMstrDTO.Builder setCDEINVDLR(java.lang.CharSequence value) {
      validate(fields()[18], value);
      this.CDE_INV_DLR = value;
      fieldSetFlags()[18] = true;
      return this;
    }

    /**
      * Checks whether the 'CDE_INV_DLR' field has been set.
      * @return True if the 'CDE_INV_DLR' field has been set, false otherwise.
      */
    public boolean hasCDEINVDLR() {
      return fieldSetFlags()[18];
    }


    /**
      * Clears the value of the 'CDE_INV_DLR' field.
      * @return This builder.
      */
    public com.mbusa.avro.dto.VehMstrDTO.Builder clearCDEINVDLR() {
      CDE_INV_DLR = null;
      fieldSetFlags()[18] = false;
      return this;
    }

    /**
      * Gets the value of the 'DTE_REGIS' field.
      * @return The value.
      */
    public java.lang.CharSequence getDTEREGIS() {
      return DTE_REGIS;
    }


    /**
      * Sets the value of the 'DTE_REGIS' field.
      * @param value The value of 'DTE_REGIS'.
      * @return This builder.
      */
    public com.mbusa.avro.dto.VehMstrDTO.Builder setDTEREGIS(java.lang.CharSequence value) {
      validate(fields()[19], value);
      this.DTE_REGIS = value;
      fieldSetFlags()[19] = true;
      return this;
    }

    /**
      * Checks whether the 'DTE_REGIS' field has been set.
      * @return True if the 'DTE_REGIS' field has been set, false otherwise.
      */
    public boolean hasDTEREGIS() {
      return fieldSetFlags()[19];
    }


    /**
      * Clears the value of the 'DTE_REGIS' field.
      * @return This builder.
      */
    public com.mbusa.avro.dto.VehMstrDTO.Builder clearDTEREGIS() {
      DTE_REGIS = null;
      fieldSetFlags()[19] = false;
      return this;
    }

    /**
      * Gets the value of the 'DTE_PROD' field.
      * @return The value.
      */
    public java.lang.CharSequence getDTEPROD() {
      return DTE_PROD;
    }


    /**
      * Sets the value of the 'DTE_PROD' field.
      * @param value The value of 'DTE_PROD'.
      * @return This builder.
      */
    public com.mbusa.avro.dto.VehMstrDTO.Builder setDTEPROD(java.lang.CharSequence value) {
      validate(fields()[20], value);
      this.DTE_PROD = value;
      fieldSetFlags()[20] = true;
      return this;
    }

    /**
      * Checks whether the 'DTE_PROD' field has been set.
      * @return True if the 'DTE_PROD' field has been set, false otherwise.
      */
    public boolean hasDTEPROD() {
      return fieldSetFlags()[20];
    }


    /**
      * Clears the value of the 'DTE_PROD' field.
      * @return This builder.
      */
    public com.mbusa.avro.dto.VehMstrDTO.Builder clearDTEPROD() {
      DTE_PROD = null;
      fieldSetFlags()[20] = false;
      return this;
    }

    /**
      * Gets the value of the 'DTS_CREA' field.
      * @return The value.
      */
    public java.lang.CharSequence getDTSCREA() {
      return DTS_CREA;
    }


    /**
      * Sets the value of the 'DTS_CREA' field.
      * @param value The value of 'DTS_CREA'.
      * @return This builder.
      */
    public com.mbusa.avro.dto.VehMstrDTO.Builder setDTSCREA(java.lang.CharSequence value) {
      validate(fields()[21], value);
      this.DTS_CREA = value;
      fieldSetFlags()[21] = true;
      return this;
    }

    /**
      * Checks whether the 'DTS_CREA' field has been set.
      * @return True if the 'DTS_CREA' field has been set, false otherwise.
      */
    public boolean hasDTSCREA() {
      return fieldSetFlags()[21];
    }


    /**
      * Clears the value of the 'DTS_CREA' field.
      * @return This builder.
      */
    public com.mbusa.avro.dto.VehMstrDTO.Builder clearDTSCREA() {
      DTS_CREA = null;
      fieldSetFlags()[21] = false;
      return this;
    }

    /**
      * Gets the value of the 'ID_CREA_USER' field.
      * @return The value.
      */
    public java.lang.CharSequence getIDCREAUSER() {
      return ID_CREA_USER;
    }


    /**
      * Sets the value of the 'ID_CREA_USER' field.
      * @param value The value of 'ID_CREA_USER'.
      * @return This builder.
      */
    public com.mbusa.avro.dto.VehMstrDTO.Builder setIDCREAUSER(java.lang.CharSequence value) {
      validate(fields()[22], value);
      this.ID_CREA_USER = value;
      fieldSetFlags()[22] = true;
      return this;
    }

    /**
      * Checks whether the 'ID_CREA_USER' field has been set.
      * @return True if the 'ID_CREA_USER' field has been set, false otherwise.
      */
    public boolean hasIDCREAUSER() {
      return fieldSetFlags()[22];
    }


    /**
      * Clears the value of the 'ID_CREA_USER' field.
      * @return This builder.
      */
    public com.mbusa.avro.dto.VehMstrDTO.Builder clearIDCREAUSER() {
      ID_CREA_USER = null;
      fieldSetFlags()[22] = false;
      return this;
    }

    /**
      * Gets the value of the 'DTS_LAST_UPDT' field.
      * @return The value.
      */
    public java.lang.CharSequence getDTSLASTUPDT() {
      return DTS_LAST_UPDT;
    }


    /**
      * Sets the value of the 'DTS_LAST_UPDT' field.
      * @param value The value of 'DTS_LAST_UPDT'.
      * @return This builder.
      */
    public com.mbusa.avro.dto.VehMstrDTO.Builder setDTSLASTUPDT(java.lang.CharSequence value) {
      validate(fields()[23], value);
      this.DTS_LAST_UPDT = value;
      fieldSetFlags()[23] = true;
      return this;
    }

    /**
      * Checks whether the 'DTS_LAST_UPDT' field has been set.
      * @return True if the 'DTS_LAST_UPDT' field has been set, false otherwise.
      */
    public boolean hasDTSLASTUPDT() {
      return fieldSetFlags()[23];
    }


    /**
      * Clears the value of the 'DTS_LAST_UPDT' field.
      * @return This builder.
      */
    public com.mbusa.avro.dto.VehMstrDTO.Builder clearDTSLASTUPDT() {
      DTS_LAST_UPDT = null;
      fieldSetFlags()[23] = false;
      return this;
    }

    /**
      * Gets the value of the 'ID_LAST_UPDT_USER' field.
      * @return The value.
      */
    public java.lang.CharSequence getIDLASTUPDTUSER() {
      return ID_LAST_UPDT_USER;
    }


    /**
      * Sets the value of the 'ID_LAST_UPDT_USER' field.
      * @param value The value of 'ID_LAST_UPDT_USER'.
      * @return This builder.
      */
    public com.mbusa.avro.dto.VehMstrDTO.Builder setIDLASTUPDTUSER(java.lang.CharSequence value) {
      validate(fields()[24], value);
      this.ID_LAST_UPDT_USER = value;
      fieldSetFlags()[24] = true;
      return this;
    }

    /**
      * Checks whether the 'ID_LAST_UPDT_USER' field has been set.
      * @return True if the 'ID_LAST_UPDT_USER' field has been set, false otherwise.
      */
    public boolean hasIDLASTUPDTUSER() {
      return fieldSetFlags()[24];
    }


    /**
      * Clears the value of the 'ID_LAST_UPDT_USER' field.
      * @return This builder.
      */
    public com.mbusa.avro.dto.VehMstrDTO.Builder clearIDLASTUPDTUSER() {
      ID_LAST_UPDT_USER = null;
      fieldSetFlags()[24] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public VehMstrDTO build() {
      try {
        VehMstrDTO record = new VehMstrDTO();
        record.ID_FIN = fieldSetFlags()[0] ? this.ID_FIN : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.ID_NUM_VIN = fieldSetFlags()[1] ? this.ID_NUM_VIN : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.NUM_MODL_YR = fieldSetFlags()[2] ? this.NUM_MODL_YR : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.CDE_MODL_CLS = fieldSetFlags()[3] ? this.CDE_MODL_CLS : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.CDE_WRLD_MFR = fieldSetFlags()[4] ? this.CDE_WRLD_MFR : (java.lang.CharSequence) defaultValue(fields()[4]);
        record.CDE_FIN_BAUREIHE = fieldSetFlags()[5] ? this.CDE_FIN_BAUREIHE : (java.lang.CharSequence) defaultValue(fields()[5]);
        record.CDE_MODL_SER = fieldSetFlags()[6] ? this.CDE_MODL_SER : (java.lang.CharSequence) defaultValue(fields()[6]);
        record.CDE_STR_PLANT = fieldSetFlags()[7] ? this.CDE_STR_PLANT : (java.lang.CharSequence) defaultValue(fields()[7]);
        record.CDE_SER_NUM = fieldSetFlags()[8] ? this.CDE_SER_NUM : (java.lang.CharSequence) defaultValue(fields()[8]);
        record.DES_SLS_MDL = fieldSetFlags()[9] ? this.DES_SLS_MDL : (java.lang.CharSequence) defaultValue(fields()[9]);
        record.NUM_PORD = fieldSetFlags()[10] ? this.NUM_PORD : (java.lang.CharSequence) defaultValue(fields()[10]);
        record.CDE_LTST_VEH_RTL_STAT = fieldSetFlags()[11] ? this.CDE_LTST_VEH_RTL_STAT : (java.lang.CharSequence) defaultValue(fields()[11]);
        record.ID_LTST_DLR = fieldSetFlags()[12] ? this.ID_LTST_DLR : (java.lang.CharSequence) defaultValue(fields()[12]);
        record.DTE_LTST_CUST_RTL_VEH = fieldSetFlags()[13] ? this.DTE_LTST_CUST_RTL_VEH : (java.lang.CharSequence) defaultValue(fields()[13]);
        record.CDE_LTST_SLS_PRI = fieldSetFlags()[14] ? this.CDE_LTST_SLS_PRI : (java.lang.CharSequence) defaultValue(fields()[14]);
        record.CDE_CTRY = fieldSetFlags()[15] ? this.CDE_CTRY : (java.lang.CharSequence) defaultValue(fields()[15]);
        record.DES_WRNTY_MODL = fieldSetFlags()[16] ? this.DES_WRNTY_MODL : (java.lang.CharSequence) defaultValue(fields()[16]);
        record.IND_WRNTY_VEH_STAT = fieldSetFlags()[17] ? this.IND_WRNTY_VEH_STAT : (java.lang.CharSequence) defaultValue(fields()[17]);
        record.CDE_INV_DLR = fieldSetFlags()[18] ? this.CDE_INV_DLR : (java.lang.CharSequence) defaultValue(fields()[18]);
        record.DTE_REGIS = fieldSetFlags()[19] ? this.DTE_REGIS : (java.lang.CharSequence) defaultValue(fields()[19]);
        record.DTE_PROD = fieldSetFlags()[20] ? this.DTE_PROD : (java.lang.CharSequence) defaultValue(fields()[20]);
        record.DTS_CREA = fieldSetFlags()[21] ? this.DTS_CREA : (java.lang.CharSequence) defaultValue(fields()[21]);
        record.ID_CREA_USER = fieldSetFlags()[22] ? this.ID_CREA_USER : (java.lang.CharSequence) defaultValue(fields()[22]);
        record.DTS_LAST_UPDT = fieldSetFlags()[23] ? this.DTS_LAST_UPDT : (java.lang.CharSequence) defaultValue(fields()[23]);
        record.ID_LAST_UPDT_USER = fieldSetFlags()[24] ? this.ID_LAST_UPDT_USER : (java.lang.CharSequence) defaultValue(fields()[24]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<VehMstrDTO>
    WRITER$ = (org.apache.avro.io.DatumWriter<VehMstrDTO>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<VehMstrDTO>
    READER$ = (org.apache.avro.io.DatumReader<VehMstrDTO>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.ID_FIN);

    out.writeString(this.ID_NUM_VIN);

    out.writeString(this.NUM_MODL_YR);

    out.writeString(this.CDE_MODL_CLS);

    out.writeString(this.CDE_WRLD_MFR);

    out.writeString(this.CDE_FIN_BAUREIHE);

    out.writeString(this.CDE_MODL_SER);

    out.writeString(this.CDE_STR_PLANT);

    out.writeString(this.CDE_SER_NUM);

    out.writeString(this.DES_SLS_MDL);

    out.writeString(this.NUM_PORD);

    out.writeString(this.CDE_LTST_VEH_RTL_STAT);

    out.writeString(this.ID_LTST_DLR);

    out.writeString(this.DTE_LTST_CUST_RTL_VEH);

    out.writeString(this.CDE_LTST_SLS_PRI);

    out.writeString(this.CDE_CTRY);

    out.writeString(this.DES_WRNTY_MODL);

    out.writeString(this.IND_WRNTY_VEH_STAT);

    out.writeString(this.CDE_INV_DLR);

    out.writeString(this.DTE_REGIS);

    out.writeString(this.DTE_PROD);

    out.writeString(this.DTS_CREA);

    out.writeString(this.ID_CREA_USER);

    out.writeString(this.DTS_LAST_UPDT);

    out.writeString(this.ID_LAST_UPDT_USER);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.ID_FIN = in.readString(this.ID_FIN instanceof Utf8 ? (Utf8)this.ID_FIN : null);

      this.ID_NUM_VIN = in.readString(this.ID_NUM_VIN instanceof Utf8 ? (Utf8)this.ID_NUM_VIN : null);

      this.NUM_MODL_YR = in.readString(this.NUM_MODL_YR instanceof Utf8 ? (Utf8)this.NUM_MODL_YR : null);

      this.CDE_MODL_CLS = in.readString(this.CDE_MODL_CLS instanceof Utf8 ? (Utf8)this.CDE_MODL_CLS : null);

      this.CDE_WRLD_MFR = in.readString(this.CDE_WRLD_MFR instanceof Utf8 ? (Utf8)this.CDE_WRLD_MFR : null);

      this.CDE_FIN_BAUREIHE = in.readString(this.CDE_FIN_BAUREIHE instanceof Utf8 ? (Utf8)this.CDE_FIN_BAUREIHE : null);

      this.CDE_MODL_SER = in.readString(this.CDE_MODL_SER instanceof Utf8 ? (Utf8)this.CDE_MODL_SER : null);

      this.CDE_STR_PLANT = in.readString(this.CDE_STR_PLANT instanceof Utf8 ? (Utf8)this.CDE_STR_PLANT : null);

      this.CDE_SER_NUM = in.readString(this.CDE_SER_NUM instanceof Utf8 ? (Utf8)this.CDE_SER_NUM : null);

      this.DES_SLS_MDL = in.readString(this.DES_SLS_MDL instanceof Utf8 ? (Utf8)this.DES_SLS_MDL : null);

      this.NUM_PORD = in.readString(this.NUM_PORD instanceof Utf8 ? (Utf8)this.NUM_PORD : null);

      this.CDE_LTST_VEH_RTL_STAT = in.readString(this.CDE_LTST_VEH_RTL_STAT instanceof Utf8 ? (Utf8)this.CDE_LTST_VEH_RTL_STAT : null);

      this.ID_LTST_DLR = in.readString(this.ID_LTST_DLR instanceof Utf8 ? (Utf8)this.ID_LTST_DLR : null);

      this.DTE_LTST_CUST_RTL_VEH = in.readString(this.DTE_LTST_CUST_RTL_VEH instanceof Utf8 ? (Utf8)this.DTE_LTST_CUST_RTL_VEH : null);

      this.CDE_LTST_SLS_PRI = in.readString(this.CDE_LTST_SLS_PRI instanceof Utf8 ? (Utf8)this.CDE_LTST_SLS_PRI : null);

      this.CDE_CTRY = in.readString(this.CDE_CTRY instanceof Utf8 ? (Utf8)this.CDE_CTRY : null);

      this.DES_WRNTY_MODL = in.readString(this.DES_WRNTY_MODL instanceof Utf8 ? (Utf8)this.DES_WRNTY_MODL : null);

      this.IND_WRNTY_VEH_STAT = in.readString(this.IND_WRNTY_VEH_STAT instanceof Utf8 ? (Utf8)this.IND_WRNTY_VEH_STAT : null);

      this.CDE_INV_DLR = in.readString(this.CDE_INV_DLR instanceof Utf8 ? (Utf8)this.CDE_INV_DLR : null);

      this.DTE_REGIS = in.readString(this.DTE_REGIS instanceof Utf8 ? (Utf8)this.DTE_REGIS : null);

      this.DTE_PROD = in.readString(this.DTE_PROD instanceof Utf8 ? (Utf8)this.DTE_PROD : null);

      this.DTS_CREA = in.readString(this.DTS_CREA instanceof Utf8 ? (Utf8)this.DTS_CREA : null);

      this.ID_CREA_USER = in.readString(this.ID_CREA_USER instanceof Utf8 ? (Utf8)this.ID_CREA_USER : null);

      this.DTS_LAST_UPDT = in.readString(this.DTS_LAST_UPDT instanceof Utf8 ? (Utf8)this.DTS_LAST_UPDT : null);

      this.ID_LAST_UPDT_USER = in.readString(this.ID_LAST_UPDT_USER instanceof Utf8 ? (Utf8)this.ID_LAST_UPDT_USER : null);

    } else {
      for (int i = 0; i < 25; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.ID_FIN = in.readString(this.ID_FIN instanceof Utf8 ? (Utf8)this.ID_FIN : null);
          break;

        case 1:
          this.ID_NUM_VIN = in.readString(this.ID_NUM_VIN instanceof Utf8 ? (Utf8)this.ID_NUM_VIN : null);
          break;

        case 2:
          this.NUM_MODL_YR = in.readString(this.NUM_MODL_YR instanceof Utf8 ? (Utf8)this.NUM_MODL_YR : null);
          break;

        case 3:
          this.CDE_MODL_CLS = in.readString(this.CDE_MODL_CLS instanceof Utf8 ? (Utf8)this.CDE_MODL_CLS : null);
          break;

        case 4:
          this.CDE_WRLD_MFR = in.readString(this.CDE_WRLD_MFR instanceof Utf8 ? (Utf8)this.CDE_WRLD_MFR : null);
          break;

        case 5:
          this.CDE_FIN_BAUREIHE = in.readString(this.CDE_FIN_BAUREIHE instanceof Utf8 ? (Utf8)this.CDE_FIN_BAUREIHE : null);
          break;

        case 6:
          this.CDE_MODL_SER = in.readString(this.CDE_MODL_SER instanceof Utf8 ? (Utf8)this.CDE_MODL_SER : null);
          break;

        case 7:
          this.CDE_STR_PLANT = in.readString(this.CDE_STR_PLANT instanceof Utf8 ? (Utf8)this.CDE_STR_PLANT : null);
          break;

        case 8:
          this.CDE_SER_NUM = in.readString(this.CDE_SER_NUM instanceof Utf8 ? (Utf8)this.CDE_SER_NUM : null);
          break;

        case 9:
          this.DES_SLS_MDL = in.readString(this.DES_SLS_MDL instanceof Utf8 ? (Utf8)this.DES_SLS_MDL : null);
          break;

        case 10:
          this.NUM_PORD = in.readString(this.NUM_PORD instanceof Utf8 ? (Utf8)this.NUM_PORD : null);
          break;

        case 11:
          this.CDE_LTST_VEH_RTL_STAT = in.readString(this.CDE_LTST_VEH_RTL_STAT instanceof Utf8 ? (Utf8)this.CDE_LTST_VEH_RTL_STAT : null);
          break;

        case 12:
          this.ID_LTST_DLR = in.readString(this.ID_LTST_DLR instanceof Utf8 ? (Utf8)this.ID_LTST_DLR : null);
          break;

        case 13:
          this.DTE_LTST_CUST_RTL_VEH = in.readString(this.DTE_LTST_CUST_RTL_VEH instanceof Utf8 ? (Utf8)this.DTE_LTST_CUST_RTL_VEH : null);
          break;

        case 14:
          this.CDE_LTST_SLS_PRI = in.readString(this.CDE_LTST_SLS_PRI instanceof Utf8 ? (Utf8)this.CDE_LTST_SLS_PRI : null);
          break;

        case 15:
          this.CDE_CTRY = in.readString(this.CDE_CTRY instanceof Utf8 ? (Utf8)this.CDE_CTRY : null);
          break;

        case 16:
          this.DES_WRNTY_MODL = in.readString(this.DES_WRNTY_MODL instanceof Utf8 ? (Utf8)this.DES_WRNTY_MODL : null);
          break;

        case 17:
          this.IND_WRNTY_VEH_STAT = in.readString(this.IND_WRNTY_VEH_STAT instanceof Utf8 ? (Utf8)this.IND_WRNTY_VEH_STAT : null);
          break;

        case 18:
          this.CDE_INV_DLR = in.readString(this.CDE_INV_DLR instanceof Utf8 ? (Utf8)this.CDE_INV_DLR : null);
          break;

        case 19:
          this.DTE_REGIS = in.readString(this.DTE_REGIS instanceof Utf8 ? (Utf8)this.DTE_REGIS : null);
          break;

        case 20:
          this.DTE_PROD = in.readString(this.DTE_PROD instanceof Utf8 ? (Utf8)this.DTE_PROD : null);
          break;

        case 21:
          this.DTS_CREA = in.readString(this.DTS_CREA instanceof Utf8 ? (Utf8)this.DTS_CREA : null);
          break;

        case 22:
          this.ID_CREA_USER = in.readString(this.ID_CREA_USER instanceof Utf8 ? (Utf8)this.ID_CREA_USER : null);
          break;

        case 23:
          this.DTS_LAST_UPDT = in.readString(this.DTS_LAST_UPDT instanceof Utf8 ? (Utf8)this.DTS_LAST_UPDT : null);
          break;

        case 24:
          this.ID_LAST_UPDT_USER = in.readString(this.ID_LAST_UPDT_USER instanceof Utf8 ? (Utf8)this.ID_LAST_UPDT_USER : null);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










